In [1]:
import numpy as np
import pandas as pd
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

year = 2026
quarter = 1
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-02-15 10:12:43

In [5]:
# Must modify select date to latest unprocess date
select_date = date(2026, 1, 1)
select_date = select_date.strftime("%Y-%m-%d")
select_date

'2026-01-01'

In [7]:
cols = "name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y".split()
colt = "year quarter q_amt y_amt aq_amt ay_amt".split()
colu = 'name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt q_amt_p'.split() 
colv = 'name year quarter kind latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt \
        inc_amt_py inc_pct_py q_amt_p inc_amt_pq inc_pct_pq \
        ticker_id mean_pct std_pct'.split()
colw = 'name year quarter kind_x latest_amt_y_x previous_amt_y_x inc_amt_y_x inc_pct_y_x \
        latest_amt_q_x previous_amt_q_x inc_amt_q_x inc_pct_q_x q_amt_c_x y_amt_x \
        inc_amt_py_x inc_pct_py_x q_amt_p_x inc_amt_pq_x inc_pct_pq_x \
        ticker_id_x mean_pct_x std_pct_x'.split()

format_dict = {
    'q_amt': '{:,}',
    'y_amt': '{:,}',
    'yoy_gain': '{:,}',
    'q_amt_c': '{:,}',
    'q_amt_p': '{:,}',
    'aq_amt': '{:,}',
    'ay_amt': '{:,}',
    'acc_gain': '{:,}',
    'latest_amt': '{:,}',
    'previous_amt': '{:,}',
    'inc_amt': '{:,}',
    'inc_amt_pq': '{:,}',
    'inc_amt_py': '{:,}',    
    'latest_amt_q': '{:,}',
    'previous_amt_q': '{:,}',
    'inc_amt_q': '{:,}',
    'latest_amt_y': '{:,}',
    'previous_amt_y': '{:,}',
    'inc_amt_y': '{:,}',
    'kind_x': '{:,}',
    'inc_pct': '{:.2f}%',
    'inc_pct_q': '{:.2f}%',
    'inc_pct_y': '{:.2f}%',
    'inc_pct_pq': '{:.2f}%',
    'inc_pct_py': '{:.2f}%',   
    'mean_pct': '{:.2f}%',
    'std_pct': '{:.2f}%',      
}

### Process for specified stocks

In [10]:
names = """
IP
""".split()
names

['IP']

In [12]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'IP'"

In [14]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = %s AND quarter = %s
AND name IN (%s)
"""
sql = sql % (year, quarter, in_p)
df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.style.format(format_dict)

### End of Process for specified stocks

In [17]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = %s AND quarter = %s
AND publish_date >= '%s'
"""
sql = sql % (year, quarter, select_date)
print(sql)
df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.style.format(format_dict)

SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt
FROM epss
WHERE year = 2026 AND quarter = 1
AND publish_date >= '2026-01-01'

### End of Normal Process

In [20]:
sql = """
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM qt_profits 
WHERE year = %s AND quarter = 'Q%s'
"""
sql = sql % (year, quarter)
print(sql)
df_qt_profits = pd.read_sql(sql, conlt)
df_qt_profits.shape

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM qt_profits
WHERE year = 2026 AND quarter = 'Q1'

(4, 7)

In [22]:
epss_inp_qt_profits = pd.merge(df_epss_inp, df_qt_profits, on=["name"], suffixes=(["_e", "_q"]), how="inner")
epss_inp_qt_profits.head(5).style.format(format_dict)

### Delete duplicated year and quarter

In [25]:
columns = ["year_q", "quarter_q"]
epss_inp_qt_profits = epss_inp_qt_profits.drop(columns, axis=1)
epss_inp_qt_profits.head(5).style.format(format_dict)

In [29]:
sql = """
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM yr_profits 
WHERE year = %s AND quarter = 'Q%s'
"""
sql = sql % (year, quarter)
print(sql)
df_yr_profits = pd.read_sql(sql, conlt)
df_yr_profits.style.format(format_dict)

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM yr_profits
WHERE year = 2026 AND quarter = 'Q1'

In [31]:
df_merge2 = pd.merge(
    epss_inp_qt_profits, df_yr_profits, on=["name"], suffixes=(["_q", "_y"]), how="inner"
)
df_merge2.head(5).style.format(format_dict)

### Delete duplicated year and quarter

In [34]:
columns = ["year_e", "quarter_e"]
df_aggr = df_merge2.drop(columns, axis=1)
df_aggr.head().style.format(format_dict)

### profits criteria
1. Yearly profit amount > 440 millions
2. Previous yearly gain amount > 400 millions
3. Yearly gain percent >= 10 percent
4. YoY Profit Higher

In [37]:
df_aggr[df_aggr["name"] == "STANLY"].style.format(format_dict)

In [39]:
criteria_1 = df_aggr.latest_amt_y > 440_000
df_aggr.loc[criteria_1, cols].sort_values(by=["name"], ascending=True).style.format(format_dict)

In [41]:
criteria_2 = df_aggr.previous_amt_y >= 400_000
df_aggr.loc[criteria_2, cols].sort_values(by=["name"], ascending=True).style.format(format_dict)

In [43]:
criteria_3 = df_aggr.inc_pct_y >= 10.00
df_aggr.loc[criteria_3, cols].style.format(format_dict)

In [45]:
criteria_4 = (df_aggr.q_amt > df_aggr.y_amt)
colt = 'name q_amt y_amt inc_amt_q inc_pct_q'.split()
df_aggr.loc[criteria_4,colt].sort_values(['inc_pct_q'],ascending=[False]).style.format(format_dict)

In [47]:
profits_criteria = criteria_1 & criteria_2 & criteria_3 & criteria_4
#df_aggr_criteria = criteria_1 & criteria_2 
filter = df_aggr.loc[profits_criteria]
filter.sort_values('name').style.format(format_dict)

In [49]:
columns = 'year quarter q_amt y_amt aq_amt ay_amt'.split()
pre_final = filter.drop(columns, axis=1)
pre_final.sort_values(['name'],ascending=[True]).style.format(format_dict)

In [51]:
final = pre_final.copy()
final.style.format(format_dict)

In [53]:
final.sort_values(by=["name"], ascending=True).style.format(format_dict)

In [55]:
sql = """
SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p 
FROM epss A JOIN epss B ON a.name = B.name 
WHERE A.year = %s AND A.quarter = %s 
AND B.year = %s-1 AND B.quarter = %s"""
sql = sql % (year, quarter, year, quarter)
print(sql)

SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p
FROM epss A JOIN epss B ON a.name = B.name
WHERE A.year = 2026 AND A.quarter = 1
AND B.year = 2026-1 AND B.quarter = 1

In [57]:
epss2 = pd.read_sql(sql, conlt)
epss2.head().style.format(format_dict)

In [59]:
df_merge3 = pd.merge(final, epss2, on=["name"], suffixes=(["_f", "_e"]), how="inner")
df_merge3.style.format(format_dict)

### The fifth criteria, added on 2022q1

In [62]:
mask = (df_merge3.q_amt_c > df_merge3.q_amt_p)
df_merge3 = df_merge3[mask]
df_merge3

Empty DataFrame
Columns: [name, latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q, latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y, year, quarter, q_amt_c, y_amt, q_amt_p]
Index: []

In [64]:
final2 = df_merge3[colu].copy()
final2.style.format(format_dict)

### If there is no record in the above statement, no need to further process

In [67]:
def better(vals):
    current, previous = vals
    if current > previous:
        return 1
    else:
        return 0

In [69]:
final2["kind"] = final2[["q_amt_c", "q_amt_p"]].apply(better, axis=1)

In [71]:
final2.kind.value_counts()

Series([], Name: count, dtype: int64)

In [73]:
final2.loc[:, "inc_amt_py"] = final2["q_amt_c"] - final2["y_amt"]
final2.loc[:, "inc_pct_py"] = final2["inc_amt_py"] / abs(final2["y_amt"]) * 100

final2.loc[:, "inc_amt_pq"] = final2["q_amt_c"] - final2["q_amt_p"]
final2.loc[:, "inc_pct_pq"] = final2["inc_amt_pq"] / abs(final2["q_amt_p"]) * 100

In [75]:
final2.loc[:, "inc_pct_py"].replace("inf", np.nan, inplace=True)

C:\Users\PC1\AppData\Local\Temp\ipykernel_25324\1111459344.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final2.loc[:, "inc_pct_py"].replace("inf", np.nan, inplace=True)

In [77]:
final2.loc[:, "mean_pct"] = final2[
    ["inc_pct_y", "inc_pct_q", "inc_pct_py", "inc_pct_pq"]
].mean(axis=1, skipna=True)

In [79]:
final2[["name", "mean_pct"]].sort_values(by=["mean_pct"], ascending=False)

Empty DataFrame
Columns: [name, mean_pct]
Index: []

In [81]:
# First ensure it's a copy
final3 = final2.copy()
final3["std_pct"] = final3[["inc_pct_y", "inc_pct_q", "inc_pct_py", "inc_pct_pq"]].std(
    axis=1
)

In [83]:
final3[["name", "std_pct"]].sort_values(by=["std_pct"], ascending=True)

Empty DataFrame
Columns: [name, std_pct]
Index: []

In [85]:
sql = "SELECT name, id, market FROM tickers"
tickers = pd.read_sql(sql, conlt)
tickers.head().style.format(format_dict)

In [87]:
df_merge4 = pd.merge(final3, tickers, on="name", how="inner")
df_merge4.rename(columns={"id": "ticker_id"}, inplace=True)

final4 = df_merge4[colv].copy()
final4.style.format(format_dict)

In [89]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
print(sql)

SELECT *
FROM profits
WHERE year = 2026 AND quarter = 1
ORDER BY name

In [91]:
profits = pd.read_sql(sql, conlt)
profits.head().style.format(format_dict)

In [93]:
df_merge = pd.merge(
    final4, profits, on=["name", "year", "quarter"], how="outer", indicator=True
)
df_merge.head().style.format(format_dict)

In [95]:
final5 = df_merge[df_merge["_merge"] == "left_only"]
final5

Empty DataFrame
Columns: [name, year, quarter, kind_x, latest_amt_y_x, previous_amt_y_x, inc_amt_y_x, inc_pct_y_x, latest_amt_q_x, previous_amt_q_x, inc_amt_q_x, inc_pct_q_x, q_amt_c_x, y_amt_x, inc_amt_py_x, inc_pct_py_x, q_amt_p_x, inc_amt_pq_x, inc_pct_pq_x, ticker_id_x, mean_pct_x, std_pct_x, id, kind_y, latest_amt_y_y, previous_amt_y_y, inc_amt_y_y, inc_pct_y_y, latest_amt_q_y, previous_amt_q_y, inc_amt_q_y, inc_pct_q_y, q_amt_c_y, y_amt_y, inc_amt_py_y, inc_pct_py_y, q_amt_p_y, inc_amt_pq_y, inc_pct_pq_y, ticker_id_y, mean_pct_y, std_pct_y, _merge]
Index: []

[0 rows x 43 columns]

In [97]:
final6 = final5[colw]
final6.sort_values('name')

Empty DataFrame
Columns: [name, year, quarter, kind_x, latest_amt_y_x, previous_amt_y_x, inc_amt_y_x, inc_pct_y_x, latest_amt_q_x, previous_amt_q_x, inc_amt_q_x, inc_pct_q_x, q_amt_c_x, y_amt_x, inc_amt_py_x, inc_pct_py_x, q_amt_p_x, inc_amt_pq_x, inc_pct_pq_x, ticker_id_x, mean_pct_x, std_pct_x]
Index: []

[0 rows x 22 columns]

In [99]:
rcds = final6.values.tolist()
len(rcds)

0

In [101]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
print(sql)
lt_profits = pd.read_sql(sql, conlt)
lt_profits.head().style.format(format_dict)

SELECT *
FROM profits
WHERE year = 2026 AND quarter = 1
ORDER BY name

In [103]:
# 1. First replace inf in the DataFrame
lt_profits['inc_pct_py'] = lt_profits['inc_pct_py'].replace([np.inf, -np.inf], 999.99)
lt_profits['mean_pct'] = lt_profits['mean_pct'].replace([np.inf, -np.inf], 999.99)

# Now when you print rcds, you'll see 999.99 instead of inf
lt_profits.style.format(format_dict)

In [105]:
# Define SQL statement using named placeholders
sql = text("""
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)
""")

# Convert list data to dictionaries for named parameters
columns = [
    "name", "year", "quarter", "kind",
    "latest_amt_y", "previous_amt_y", "inc_amt_y", "inc_pct_y",
    "latest_amt_q", "previous_amt_q", "inc_amt_q", "inc_pct_q",
    "q_amt_c", "y_amt", "inc_amt_py", "inc_pct_py",
    "q_amt_p", "inc_amt_pq", "inc_pct_pq",
    "ticker_id", "mean_pct", "std_pct"
]

records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]

# Check for empty records before attempting insertion
if not rcds:
    print("No records to insert - skipping database operation")
    # In notebook/script context, just proceed to next cell instead of 'return'
else:
    try:
        # Convert list data to dictionaries for named parameters
#        records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]
        conlt.execute(sql, records_dicts)
        conlt.commit()
        print(f"Successfully inserted {len(records_dicts)} records")
    except Exception as e:
        conlt.rollback()
        print("Insert failed:", e)
    finally:
        conlt.commit()

No records to insert - skipping database operation

In [107]:
# Replace 'inf' with 999.99 in specific columns
lt_profits['inc_pct_py'] = lt_profits['inc_pct_py'].replace([np.inf, -np.inf], 999.99)
lt_profits['mean_pct'] = lt_profits['mean_pct'].replace([np.inf, -np.inf], 999.99)

In [109]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
profits = pd.read_sql(sql, conlt)
profits.head().style.format(format_dict)

### End of Create Data

In [112]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y:%m:%d %H:%M:%S")
print(formatted_time)

2026:02:15 10:15:30