In [1]:
import numpy as np
import pandas as pd
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

year = 2026
quarter = 1
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-05-17 14:52:33

In [3]:
# Must modify select date to latest unprocess date
select_date = date(2026, 4, 1)
select_date = select_date.strftime("%Y-%m-%d")
select_date

'2026-04-01'

In [5]:
cols = "name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y".split()
colt = "year quarter q_amt y_amt aq_amt ay_amt".split()
colu = 'name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt q_amt_p'.split() 
colv = 'name year quarter kind latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt \
        inc_amt_py inc_pct_py q_amt_p inc_amt_pq inc_pct_pq \
        ticker_id mean_pct std_pct'.split()
colw = 'name year quarter kind_x latest_amt_y_x previous_amt_y_x inc_amt_y_x inc_pct_y_x \
        latest_amt_q_x previous_amt_q_x inc_amt_q_x inc_pct_q_x q_amt_c_x y_amt_x \
        inc_amt_py_x inc_pct_py_x q_amt_p_x inc_amt_pq_x inc_pct_pq_x \
        ticker_id_x mean_pct_x std_pct_x'.split()

format_dict = {
    'q_amt': '{:,}',
    'y_amt': '{:,}',
    'yoy_gain': '{:,}',
    'q_amt_c': '{:,}',
    'q_amt_p': '{:,}',
    'aq_amt': '{:,}',
    'ay_amt': '{:,}',
    'acc_gain': '{:,}',
    'latest_amt': '{:,}',
    'previous_amt': '{:,}',
    'inc_amt': '{:,}',
    'inc_amt_pq': '{:,}',
    'inc_amt_py': '{:,}',    
    'latest_amt_q': '{:,}',
    'previous_amt_q': '{:,}',
    'inc_amt_q': '{:,}',
    'latest_amt_y': '{:,}',
    'previous_amt_y': '{:,}',
    'inc_amt_y': '{:,}',
    'kind_x': '{:,}',
    'inc_pct': '{:.2f}%',
    'inc_pct_q': '{:.2f}%',
    'inc_pct_y': '{:.2f}%',
    'inc_pct_pq': '{:.2f}%',
    'inc_pct_py': '{:.2f}%',   
    'mean_pct': '{:.2f}%',
    'std_pct': '{:.2f}%',      
}

### Process for specified stocks

In [38]:
# Can input only one stock
names = """
IP
""".split()
names

['IP']

In [40]:
stock_list = names
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

IP

In [42]:
sql = f"""
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = {year} AND quarter = {quarter}
AND name IN ('{stock_list_str}')
"""
print(sql)
df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.style.format(format_dict)

SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt
FROM epss
WHERE year = 2026 AND quarter = 1
AND name IN ('IP')

### End of Process for specified stocks

In [7]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = %s AND quarter = %s
AND publish_date >= '%s'
"""
sql = sql % (year, quarter, select_date)
print(sql)
df_epss_inp = pd.read_sql(sql, conlt)
#df_epss_inp.style.format(format_dict)
df_epss_inp.shape

SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt
FROM epss
WHERE year = 2026 AND quarter = 1
AND publish_date >= '2026-04-01'

(176, 7)

### End of Normal Process

In [9]:
sql = """
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM qt_profits 
WHERE year = %s AND quarter = 'Q%s'
"""
sql = sql % (year, quarter)
print(sql)
df_qt_profits = pd.read_sql(sql, conlt)
df_qt_profits.shape

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM qt_profits
WHERE year = 2026 AND quarter = 'Q1'

(181, 7)

In [11]:
epss_inp_qt_profits = pd.merge(df_epss_inp, df_qt_profits, on=["name"], suffixes=(["_e", "_q"]), how="inner")
epss_inp_qt_profits.head(5).style.format(format_dict)

### Delete duplicated year and quarter

In [14]:
columns = ["year_q", "quarter_q"]
epss_inp_qt_profits = epss_inp_qt_profits.drop(columns, axis=1)
epss_inp_qt_profits.head(5).style.format(format_dict)

In [16]:
sql = """
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM yr_profits 
WHERE year = %s AND quarter = 'Q%s'
"""
sql = sql % (year, quarter)
print(sql)
df_yr_profits = pd.read_sql(sql, conlt)
#df_yr_profits.style.format(format_dict)
df_yr_profits.shape

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM yr_profits
WHERE year = 2026 AND quarter = 'Q1'

(181, 7)

In [18]:
df_merge2 = pd.merge(
    epss_inp_qt_profits, df_yr_profits, on=["name"], suffixes=(["_q", "_y"]), how="inner"
)
df_merge2.head(5).style.format(format_dict)

### Delete duplicated year and quarter

In [21]:
columns = ["year_e", "quarter_e"]
df_aggr = df_merge2.drop(columns, axis=1)
df_aggr.head().style.format(format_dict)

### profits criteria
1. Yearly profit amount > 440 millions
2. Previous yearly gain amount > 400 millions
3. Yearly gain percent >= 10 percent
4. YoY Profit Higher

In [24]:
df_aggr[df_aggr["name"] == "TVO"].style.format(format_dict)

In [26]:
criteria_1 = df_aggr.latest_amt_y > 440_000
df_aggr.loc[criteria_1, cols].sort_values(by=["name"], ascending=True).style.format(format_dict)

In [28]:
criteria_2 = df_aggr.previous_amt_y >= 400_000
df_aggr.loc[criteria_2, cols].sort_values(by=["name"], ascending=True).style.format(format_dict)

In [30]:
criteria_3 = df_aggr.inc_pct_y >= 10.00
df_aggr.loc[criteria_3, cols].style.format(format_dict)

In [32]:
criteria_4 = (df_aggr.q_amt > df_aggr.y_amt)
colt = 'name q_amt y_amt inc_amt_q inc_pct_q'.split()
df_aggr.loc[criteria_4,colt].sort_values(['inc_pct_q'],ascending=[False]).style.format(format_dict)

In [34]:
profits_criteria = criteria_1 & criteria_2 & criteria_3 & criteria_4
#df_aggr_criteria = criteria_1 & criteria_2 
filter = df_aggr.loc[profits_criteria]
filter.sort_values('name').style.format(format_dict)

In [36]:
columns = 'year quarter q_amt y_amt aq_amt ay_amt'.split()
pre_final = filter.drop(columns, axis=1)
pre_final.sort_values(['name'],ascending=[True]).style.format(format_dict)

In [38]:
final = pre_final.copy()
final.style.format(format_dict)

In [40]:
final.sort_values(by=["name"], ascending=True).style.format(format_dict)

In [42]:
sql = """
SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p 
FROM epss A JOIN epss B ON a.name = B.name 
WHERE A.year = %s AND A.quarter = %s 
AND B.year = %s-1 AND B.quarter = %s"""
sql = sql % (year, quarter, year, quarter)
print(sql)

SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p
FROM epss A JOIN epss B ON a.name = B.name
WHERE A.year = 2026 AND A.quarter = 1
AND B.year = 2026-1 AND B.quarter = 1

In [44]:
epss2 = pd.read_sql(sql, conlt)
epss2.head().style.format(format_dict)

In [46]:
df_merge3 = pd.merge(final, epss2, on=["name"], suffixes=(["_f", "_e"]), how="inner")
df_merge3.style.format(format_dict)

### The fifth criteria, added on 2022q1

In [49]:
mask = (df_merge3.q_amt_c > df_merge3.q_amt_p)
df_merge3 = df_merge3[mask]
df_merge3

,name,latest_amt_q,previous_amt_q,inc_amt_q,inc_pct_q,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,year,quarter,q_amt_c,y_amt,q_amt_p
0,KKP,6806788,5912913,893875,15.12,6806788,4985068,1821720,36.54,2026,1,1955494,1061619,1061619
1,KTB,48952081,48228603,723478,1.50,48952081,43855657,5096424,11.62,2026,1,12437176,11713698,11713698
2,DELTA,28407374,24814324,3593050,14.48,28407374,18938580,9468794,50.00,2026,1,9081176,5488126,5488126
3,SCGP,4735791,4069495,666296,16.37,4735791,3699083,1036708,28.03,2026,1,1566168,899872,899872
4,SCC,19199135,14075020,5124115,36.41,19199135,6341638,12857497,202.75,2026,1,6222963,1098848,1098848
5,TVO,2364101,2188791,175310,8.01,2364101,2103105,260996,12.41,2026,1,708925,533615,533615
6,ADVANC,50797881,47885902,2911979,6.08,50797881,35075357,15722524,44.82,2026,1,13495505,10583526,10583526
7,WHART,2358805,2349806,8999,0.38,2358805,1920946,437859,22.79,2026,1,674906,665907,665907
8,THANI,1234581,1147837,86744,7.56,1234581,800211,434370,54.28,2026,1,340348,253604,253604
9,TPIPL,2107706,1998504,109202,5.46,2107706,1442498,665208,46.12,2026,1,832438,723236,723236
10,GUNKUL,1857507,1768709,88798,5.02,1857507,1660831,196676,11.84,2026,1,455763,366965,366965
11,TIDLOR,5248767,3622141,1626626,44.91,5248767,4230480,1018287,24.07,2026,1,1613744,1197815,-12882
12,GPSC,6978315,6399003,579312,9.05,6978315,4062379,2915936,71.78,2026,1,1719348,1140036,1140036
14,SYNEX,802946,769786,33160,4.31,802946,627721,175225,27.91,2026,1,221377,188217,188217
15,TFG,7451307,7440837,10470,0.14,7451307,3166564,4284743,135.31,2026,1,2047091,2036621,2036621
16,TCAP,8163458,7749834,413624,5.34,8163458,6646024,1517434,22.83,2026,1,2123240,1709616,1709616
17,CENTEL,3387598,1992901,1394697,69.98,3387598,1752985,1634613,93.25,2026,1,2142542,747845,747845
18,TOP,30561848,14584201,15977647,109.55,30561848,9958628,20603220,206.89,2026,1,19481157,3503510,3503510
19,BPP,8329005,3026277,5302728,175.22,8329005,1746321,6582684,376.95,2026,1,5877083,574355,574355
20,COM7,4309060,4063532,245528,6.04,4309060,3307162,1001898,30.29,2026,1,1226182,980654,980654
21,MTC,6975094,6723275,251819,3.75,6975094,5867308,1107786,18.88,2026,1,1823034,1571215,1571215
22,BLA,7384829,6968375,416454,5.98,7384829,4317070,3067759,71.06,2026,1,1605539,1250525,1189085
23,KGI,987326,866402,120924,13.96,987326,864737,122589,14.18,2026,1,318590,197666,197666
24,TTW,3270342,3266088,4254,0.13,3270342,2790939,479403,17.18,2026,1,672938,668684,668684
25,BGRIM,1742731,1675487,67244,4.01,1742731,1556871,185860,11.94,2026,1,721178,653934,653934
26,CPALL,29738684,28206100,1532584,5.43,29738684,25345841,4392843,17.33,2026,1,9117822,7585238,7585238
27,DIF,13891180,13855643,35537,0.26,13891180,656288,13234892,2016.63,2026,1,2767480,2731943,2731943
28,SPRC,9222759,2569354,6653405,258.95,9222759,2234886,6987873,312.67,2026,1,7366927,713522,713522
29,BCP,6908168,2879701,4028467,139.89,6908168,2184088,4724080,216.30,2026,1,6143762,2115295,2115295
30,TOA,3137161,2917013,220148,7.55,3137161,1919604,1217557,63.43,2026,1,953247,733099,733099
31,CK,3375096,3328223,46873,1.41,3375096,1445903,1929193,133.42,2026,1,329116,282243,282243
32,CPN,19584844,18841255,743589,3.95,19584844,16729046,2855798,17.07,2026,1,4970796,4227207,4227207
33,SIS,932467,876418,56049,6.40,932467,697604,234863,33.67,2026,1,258003,201954,201954
34,VIBHA,1805630,1694894,110736,6.53,1805630,698606,1107024,158.46,2026,1,136719,25983,25983
35,AMATA,3697994,3148658,549336,17.45,3697994,2482899,1215095,48.94,2026,1,1378517,829181,829181
36,BKIH,3634595,3063951,570644,18.62,3634595,3014794,619801,20.56,2026,1,1129143,558499,558499
37,CKP,2890971,2781825,109146,3.92,2890971,1344536,1546435,115.02,2026,1,179611,70465,70465
38,MINT,9241257,9009342,231915,2.57,9241257,7750222,1491035,19.24,2026,1,648780,416865,416865
39,ONEE,527725,450472,77253,17.15,527725,421017,106708,25.35,2026,1,53720,-23533,-23533

In [51]:
final2 = df_merge3[colu].copy()
final2.style.format(format_dict)

### If there is no record in the above statement, no need to further process

In [54]:
def better(vals):
    current, previous = vals
    if current > previous:
        return 1
    else:
        return 0

In [56]:
final2["kind"] = final2[["q_amt_c", "q_amt_p"]].apply(better, axis=1)

In [58]:
final2.kind.value_counts()

kind
1    39
Name: count, dtype: int64

In [60]:
final2.loc[:, "inc_amt_py"] = final2["q_amt_c"] - final2["y_amt"]
final2.loc[:, "inc_pct_py"] = final2["inc_amt_py"] / abs(final2["y_amt"]) * 100

final2.loc[:, "inc_amt_pq"] = final2["q_amt_c"] - final2["q_amt_p"]
final2.loc[:, "inc_pct_pq"] = final2["inc_amt_pq"] / abs(final2["q_amt_p"]) * 100

In [62]:
final2.loc[:, "inc_pct_py"].replace("inf", np.nan, inplace=True)

C:\Users\PC1\AppData\Local\Temp\ipykernel_26360\1111459344.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final2.loc[:, "inc_pct_py"].replace("inf", np.nan, inplace=True)

In [64]:
final2.loc[:, "mean_pct"] = final2[
    ["inc_pct_y", "inc_pct_q", "inc_pct_py", "inc_pct_pq"]
].mean(axis=1, skipna=True)

In [66]:
final2[["name", "mean_pct"]].sort_values(by=["mean_pct"], ascending=False)

      name     mean_pct
11  TIDLOR  3182.706774
28    SPRC   609.141850
19     BPP   599.667105
27     DIF   504.872898
18     TOP   307.133425
4      SCC   292.948499
34   VIBHA   254.340676
29     BCP   184.269845
39    ONEE   174.762594
17  CENTEL   134.055232
37     CKP   107.181959
36    BKIH    60.882289
0      KKP    55.014614
35   AMATA    49.722716
2    DELTA    48.854762
3     SCGP    48.121710
12    GPSC    45.615119
31      CK    42.011160
23     KGI    37.622962
22     BLA    35.113065
15     TFG    34.119543
38    MINT    33.269059
30     TOA    32.759889
8    THANI    32.562254
6   ADVANC    26.482131
33     SIS    23.894175
20    COM7    21.601085
5      TVO    21.531637
9    TPIPL    20.444541
16    TCAP    19.139486
14   SYNEX    16.863981
10  GUNKUL    16.313974
26   CPALL    15.792412
32     CPN    14.050275
21     MTC    13.671012
25   BGRIM     9.128997
7    WHART     6.468195
1      KTB     6.368171
24     TTW     4.645587

In [68]:
# First ensure it's a copy
final3 = final2.copy()
final3["std_pct"] = final3[["inc_pct_y", "inc_pct_q", "inc_pct_py", "inc_pct_pq"]].std(
    axis=1
)

In [70]:
final3[["name", "std_pct"]].sort_values(by=["std_pct"], ascending=True)

      name      std_pct
25   BGRIM     3.500918
1      KTB     4.137406
32     CPN     6.737987
21     MTC     6.749361
26   CPALL     7.039946
24     TTW     8.359681
16    TCAP     9.222099
10  GUNKUL     9.519881
14   SYNEX     9.673916
20    COM7    10.665489
7    WHART    10.890834
33     SIS    11.991655
5      TVO    13.195932
6   ADVANC    15.860380
9    TPIPL    17.709823
8    THANI    19.167396
35   AMATA    23.010662
30     TOA    23.029700
2    DELTA    24.048815
12    GPSC    26.303938
38    MINT    26.705487
22     BLA    26.994667
23     KGI    27.196766
3     SCGP    30.307963
29     BCP    31.998744
0      KKP    34.815585
36    BKIH    47.686806
17  CENTEL    61.293442
31      CK    61.358891
15     TFG    67.460535
37     CKP    71.361356
18     TOP   176.482644
39    ONEE   177.292683
34   VIBHA   207.898299
4      SCC   211.393033
28    SPRC   373.995036
19     BPP   382.609031
27     DIF  1007.838187
11  TIDLOR  6296.283312

In [72]:
sql = "SELECT name, id, market FROM tickers"
tickers = pd.read_sql(sql, conlt)
tickers.head().style.format(format_dict)

In [74]:
df_merge4 = pd.merge(final3, tickers, on="name", how="inner")
df_merge4.rename(columns={"id": "ticker_id"}, inplace=True)

final4 = df_merge4[colv].copy()
final4.style.format(format_dict)

In [76]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
print(sql)

SELECT *
FROM profits
WHERE year = 2026 AND quarter = 1
ORDER BY name

In [78]:
profits = pd.read_sql(sql, conlt)
profits.head().style.format(format_dict)

In [80]:
df_merge = pd.merge(
    final4, profits, on=["name", "year", "quarter"], how="outer", indicator=True
)
df_merge.head().style.format(format_dict)

In [82]:
final5 = df_merge[df_merge["_merge"] == "left_only"]
final5

,name,year,quarter,kind_x,latest_amt_y_x,previous_amt_y_x,inc_amt_y_x,inc_pct_y_x,latest_amt_q_x,previous_amt_q_x,...,y_amt_y,inc_amt_py_y,inc_pct_py_y,q_amt_p_y,inc_amt_pq_y,inc_pct_pq_y,ticker_id_y,mean_pct_y,std_pct_y,_merge
1,AMATA,2026,1,1,3697994,2482899,1215095,48.94,3697994,3148658,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,BCP,2026,1,1,6908168,2184088,4724080,216.30,6908168,2879701,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,BGRIM,2026,1,1,1742731,1556871,185860,11.94,1742731,1675487,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,BKIH,2026,1,1,3634595,3014794,619801,20.56,3634595,3063951,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5,BLA,2026,1,1,7384829,4317070,3067759,71.06,7384829,6968375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
6,BPP,2026,1,1,8329005,1746321,6582684,376.95,8329005,3026277,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
7,CENTEL,2026,1,1,3387598,1752985,1634613,93.25,3387598,1992901,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
8,CK,2026,1,1,3375096,1445903,1929193,133.42,3375096,3328223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
9,CKP,2026,1,1,2890971,1344536,1546435,115.02,2890971,2781825,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
10,COM7,2026,1,1,4309060,3307162,1001898,30.29,4309060,4063532,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
11,CPALL,2026,1,1,29738684,25345841,4392843,17.33,29738684,28206100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
12,CPN,2026,1,1,19584844,16729046,2855798,17.07,19584844,18841255,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
14,DIF,2026,1,1,13891180,656288,13234892,2016.63,13891180,13855643,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
17,KGI,2026,1,1,987326,864737,122589,14.18,987326,866402,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
20,MINT,2026,1,1,9241257,7750222,1491035,19.24,9241257,9009342,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
21,MTC,2026,1,1,6975094,5867308,1107786,18.88,6975094,6723275,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
22,ONEE,2026,1,1,527725,421017,106708,25.35,527725,450472,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
25,SIS,2026,1,1,932467,697604,234863,33.67,932467,876418,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
26,SPRC,2026,1,1,9222759,2234886,6987873,312.67,9222759,2569354,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
27,SYNEX,2026,1,1,802946,627721,175225,27.91,802946,769786,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
28,TCAP,2026,1,1,8163458,6646024,1517434,22.83,8163458,7749834,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
29,TFG,2026,1,1,7451307,3166564,4284743,135.31,7451307,7440837,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
32,TOA,2026,1,1,3137161,1919604,1217557,63.43,3137161,2917013,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
33,TOP,2026,1,1,30561848,9958628,20603220,206.89,30561848,14584201,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
35,TTW,2026,1,1,3270342,2790939,479403,17.18,3270342,3266088,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
37,VIBHA,2026,1,1,1805630,698606,1107024,158.46,1805630,1694894,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [84]:
final6 = final5[colw]
final6.sort_values('name')

,name,year,quarter,kind_x,latest_amt_y_x,previous_amt_y_x,inc_amt_y_x,inc_pct_y_x,latest_amt_q_x,previous_amt_q_x,...,q_amt_c_x,y_amt_x,inc_amt_py_x,inc_pct_py_x,q_amt_p_x,inc_amt_pq_x,inc_pct_pq_x,ticker_id_x,mean_pct_x,std_pct_x
1,AMATA,2026,1,1,3697994,2482899,1215095,48.94,3697994,3148658,...,1378517,829181,549336,66.250433,829181,549336,66.250433,21,49.722716,23.010662
2,BCP,2026,1,1,6908168,2184088,4724080,216.30,6908168,2879701,...,6143762,2115295,4028467,190.444690,2115295,4028467,190.444690,52,184.269845,31.998744
3,BGRIM,2026,1,1,1742731,1556871,185860,11.94,1742731,1675487,...,721178,653934,67244,10.282995,653934,67244,10.282995,59,9.128997,3.500918
4,BKIH,2026,1,1,3634595,3014794,619801,20.56,3634595,3063951,...,1129143,558499,570644,102.174579,558499,570644,102.174579,68,60.882289,47.686806
5,BLA,2026,1,1,7384829,4317070,3067759,71.06,7384829,6968375,...,1605539,1250525,355014,28.389197,1189085,416454,35.023064,70,35.113065,26.994667
6,BPP,2026,1,1,8329005,1746321,6582684,376.95,8329005,3026277,...,5877083,574355,5302728,923.249210,574355,5302728,923.249210,74,599.667105,382.609031
7,CENTEL,2026,1,1,3387598,1752985,1634613,93.25,3387598,1992901,...,2142542,747845,1394697,186.495464,747845,1394697,186.495464,92,134.055232,61.293442
8,CK,2026,1,1,3375096,1445903,1929193,133.42,3375096,3328223,...,329116,282243,46873,16.607321,282243,46873,16.607321,106,42.011160,61.358891
9,CKP,2026,1,1,2890971,1344536,1546435,115.02,2890971,2781825,...,179611,70465,109146,154.893919,70465,109146,154.893919,107,107.181959,71.361356
10,COM7,2026,1,1,4309060,3307162,1001898,30.29,4309060,4063532,...,1226182,980654,245528,25.037169,980654,245528,25.037169,114,21.601085,10.665489
11,CPALL,2026,1,1,29738684,25345841,4392843,17.33,29738684,28206100,...,9117822,7585238,1532584,20.204824,7585238,1532584,20.204824,116,15.792412,7.039946
12,CPN,2026,1,1,19584844,16729046,2855798,17.07,19584844,18841255,...,4970796,4227207,743589,17.590551,4227207,743589,17.590551,121,14.050275,6.737987
14,DIF,2026,1,1,13891180,656288,13234892,2016.63,13891180,13855643,...,2767480,2731943,35537,1.300796,2731943,35537,1.300796,140,504.872898,1007.838187
17,KGI,2026,1,1,987326,864737,122589,14.18,987326,866402,...,318590,197666,120924,61.175923,197666,120924,61.175923,252,37.622962,27.196766
20,MINT,2026,1,1,9241257,7750222,1491035,19.24,9241257,9009342,...,648780,416865,231915,55.633119,416865,231915,55.633119,301,33.269059,26.705487
21,MTC,2026,1,1,6975094,5867308,1107786,18.88,6975094,6723275,...,1823034,1571215,251819,16.027024,1571215,251819,16.027024,315,13.671012,6.749361
22,ONEE,2026,1,1,527725,421017,106708,25.35,527725,450472,...,53720,-23533,77253,328.275188,-23533,77253,328.275188,741,174.762594,177.292683
25,SIS,2026,1,1,932467,697604,234863,33.67,932467,876418,...,258003,201954,56049,27.753350,201954,56049,27.753350,449,23.894175,11.991655
26,SPRC,2026,1,1,9222759,2234886,6987873,312.67,9222759,2569354,...,7366927,713522,6653405,932.473701,713522,6653405,932.473701,470,609.141850,373.995036
27,SYNEX,2026,1,1,802946,627721,175225,27.91,802946,769786,...,221377,188217,33160,17.617962,188217,33160,17.617962,495,16.863981,9.673916
28,TCAP,2026,1,1,8163458,6646024,1517434,22.83,8163458,7749834,...,2123240,1709616,413624,24.193971,1709616,413624,24.193971,503,19.139486,9.222099
29,TFG,2026,1,1,7451307,3166564,4284743,135.31,7451307,7440837,...,2047091,2036621,10470,0.514087,2036621,10470,0.514087,513,34.119543,67.460535
32,TOA,2026,1,1,3137161,1919604,1217557,63.43,3137161,2917013,...,953247,733099,220148,30.029778,733099,220148,30.029778,645,32.759889,23.029700
33,TOP,2026,1,1,30561848,9958628,20603220,206.89,30561848,14584201,...,19481157,3503510,15977647,456.046850,3503510,15977647,456.046850,555,307.133425,176.482644
35,TTW,2026,1,1,3270342,2790939,479403,17.18,3270342,3266088,...,672938,668684,4254,0.636175,668684,4254,0.636175,581,4.645587,8.359681
37,VIBHA,2026,1,1,1805630,698606,1107024,158.46,1805630,1694894,...,136719,25983,110736,426.186353,25983,110736,426.186353,610,254.340676,207.898299

In [86]:
rcds = final6.values.tolist()
len(rcds)

26

In [88]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
print(sql)
lt_profits = pd.read_sql(sql, conlt)
lt_profits.head().style.format(format_dict)

SELECT *
FROM profits
WHERE year = 2026 AND quarter = 1
ORDER BY name

In [90]:
# 1. First replace inf in the DataFrame
lt_profits['inc_pct_py'] = lt_profits['inc_pct_py'].replace([np.inf, -np.inf], 999.99)
lt_profits['mean_pct'] = lt_profits['mean_pct'].replace([np.inf, -np.inf], 999.99)

# Now when you print rcds, you'll see 999.99 instead of inf
lt_profits.style.format(format_dict)

In [92]:
# Define SQL statement using named placeholders
sql = text("""
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)
""")

# Convert list data to dictionaries for named parameters
columns = [
    "name", "year", "quarter", "kind",
    "latest_amt_y", "previous_amt_y", "inc_amt_y", "inc_pct_y",
    "latest_amt_q", "previous_amt_q", "inc_amt_q", "inc_pct_q",
    "q_amt_c", "y_amt", "inc_amt_py", "inc_pct_py",
    "q_amt_p", "inc_amt_pq", "inc_pct_pq",
    "ticker_id", "mean_pct", "std_pct"
]

records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]

# Check for empty records before attempting insertion
if not rcds:
    print("No records to insert - skipping database operation")
    # In notebook/script context, just proceed to next cell instead of 'return'
else:
    try:
        # Convert list data to dictionaries for named parameters
#        records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]
        conlt.execute(sql, records_dicts)
        conlt.commit()
        print(f"Successfully inserted {len(records_dicts)} records")
    except Exception as e:
        conlt.rollback()
        print("Insert failed:", e)
    finally:
        conlt.commit()

Successfully inserted 26 records

In [94]:
# Replace 'inf' with 999.99 in specific columns
lt_profits['inc_pct_py'] = lt_profits['inc_pct_py'].replace([np.inf, -np.inf], 999.99)
lt_profits['mean_pct'] = lt_profits['mean_pct'].replace([np.inf, -np.inf], 999.99)

In [96]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
profits = pd.read_sql(sql, conlt)
profits.head().style.format(format_dict)

### End of Create Data

In [99]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y:%m:%d %H:%M:%S")
print(formatted_time)

2026:05:17 14:56:50