In [1]:
import numpy as np
import pandas as pd
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

year = 2026
quarter = 1
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-05-11 22:28:38

### Insert Profits from PortLt to PortMy

In [4]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

lt_profits = pd.read_sql(sql, conlt)
lt_profits

SELECT *
FROM profits
WHERE  year = 2026 AND quarter = 1

,id,name,year,quarter,kind,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,latest_amt_q,...,q_amt_c,y_amt,inc_amt_py,inc_pct_py,q_amt_p,inc_amt_pq,inc_pct_pq,ticker_id,mean_pct,std_pct
0,2860,ADVANC,2026,1,1,50797881,35075357,15722524,44.82,50797881,...,13495505,10583526,2911979,27.514261,10583526,2911979,27.514261,6,26.482131,15.860380
1,2861,DELTA,2026,1,1,28407374,18938580,9468794,50.00,28407374,...,9081176,5488126,3593050,65.469525,5488126,3593050,65.469525,138,48.854762,24.048815
2,2862,GPSC,2026,1,1,6978315,4062379,2915936,71.78,6978315,...,1719348,1140036,579312,50.815237,1140036,579312,50.815237,197,45.615119,26.303938
3,2863,GUNKUL,2026,1,1,1857507,1660831,196676,11.84,1857507,...,455763,366965,88798,24.197948,366965,88798,24.197948,202,16.313974,9.519881
4,2864,KKP,2026,1,1,6806788,4985068,1821720,36.54,6806788,...,1955494,1061619,893875,84.199228,1061619,893875,84.199228,255,55.014614,34.815585
5,2865,KTB,2026,1,1,48952081,43855657,5096424,11.62,48952081,...,12437176,11713698,723478,6.176342,11713698,723478,6.176342,258,6.368171,4.137406
6,2866,SCC,2026,1,1,19199135,6341638,12857497,202.75,19199135,...,6222963,1098848,5124115,466.316997,1098848,5124115,466.316997,427,292.948499,211.393033
7,2867,SCGP,2026,1,1,4735791,3699083,1036708,28.03,4735791,...,1566168,899872,666296,74.043420,899872,666296,74.043420,713,48.121710,30.307963
8,2868,THANI,2026,1,1,1234581,800211,434370,54.28,1234581,...,340348,253604,86744,34.204508,253604,86744,34.204508,522,32.562254,19.167396
9,2869,TIDLOR,2026,1,1,5248767,4230480,1018287,24.07,5248767,...,1613744,1197815,415929,34.723977,-12882,1626626,12627.123118,751,3182.706774,6296.283312
10,2870,TPIPL,2026,1,1,2107706,1442498,665208,46.12,2107706,...,832438,723236,109202,15.099082,723236,109202,15.099082,559,20.444541,17.709823
11,2871,TVO,2026,1,1,2364101,2103105,260996,12.41,2364101,...,708925,533615,175310,32.853274,533615,175310,32.853274,585,21.531637,13.195932
12,2872,WHART,2026,1,1,2358805,1920946,437859,22.79,2358805,...,674906,665907,8999,1.351390,665907,8999,1.351390,622,6.468195,10.890834

In [6]:
lt_profits = lt_profits.drop(columns=['id'])
lt_profits.shape

(13, 22)

In [8]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

my_profits = pd.read_sql(sql, conmy)
my_profits

SELECT *
FROM profits
WHERE  year = 2026 AND quarter = 1

Empty DataFrame
Columns: [id, name, year, quarter, kind, latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y, latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q, q_amt_c, y_amt, inc_amt_py, inc_pct_py, q_amt_p, inc_amt_pq, inc_pct_pq, ticker_id, mean_pct, std_pct]
Index: []

[0 rows x 23 columns]

In [10]:
sqlDel = text("DELETE FROM profits WHERE year = :year AND quarter = :quarter")
print(sqlDel)  # Shows the uncompiled SQL with placeholders

# Execute and get the result
result = conmy.execute(sqlDel, {"year": year, "quarter": quarter})
rows_deleted = result.rowcount  # Get the number of rows deleted
conmy.commit()  # Commit the transaction

print(f"Number of rows deleted: {rows_deleted}")

DELETE FROM profits WHERE year = :year AND quarter = :quarter
Number of rows deleted: 0

In [12]:
# Define SQL statement using named placeholders
sqlIns = text("""
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)
""")
print(sqlIns)

INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)

In [14]:
rcds = lt_profits.values.tolist()
print(f"Number of rows to insert: {len(rcds)}")

Number of rows to insert: 13

In [16]:
# Convert list data to dictionaries for named parameters
columns = [
    "name", "year", "quarter", "kind",
    "latest_amt_y", "previous_amt_y", "inc_amt_y", "inc_pct_y",
    "latest_amt_q", "previous_amt_q", "inc_amt_q", "inc_pct_q",
    "q_amt_c", "y_amt", "inc_amt_py", "inc_pct_py",
    "q_amt_p", "inc_amt_pq", "inc_pct_pq",
    "ticker_id", "mean_pct", "std_pct"
]

records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]

# Check for empty records before attempting insertion
if not rcds:
    print("No records to insert - skipping database operation")
    # In notebook/script context, just proceed to next cell instead of 'return'
else:
    try:
        result = conmy.execute(sqlIns, records_dicts)  # Bulk insert using named parameters
        rows_insert = result.rowcount
        print(f"{rows_insert} rows inserted successfully!")
    except Exception as e:
        print("Error inserting data:", e)
    finally:
        conmy.commit()

13 rows inserted successfully!

In [18]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

my_profits = pd.read_sql(sql, conmy)
my_profits

SELECT *
FROM profits
WHERE  year = 2026 AND quarter = 1

,id,name,year,quarter,kind,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,latest_amt_q,...,q_amt_c,y_amt,inc_amt_py,inc_pct_py,q_amt_p,inc_amt_pq,inc_pct_pq,ticker_id,mean_pct,std_pct
0,369,ADVANC,2026,1,1,50797881,35075357,15722524,44.82,50797881,...,13495505,10583526,2911979,27.514261,10583526,2911979,27.514261,6,26.482131,15.860380
1,370,DELTA,2026,1,1,28407374,18938580,9468794,50.00,28407374,...,9081176,5488126,3593050,65.469525,5488126,3593050,65.469525,138,48.854762,24.048815
2,371,GPSC,2026,1,1,6978315,4062379,2915936,71.78,6978315,...,1719348,1140036,579312,50.815237,1140036,579312,50.815237,197,45.615119,26.303938
3,372,GUNKUL,2026,1,1,1857507,1660831,196676,11.84,1857507,...,455763,366965,88798,24.197948,366965,88798,24.197948,202,16.313974,9.519881
4,373,KKP,2026,1,1,6806788,4985068,1821720,36.54,6806788,...,1955494,1061619,893875,84.199228,1061619,893875,84.199228,255,55.014614,34.815585
5,374,KTB,2026,1,1,48952081,43855657,5096424,11.62,48952081,...,12437176,11713698,723478,6.176342,11713698,723478,6.176342,258,6.368171,4.137406
6,375,SCC,2026,1,1,19199135,6341638,12857497,202.75,19199135,...,6222963,1098848,5124115,466.316997,1098848,5124115,466.316997,427,292.948499,211.393033
7,376,SCGP,2026,1,1,4735791,3699083,1036708,28.03,4735791,...,1566168,899872,666296,74.043420,899872,666296,74.043420,713,48.121710,30.307963
8,377,THANI,2026,1,1,1234581,800211,434370,54.28,1234581,...,340348,253604,86744,34.204508,253604,86744,34.204508,522,32.562254,19.167396
9,378,TIDLOR,2026,1,1,5248767,4230480,1018287,24.07,5248767,...,1613744,1197815,415929,34.723977,-12882,1626626,12627.123118,751,3182.706774,6296.283312
10,379,TPIPL,2026,1,1,2107706,1442498,665208,46.12,2107706,...,832438,723236,109202,15.099082,723236,109202,15.099082,559,20.444541,17.709823
11,380,TVO,2026,1,1,2364101,2103105,260996,12.41,2364101,...,708925,533615,175310,32.853274,533615,175310,32.853274,585,21.531637,13.195932
12,381,WHART,2026,1,1,2358805,1920946,437859,22.79,2358805,...,674906,665907,8999,1.351390,665907,8999,1.351390,622,6.468195,10.890834

### PortPg Process

In [21]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

pg_profits = pd.read_sql(sql, conpg)
pg_profits

SELECT *
FROM profits
WHERE  year = 2026 AND quarter = 1

Empty DataFrame
Columns: [id, name, year, quarter, kind, latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y, latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q, q_amt_c, y_amt, inc_amt_py, inc_pct_py, q_amt_p, inc_amt_pq, inc_pct_pq, mean_pct, std_pct, publish_date, ticker_id]
Index: []

[0 rows x 24 columns]

In [23]:
sqlDel = text("DELETE FROM profits WHERE year = :year AND quarter = :quarter")
print(sqlDel)  # Shows the uncompiled SQL with placeholders

# Execute and get the result
result = conpg.execute(sqlDel, {"year": year, "quarter": quarter})
rows_deleted = result.rowcount  # Get the number of rows deleted

print(f"Number of rows deleted: {rows_deleted}")

DELETE FROM profits WHERE year = :year AND quarter = :quarter
Number of rows deleted: 0

In [25]:
sql = 'SELECT name, id FROM tickers'
pg_tickers = pd.read_sql(sql, conpg)
pg_tickers.shape

(390, 2)

In [27]:
df_merge = pd.merge(my_profits, pg_tickers, on="name", how="inner")
df_merge

,id_x,name,year,quarter,kind,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,latest_amt_q,...,y_amt,inc_amt_py,inc_pct_py,q_amt_p,inc_amt_pq,inc_pct_pq,ticker_id,mean_pct,std_pct,id_y
0,369,ADVANC,2026,1,1,50797881,35075357,15722524,44.82,50797881,...,10583526,2911979,27.514261,10583526,2911979,27.514261,6,26.482131,15.860380,8
1,370,DELTA,2026,1,1,28407374,18938580,9468794,50.00,28407374,...,5488126,3593050,65.469525,5488126,3593050,65.469525,138,48.854762,24.048815,144
2,371,GPSC,2026,1,1,6978315,4062379,2915936,71.78,6978315,...,1140036,579312,50.815237,1140036,579312,50.815237,197,45.615119,26.303938,202
3,372,GUNKUL,2026,1,1,1857507,1660831,196676,11.84,1857507,...,366965,88798,24.197948,366965,88798,24.197948,202,16.313974,9.519881,208
4,373,KKP,2026,1,1,6806788,4985068,1821720,36.54,6806788,...,1061619,893875,84.199228,1061619,893875,84.199228,255,55.014614,34.815585,262
5,374,KTB,2026,1,1,48952081,43855657,5096424,11.62,48952081,...,11713698,723478,6.176342,11713698,723478,6.176342,258,6.368171,4.137406,265
6,375,SCC,2026,1,1,19199135,6341638,12857497,202.75,19199135,...,1098848,5124115,466.316997,1098848,5124115,466.316997,427,292.948499,211.393033,433
7,376,SCGP,2026,1,1,4735791,3699083,1036708,28.03,4735791,...,899872,666296,74.043420,899872,666296,74.043420,713,48.121710,30.307963,684
8,377,THANI,2026,1,1,1234581,800211,434370,54.28,1234581,...,253604,86744,34.204508,253604,86744,34.204508,522,32.562254,19.167396,528
9,378,TIDLOR,2026,1,1,5248767,4230480,1018287,24.07,5248767,...,1197815,415929,34.723977,-12882,1626626,12627.123118,751,3182.706774,6296.283312,696
10,379,TPIPL,2026,1,1,2107706,1442498,665208,46.12,2107706,...,723236,109202,15.099082,723236,109202,15.099082,559,20.444541,17.709823,568
11,380,TVO,2026,1,1,2364101,2103105,260996,12.41,2364101,...,533615,175310,32.853274,533615,175310,32.853274,585,21.531637,13.195932,594
12,381,WHART,2026,1,1,2358805,1920946,437859,22.79,2358805,...,665907,8999,1.351390,665907,8999,1.351390,622,6.468195,10.890834,630

In [29]:
df_merge = df_merge.drop(columns=['ticker_id']).rename(columns={'id_y': 'ticker_id'})

In [31]:
columns = 'name ticker_id'.split()
df_merge[columns]

      name  ticker_id
0   ADVANC          8
1    DELTA        144
2     GPSC        202
3   GUNKUL        208
4      KKP        262
5      KTB        265
6      SCC        433
7     SCGP        684
8    THANI        528
9   TIDLOR        696
10   TPIPL        568
11     TVO        594
12   WHART        630

In [33]:
colv = 'name year quarter kind latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt \
        inc_amt_py inc_pct_py q_amt_p inc_amt_pq inc_pct_pq \
        ticker_id mean_pct std_pct'.split()
format_dict = {
    'q_amt': '{:,}',
    'y_amt': '{:,}',
    'yoy_gain': '{:,}',
    'q_amt_c': '{:,}',
    'q_amt_p': '{:,}',
    'aq_amt': '{:,}',
    'ay_amt': '{:,}',
    'acc_gain': '{:,}',
    'latest_amt': '{:,}',
    'previous_amt': '{:,}',
    'inc_amt': '{:,}',
    'inc_amt_pq': '{:,}',
    'inc_amt_py': '{:,}',    
    'latest_amt_q': '{:,}',
    'previous_amt_q': '{:,}',
    'inc_amt_q': '{:,}',
    'latest_amt_y': '{:,}',
    'previous_amt_y': '{:,}',
    'inc_amt_y': '{:,}',
    'kind_x': '{:,}',
    'inc_pct': '{:.2f}%',
    'inc_pct_q': '{:.2f}%',
    'inc_pct_y': '{:.2f}%',
    'inc_pct_pq': '{:.2f}%',
    'inc_pct_py': '{:.2f}%',   
    'mean_pct': '{:.2f}%',
    'std_pct': '{:.2f}%',      
}

In [35]:
final = df_merge[colv].copy()
final.sort_values(by=['ticker_id'],ascending=True).style.format(format_dict)

In [37]:
# Define SQL statement using named placeholders
sqlInsPg = text("""
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)
""")

# Convert list data to dictionaries for named parameters
columns = [
    "name", "year", "quarter", "kind",
    "latest_amt_y", "previous_amt_y", "inc_amt_y", "inc_pct_y",
    "latest_amt_q", "previous_amt_q", "inc_amt_q", "inc_pct_q",
    "q_amt_c", "y_amt", "inc_amt_py", "inc_pct_py",
    "q_amt_p", "inc_amt_pq", "inc_pct_pq",
    "ticker_id", "mean_pct", "std_pct"
]
print(sqlInsPg)

INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)

In [39]:
rcds = final.values.tolist()
print(f"Number of rows to insert: {len(rcds)}")

Number of rows to insert: 13

In [41]:
records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]
#print(records_dicts)

# Check for empty records before attempting insertion
if not rcds:
    print("No records to insert - skipping database operation")
    # In notebook/script context, just proceed to next cell instead of 'return'
else:
    try:
        result = conpg.execute(sqlInsPg, records_dicts)  # Bulk insert using named parameters
        rows_insert = result.rowcount
        print(f"{rows_insert} rows inserted successfully!")
    except Exception as e:
        print("Error inserting data:", e)
    finally:
        conpg.commit()

13 rows inserted successfully!

In [43]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

pg_profits = pd.read_sql(sql, conpg)
pg_profits

SELECT *
FROM profits
WHERE  year = 2026 AND quarter = 1

,id,name,year,quarter,kind,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,latest_amt_q,...,y_amt,inc_amt_py,inc_pct_py,q_amt_p,inc_amt_pq,inc_pct_pq,mean_pct,std_pct,publish_date,ticker_id
0,68022,ADVANC,2026,1,1,50797881,35075357,15722524,44.82,50797881,...,10583526,2911979,27.514261,10583526,2911979,27.514261,26.482131,15.860380,None,8
1,68023,DELTA,2026,1,1,28407374,18938580,9468794,50.00,28407374,...,5488126,3593050,65.469525,5488126,3593050,65.469525,48.854762,24.048815,None,144
2,68024,GPSC,2026,1,1,6978315,4062379,2915936,71.78,6978315,...,1140036,579312,50.815237,1140036,579312,50.815237,45.615119,26.303938,None,202
3,68025,GUNKUL,2026,1,1,1857507,1660831,196676,11.84,1857507,...,366965,88798,24.197948,366965,88798,24.197948,16.313974,9.519881,None,208
4,68026,KKP,2026,1,1,6806788,4985068,1821720,36.54,6806788,...,1061619,893875,84.199228,1061619,893875,84.199228,55.014614,34.815585,None,262
5,68027,KTB,2026,1,1,48952081,43855657,5096424,11.62,48952081,...,11713698,723478,6.176342,11713698,723478,6.176342,6.368171,4.137406,None,265
6,68028,SCC,2026,1,1,19199135,6341638,12857497,202.75,19199135,...,1098848,5124115,466.316997,1098848,5124115,466.316997,292.948499,211.393033,None,433
7,68029,SCGP,2026,1,1,4735791,3699083,1036708,28.03,4735791,...,899872,666296,74.043420,899872,666296,74.043420,48.121710,30.307963,None,684
8,68030,THANI,2026,1,1,1234581,800211,434370,54.28,1234581,...,253604,86744,34.204508,253604,86744,34.204508,32.562254,19.167396,None,528
9,68031,TIDLOR,2026,1,1,5248767,4230480,1018287,24.07,5248767,...,1197815,415929,34.723977,-12882,1626626,12627.123118,3182.706774,6296.283312,None,696
10,68032,TPIPL,2026,1,1,2107706,1442498,665208,46.12,2107706,...,723236,109202,15.099082,723236,109202,15.099082,20.444541,17.709823,None,568
11,68033,TVO,2026,1,1,2364101,2103105,260996,12.41,2364101,...,533615,175310,32.853274,533615,175310,32.853274,21.531637,13.195932,None,594
12,68034,WHART,2026,1,1,2358805,1920946,437859,22.79,2358805,...,665907,8999,1.351390,665907,8999,1.351390,6.468195,10.890834,None,630

In [45]:
stock_list = pg_profits['name'].unique().tolist()
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

ADVANC','DELTA','GPSC','GUNKUL','KKP','KTB','SCC','SCGP','THANI','TIDLOR','TPIPL','TVO','WHART

In [47]:
sql = f"""SELECT name, year, quarter, publish_date FROM epss WHERE year = {year} AND quarter = {quarter} AND name IN ('{stock_list_str}')"""
print(sql)
df_epss_profits = pd.read_sql(sql, conlt)
df_epss_profits

SELECT name, year, quarter, publish_date FROM epss WHERE year = 2026 AND quarter = 1 AND name IN ('ADVANC','DELTA','GPSC','GUNKUL','KKP','KTB','SCC','SCGP','THANI','TIDLOR','TPIPL','TVO','WHART')

      name  year  quarter publish_date
0   ADVANC  2026        1   2026-05-07
1    DELTA  2026        1   2026-04-27
2     GPSC  2026        1   2026-05-07
3   GUNKUL  2026        1   2026-05-08
4      KKP  2026        1   2026-04-20
5      KTB  2026        1   2026-04-21
6      SCC  2026        1   2026-04-29
7     SCGP  2026        1   2026-04-28
8    THANI  2026        1   2026-05-08
9   TIDLOR  2026        1   2026-05-07
10   TPIPL  2026        1   2026-05-08
11     TVO  2026        1   2026-05-08
12   WHART  2026        1   2026-05-07

In [49]:
sql = f"""
SELECT name, year, quarter, publish_date 
FROM epss 
WHERE year = {year} AND quarter = {quarter} AND name IN ('{stock_list_str}')
""" 
print(sql)
df_epss_profits = pd.read_sql(sql, conlt)

if not df_epss_profits.empty:
    update_sql = text("""
        UPDATE profits 
        SET publish_date = :publish_date
        WHERE name = :name AND year = :year AND quarter = :quarter
    """)
    
    # Execute update for each row in df_epss_profits
    for _, row in df_epss_profits.iterrows():
        conpg.execute(update_sql, {
            'publish_date': row['publish_date'],
            'name': row['name'],
            'year': row['year'],
            'quarter': row['quarter']
        })

SELECT name, year, quarter, publish_date
FROM epss
WHERE year = 2026 AND quarter = 1 AND name IN ('ADVANC','DELTA','GPSC','GUNKUL','KKP','KTB','SCC','SCGP','THANI','TIDLOR','TPIPL','TVO','WHART')

In [51]:
#After update publish_date from epss to profits
sql = """
SELECT name, year, quarter, publish_date 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

pg_profits = pd.read_sql(sql, conpg)
pg_profits

SELECT name, year, quarter, publish_date
FROM profits
WHERE  year = 2026 AND quarter = 1

      name  year  quarter publish_date
0   ADVANC  2026        1   2026-05-07
1    DELTA  2026        1   2026-04-27
2     GPSC  2026        1   2026-05-07
3   GUNKUL  2026        1   2026-05-08
4      KKP  2026        1   2026-04-20
5      KTB  2026        1   2026-04-21
6      SCC  2026        1   2026-04-29
7     SCGP  2026        1   2026-04-28
8    THANI  2026        1   2026-05-08
9   TIDLOR  2026        1   2026-05-07
10   TPIPL  2026        1   2026-05-08
11     TVO  2026        1   2026-05-08
12   WHART  2026        1   2026-05-07