### Restart and Run All Cells

In [2]:
import pandas as pd
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()

engine = create_engine("postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()

current_time = datetime.now()
print(current_time)

2026-02-15 10:17:05.385705

In [4]:
format_dict = {
    "q_amt": "{:,}",
    "y_amt": "{:,}",
    "yoy_gain": "{:,}",
    "q_amt_c": "{:,}",
    "q_amt_p": "{:,}",
    "aq_amt": "{:,}",
    "ay_amt": "{:,}",
    "acc_gain": "{:,}",
    "latest_amt": "{:,}",
    "previous_amt": "{:,}",
    "inc_amt": "{:,}",
    "inc_amt_pq": "{:,}",
    "inc_amt_py": "{:,}",    
    "latest_amt_q": "{:,}",
    "previous_amt_q": "{:,}",
    "inc_amt_q": "{:,}",
    "latest_amt_y": "{:,}",
    "previous_amt_y": "{:,}",
    "inc_amt_y": "{:,}",
    "kind_x": "{:,}",
    "inc_pct": "{:.2f}%",
    "inc_pct_q": "{:.2f}%",
    "inc_pct_y": "{:.2f}%",
    "inc_pct_pq": "{:.2f}%",
    "inc_pct_py": "{:.2f}%",   
    "mean_pct": "{:.2f}%",
    "std_pct": "{:.2f}%",      
}

In [6]:
sql = '''
SELECT name, id AS ticker_id
FROM tickers'''

df_tickers = pd.read_sql(sql, conpg)
df_tickers.shape

(396, 2)

In [8]:
# Delete old epss in PortPG
sql = text("DELETE FROM epss")
rp = conpg.execute(sql)
rp.rowcount

10173

In [10]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt,q_eps,y_eps,aq_eps,ay_eps,publish_date
FROM epss 
ORDER BY year, quarter, name"""

df_epss = pd.read_sql(sql, conlt)
df_epss.shape

(10173, 12)

In [12]:
df_merge = pd.merge(df_epss, df_tickers, on="name", how="outer", indicator=True)
df_merge.shape

(10343, 14)

In [14]:
df_left = df_merge[df_merge["_merge"] == "left_only"]
df_left["name"].unique()
df_left

Empty DataFrame
Columns: [name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, q_eps, y_eps, aq_eps, ay_eps, publish_date, ticker_id, _merge]
Index: []

In [16]:
cols = 'name year quarter q_amt y_amt aq_amt ay_amt q_eps y_eps aq_eps ay_eps ticker_id publish_date'.split()
cols

['name',
 'year',
 'quarter',
 'q_amt',
 'y_amt',
 'aq_amt',
 'ay_amt',
 'q_eps',
 'y_eps',
 'aq_eps',
 'ay_eps',
 'ticker_id',
 'publish_date']

In [18]:
# epss from PortLT that will be copied to PortPG
df_ins = df_merge[df_merge["_merge"] == "both"]
df_epss_cols    = df_ins[cols]
df_epss_cols.shape

(10173, 13)

In [20]:
# Convert DataFrame to list of records
rcds = df_epss_cols.values.tolist()

# Define column names in the same order as values
columns = ['name', 'year', 'quarter', 'q_amt', 'y_amt', 'aq_amt', 'ay_amt', 
           'q_eps', 'y_eps', 'aq_eps', 'ay_eps', 'ticker_id', 'publish_date']

# SQL insert statement with named parameters
sql = text("""
    INSERT INTO epss 
    (name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, 
     q_eps, y_eps, aq_eps, ay_eps, ticker_id, publish_date)
    VALUES (:name, :year, :quarter, :q_amt, :y_amt, :aq_amt, :ay_amt,
            :q_eps, :y_eps, :aq_eps, :ay_eps, :ticker_id, :publish_date)
""")

try:
    # Execute inserts
    for rcd in rcds:
        # Convert list to dictionary
        params = dict(zip(columns, rcd))
        conpg.execute(sql, params)
    
    # Commit the transaction
    conpg.commit()
except Exception as e:
    # Rollback on error
    conpg.rollback()
    raise e

### Start of Yearly Profit Section

In [22]:
sql = text("DELETE FROM yr_profits")
rp = conpg.execute(sql)
rp.rowcount

7628

In [23]:
sql = """
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM yr_profits 
ORDER BY year desc, quarter desc, name"""
df_yr_profits = pd.read_sql(sql, conlt)
df_yr_profits.shape

(7632, 7)

In [27]:
# Extract numeric portion from Q9 format
df_yr_profits["qtr_int"] = df_yr_profits["quarter"].str[1:]
df_yr_profits.shape

(7632, 8)

In [29]:
df_merge = pd.merge(df_yr_profits, df_tickers, on="name", how="outer", indicator=True)
df_merge.shape

(7802, 10)

In [31]:
df_left = df_merge[df_merge["_merge"] == "left_only"]
df_left

Empty DataFrame
Columns: [name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct, qtr_int, ticker_id, _merge]
Index: []

In [33]:
# quarter in numeric format 1..4
colt = 'name year qtr_int latest_amt previous_amt inc_amt inc_pct ticker_id'.split()
colt

['name',
 'year',
 'qtr_int',
 'latest_amt',
 'previous_amt',
 'inc_amt',
 'inc_pct',
 'ticker_id']

In [35]:
df_ins = df_merge[df_merge["_merge"] == "both"]
df_yr_profits_colt = df_ins[colt]
df_yr_profits_colt.shape

(7632, 8)

In [37]:
# Column names (ensure they match the actual column names in your table)
columns = ["name", "year", "quarter", "latest_amt", "previous_amt", "inc_amt", "inc_pct", "ticker_id"]

# Convert list of lists to list of dictionaries
rcds = [dict(zip(columns, row)) for row in df_yr_profits_colt.values.tolist()]

query = text("""
    INSERT INTO yr_profits (name, year, quarter, 
    latest_amt, previous_amt, inc_amt, inc_pct, ticker_id) 
    VALUES (:name, :year, :quarter, :latest_amt, :previous_amt, :inc_amt, :inc_pct, :ticker_id)
""")

conpg.execute(query, rcds)  # Bulk insert with named placeholders
conpg.commit()  # Commit transaction

### Start of Profits section

In [40]:
sql = text('DELETE FROM profits')
rp = conpg.execute(sql)
rp.rowcount

20

In [42]:
sql = '''
SELECT * FROM profits
ORDER BY name, year DESC, quarter DESC'''
lt_profits   = pd.read_sql(sql, conlt)
lt_profits.shape

(25, 23)

In [44]:
sql = """
SELECT name, year, quarter, publish_date
FROM epss"""
df_epss = pd.read_sql(sql, conlt)
df_epss.shape

(10173, 4)

In [46]:
df_merge = pd.merge(
    lt_profits, df_epss, on=["name", "year", "quarter"], how="outer", indicator=True
)
df_merge.shape

(10173, 25)

In [48]:
prf_eps = df_merge[df_merge["_merge"] == "both"]
prf_eps.shape

(25, 25)

In [50]:
columns = ["id", "ticker_id", "_merge"]
prf_eps_2 = prf_eps.drop(columns, axis=1)
prf_eps_2.shape

(25, 22)

In [52]:
df_merge = pd.merge(prf_eps_2, df_tickers, on="name", how="inner")
df_merge.shape

(25, 23)

In [54]:
df_merge = df_merge.query("name != 'GULF'")
df_merge.shape

(25, 23)

In [56]:
rcds = df_merge.values.tolist()
print(f"Number of records to insert: {len(rcds)}")

Number of records to insert: 25

In [58]:
# SQL query with parameter placeholders
sql = text("""
INSERT INTO profits (
    name, year, quarter, kind,
    latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
    latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
    q_amt_c, y_amt, inc_amt_py, inc_pct_py,
    q_amt_p, inc_amt_pq, inc_pct_pq,
    mean_pct, std_pct, publish_date, ticker_id
)
VALUES (
    :name, :year, :quarter, :kind,
    :latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
    :latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
    :q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
    :q_amt_p, :inc_amt_pq, :inc_pct_pq,
    :mean_pct, :std_pct, :publish_date, :ticker_id
)
""")
print(sql)

INSERT INTO profits (
    name, year, quarter, kind,
    latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
    latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
    q_amt_c, y_amt, inc_amt_py, inc_pct_py,
    q_amt_p, inc_amt_pq, inc_pct_pq,
    mean_pct, std_pct, publish_date, ticker_id
)
VALUES (
    :name, :year, :quarter, :kind,
    :latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
    :latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
    :q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
    :q_amt_p, :inc_amt_pq, :inc_pct_pq,
    :mean_pct, :std_pct, :publish_date, :ticker_id
)

In [60]:
# Execute the query for each record
for rcd in rcds:
    # Convert tuple to dictionary
    params = {
        'name': rcd[0],
        'year': rcd[1],
        'quarter': rcd[2],
        'kind': rcd[3],
        'latest_amt_y': rcd[4],
        'previous_amt_y': rcd[5],
        'inc_amt_y': rcd[6],
        'inc_pct_y': rcd[7],
        'latest_amt_q': rcd[8],
        'previous_amt_q': rcd[9],
        'inc_amt_q': rcd[10],
        'inc_pct_q': rcd[11],
        'q_amt_c': rcd[12],
        'y_amt': rcd[13],
        'inc_amt_py': rcd[14],
        'inc_pct_py': rcd[15],
        'q_amt_p': rcd[16],
        'inc_amt_pq': rcd[17],
        'inc_pct_pq': rcd[18],
        'mean_pct': rcd[19],
        'std_pct': rcd[20],
        'publish_date': rcd[21],
        'ticker_id': rcd[22]
    }

    # Execute the query
    conpg.execute(sql, params)
print("Records inserted successfully!")

Records inserted successfully!

In [62]:
sql = '''
SELECT * FROM profits
ORDER BY name'''
pg_profits   = pd.read_sql(sql, conpg)
pg_profits.style.format(format_dict)

### End of Profits section

In [65]:
conpg.commit()
conpg.close()

In [67]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-02-15 10:17:39