In [1]:
import os
import pandas as pd
from sqlalchemy import create_engine, text
from glob import glob

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()

engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

data_path = "../data/"
irreg_path = "../data/irreg/"

In [2]:
year = 2026
quarter = 1
year, quarter

(2026, 1)

In [3]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")
#C:\Users\PC1\OneDrive\A5\Excel
xsl_path = os.path.join(base_path, "Excel")

In [4]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path (dat_path): {dat_path}") 
print(f"Excel path (xsl_path): {xsl_path}") 
print(f"Google Drive path (god_path): {god_path}")
print(f"iCloudDrive path (icd_path): {icd_path}") 
print(f"Obsidian path (osd_path): {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Quarterly
Base path: C:\Users\PC1\OneDrive\A4
Data path (dat_path): C:\Users\PC1\OneDrive\A4\Data
Excel path (xsl_path): C:\Users\PC1\OneDrive\A4\Excel
Google Drive path (god_path): C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path (icd_path): C:\Users\PC1\iCloudDrive\Data
Obsidian path (osd_path): C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

### Begin of Irregular quarter

### Irregular Quarter Plus 1

In [7]:
file_name = 'P1-Stocks.csv'
input_file = irreg_path + file_name
# Read with header=0 (default) to use first row as column names
data_ins = pd.read_csv(input_file)
# Now data_ins will have the actual column name (probably 'name' or something else)
data_ins

      name
0      AOT
1     CITY
2      FPT
3   GVREIT
4      IRC
5     KTIS
6       MC
7    OISHI
8     PICO
9      SSC
10   TFFIF
11      UV

In [8]:
stock_list = data_ins['name'].unique().tolist()
stock_list_str = "','".join(stock_list)
print(stock_list_str)

AOT','CITY','FPT','GVREIT','IRC','KTIS','MC','OISHI','PICO','SSC','TFFIF','UV

In [70]:
sql = f'''
SELECT name, COUNT(*) FROM epss 
WHERE name NOT IN ('{stock_list_str}')
AND ((year = {year} AND quarter <= {quarter} + 1)
OR (year = {year} - 1 AND quarter > {quarter} + 1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name'''
print(sql)

SELECT name, COUNT(*) FROM epss
WHERE name NOT IN ('AEONTS','BCT','BLAND','BTS','BTSGIF','EPG','IMPACT','KYE','LHK','LPF','MACO','PTL','SFP','STANLY','TIF1','TLGF','TMW','TR','TSTH','VGI','AOT','CITY','FPT','GVREIT','IRC','KTIS','MC','OISHI','PICO','SSC','TFFIF','UV')
AND ((year = 2026 AND quarter <= 1 + 1)
OR (year = 2026 - 1 AND quarter > 1 + 1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name

In [72]:
df = pd.read_sql(sql, conlt)
df

       name  COUNT(*)
0     3BBIF         3
1       ACE         3
2    ADVANC         3
3        AH         3
4       AIE         3
..      ...       ...
192   WHAIR         3
193   WHART         3
194   WHAUP         3
195    WICE         3
196    WORK         3

[197 rows x 2 columns]

### Irregular Quarter Minus 1

In [12]:
file_name   = 'M1-Stocks.csv'
input_file = irreg_path + file_name
# Read with header=0 (default) to use first row as column names
data_ins = pd.read_csv(input_file)
# Now data_ins will have the actual column name (probably 'name' or something else)
data_ins

      name
0   AEONTS
1      BCT
2    BLAND
3      BTS
4   BTSGIF
5      EPG
6   IMPACT
7      KYE
8      LHK
9      LPF
10    MACO
11     PTL
12     SFP
13  STANLY
14    TIF1
15    TLGF
16     TMW
17      TR
18    TSTH
19     VGI

In [13]:
stock_list = data_ins['name'].unique().tolist()
stock_list_str = "','".join(stock_list)
print(stock_list_str)

AEONTS','BCT','BLAND','BTS','BTSGIF','EPG','IMPACT','KYE','LHK','LPF','MACO','PTL','SFP','STANLY','TIF1','TLGF','TMW','TR','TSTH','VGI

In [14]:
sql = f'''
SELECT name, COUNT(*) FROM epss 
WHERE name in ('{stock_list_str}')
AND ((year = {year} AND quarter <= {quarter} - 1)
OR (year = {year} - 1 AND quarter > {quarter} - 1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name'''
print(sql)

SELECT name, COUNT(*) FROM epss
WHERE name in ('AEONTS','BCT','BLAND','BTS','BTSGIF','EPG','IMPACT','KYE','LHK','LPF','MACO','PTL','SFP','STANLY','TIF1','TLGF','TMW','TR','TSTH','VGI')
AND ((year = 2026 AND quarter <= 1 - 1)
OR (year = 2026 - 1 AND quarter > 1 - 1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name

In [15]:
df = pd.read_sql(sql, conlt)
df

      name  COUNT(*)
0      BCT         3
1    BLAND         3
2      BTS         3
3   BTSGIF         3
4      EPG         3
5   IMPACT         3
6      KYE         3
7      LHK         3
8      PTL         3
9   STANLY         3
10     TMW         3
11      TR         3
12    TSTH         3
13     VGI         3

In [16]:
df.shape

(14, 2)

### End of Irregular quarter

### Normal Quarter Stocks

In [19]:
irreg_files = sorted(glob('../data/irreg/*.csv'))
irreg_files

['../data/irreg\\M1-Stocks.csv', '../data/irreg\\P1-Stocks.csv']

In [20]:
col_names = ['name']
df_tmp = pd.concat((pd.read_csv(file) for file in irreg_files), ignore_index=True)
df_tmp

      name
0   AEONTS
1      BCT
2    BLAND
3      BTS
4   BTSGIF
5      EPG
6   IMPACT
7      KYE
8      LHK
9      LPF
10    MACO
11     PTL
12     SFP
13  STANLY
14    TIF1
15    TLGF
16     TMW
17      TR
18    TSTH
19     VGI
20     AOT
21    CITY
22     FPT
23  GVREIT
24     IRC
25    KTIS
26      MC
27   OISHI
28    PICO
29     SSC
30   TFFIF
31      UV

In [21]:
stock_list = df_tmp['name'].unique().tolist()
stock_list_str = "','".join(stock_list)
print(stock_list_str)

AEONTS','BCT','BLAND','BTS','BTSGIF','EPG','IMPACT','KYE','LHK','LPF','MACO','PTL','SFP','STANLY','TIF1','TLGF','TMW','TR','TSTH','VGI','AOT','CITY','FPT','GVREIT','IRC','KTIS','MC','OISHI','PICO','SSC','TFFIF','UV

In [22]:
sql = f"""
SELECT name, COUNT(*) AS quarters 
FROM epss 
WHERE name NOT IN ('{stock_list_str}')
AND ((year = {year} AND quarter <= {quarter}) OR (year = {year}-1 AND quarter >= {quarter}+1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name"""
print(sql)

SELECT name, COUNT(*) AS quarters
FROM epss
WHERE name NOT IN ('AEONTS','BCT','BLAND','BTS','BTSGIF','EPG','IMPACT','KYE','LHK','LPF','MACO','PTL','SFP','STANLY','TIF1','TLGF','TMW','TR','TSTH','VGI','AOT','CITY','FPT','GVREIT','IRC','KTIS','MC','OISHI','PICO','SSC','TFFIF','UV')
AND ((year = 2026 AND quarter <= 1) OR (year = 2026-1 AND quarter >= 1+1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name

In [23]:
df = pd.read_sql(sql, conlt)
df

      name  quarters
0       AJ         3
1      BAY         3
2      BE8         3
3      DRT         3
4    EASTW         3
5    FORTH         3
6      GGC         3
7   GRAMMY         3
8     INOX         3
9      KEX         1
10    LHFG         3
11     LPH         3
12     PAP         3
13      RS         3
14     S11         3
15     SKN         3
16     SKR         3
17     SPC         3
18  SPRIME         3
19     SVI         3
20   TIPCO         3
21      TK         3

In [24]:
df.shape

(22, 2)

In [25]:
sql = f"""
SELECT name 
FROM epss 
WHERE name NOT IN ('{stock_list_str}')
AND (year = {year} AND quarter = {quarter}) 
ORDER BY name"""
print(sql)

SELECT name
FROM epss
WHERE name NOT IN ('AEONTS','BCT','BLAND','BTS','BTSGIF','EPG','IMPACT','KYE','LHK','LPF','MACO','PTL','SFP','STANLY','TIF1','TLGF','TMW','TR','TSTH','VGI','AOT','CITY','FPT','GVREIT','IRC','KTIS','MC','OISHI','PICO','SSC','TFFIF','UV')
AND (year = 2026 AND quarter = 1)
ORDER BY name

In [26]:
df_eps = pd.read_sql(sql, conlt)
df_eps

       name
0     3BBIF
1       ACE
2    ADVANC
3        AH
4       AIE
..      ...
171   WHAIR
172   WHART
173   WHAUP
174    WICE
175    WORK

[176 rows x 1 columns]

In [27]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file : {input_file}")

Input file : C:\Users\PC1\OneDrive\A4\Data\name-ttl.csv

In [28]:
# Read CSV that has no header
df_name = pd.read_csv(input_file, header=None)

# Add column name
df_name.columns = ['name']

# Now your DataFrame has a column named 'name'
print(df_name.head())

     name
0     ACE
1  ADVANC
2  AEONTS
3      AH
4     AIE

In [29]:
# Get rows that are only in df_name (not in df_eps)
# Select rows in df_name where 'name' is NOT in df_eps['name']
df_name_not_in_eps = df_name[~df_name['name'].isin(df_eps['name'])]
df_name_not_in_eps

       name
2    AEONTS
9       AOT
33    BLAND
35      BTS
36   BTSGIF
58      EPG
59    FORTH
67   GVREIT
76   IMPACT
97       MC
118     PTL
152     SVI
156   TFFIF
172    TSTH
181     VGI

In [30]:
file_name = "Incomplete-01.csv"
output_file = os.path.join(dat_path, file_name)
xsl_file = os.path.join(xsl_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [31]:
print(f"Output file : {output_file}") 
print(f"xsl_file : {xsl_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

Output file : C:\Users\PC1\OneDrive\A4\Data\Incomplete-01.csv
xsl_file : C:\Users\PC1\OneDrive\A4\Excel\Incomplete-01.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Incomplete-01.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Incomplete-01.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Incomplete-01.csv

In [32]:
df_name_not_in_eps.to_csv(output_file, header=True, index=False)
df_name_not_in_eps.to_csv(god_file, header=True, index=False)
df_name_not_in_eps.to_csv(icd_file, header=True, index=False)
df_name_not_in_eps.to_csv(osd_file, header=True, index=False)

### End of Normal Quarter stocks

In [80]:
sql = f"""
SELECT *
FROM epss 
WHERE name IN ('AOT','FPT') AND year >= 2025
ORDER BY name, year DESC, quarter DESC"""
print(sql)

SELECT *
FROM epss
WHERE name IN ('AOT','FPT') AND year >= 2025
ORDER BY name, year DESC, quarter DESC

In [82]:
df = pd.read_sql(sql, conlt)
df

,id,name,year,quarter,q_amt,y_amt,aq_amt,ay_amt,q_eps,y_eps,aq_eps,ay_eps,ticker_id,publish_date
0,24904,AOT,2026,1,4652626,5344298,4652626,5344298,0.33,0.37,0.33,0.37,24,2026-02-12
1,24862,AOT,2025,4,3862840,4272047,18125206,19182394,0.27,0.30,1.27,1.34,24,2025-11-21
2,24533,AOT,2025,3,3864797,4562722,14262366,14910347,0.27,0.32,1.00,1.04,24,2025-08-13
3,24414,AOT,2025,2,5053270,5784593,10397569,10347626,0.35,0.40,0.73,0.72,24,2025-05-14
4,24039,AOT,2025,1,5344298,4563033,5344298,4563033,0.37,0.32,0.37,0.32,24,2025-02-13
5,25281,FPT,2026,2,1269602,222210,1603572,548673,0.55,0.10,0.69,0.24,746,2026-05-05
6,25282,FPT,2026,1,333970,326463,333970,326463,0.14,0.14,0.14,0.14,746,2026-02-05
7,24863,FPT,2025,4,267933,632264,1460758,1438028,0.12,0.27,0.63,0.62,746,2025-11-06
8,24534,FPT,2025,3,644152,330697,1192825,805764,0.27,0.14,0.51,0.35,746,2025-08-13
9,24415,FPT,2025,2,222210,158526,548673,475067,0.10,0.06,0.24,0.20,746,2025-05-02
10,24008,FPT,2025,1,326463,316541,326463,316541,0.14,0.14,0.14,0.14,746,2025-02-04

In [36]:
# Get unique rows based on 'name' column
result = df.drop_duplicates(subset=['name'])
result

,id,name,year,quarter,q_amt,y_amt,aq_amt,ay_amt,q_eps,y_eps,aq_eps,ay_eps,ticker_id,publish_date
0,25181,GVREIT,2026,2,194332,200096,364410,403948,0.00,0.00,0.00,0.00,654,2026-05-13
6,25208,MC,2026,3,176306,188485,595273,625659,0.22,0.24,0.75,0.79,291,2026-05-14

In [37]:
sql_max = 'SELECT MAX(id) FROM epss'
result = pd.read_sql(sql_max, conlt)
result

   MAX(id)
0    25280