In [1]:
import os
import pandas as pd
from sqlalchemy import create_engine, text
from glob import glob

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()

engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

data_path = "../data/"
irreg_path = "../data/irreg/"

In [2]:
year = 2026
quarter = 1
year, quarter

(2026, 1)

### Begin of Irregular quarter

### Irregular Quarter Plus 1

In [5]:
file_name = 'P1-Stocks.csv'
input_file = irreg_path + file_name
# Read with header=0 (default) to use first row as column names
data_ins = pd.read_csv(input_file)
# Now data_ins will have the actual column name (probably 'name' or something else)
data_ins

      name
0      AOT
1     CITY
2      FPT
3   GVREIT
4      IRC
5     KTIS
6       MC
7    OISHI
8     PICO
9      SSC
10   TFFIF
11      UV

In [6]:
stock_list = data_ins['name'].unique().tolist()
stock_list_str = "','".join(stock_list)
print(stock_list_str)

AOT','CITY','FPT','GVREIT','IRC','KTIS','MC','OISHI','PICO','SSC','TFFIF','UV

In [7]:
sql = f'''
SELECT name, COUNT(*) FROM epss 
WHERE name in ('{stock_list_str}')
AND ((year = {year} AND quarter <= {quarter} + 1)
OR (year = {year} - 1 AND quarter > {quarter} + 1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name'''
print(sql)

SELECT name, COUNT(*) FROM epss
WHERE name in ('AOT','CITY','FPT','GVREIT','IRC','KTIS','MC','OISHI','PICO','SSC','TFFIF','UV')
AND ((year = 2026 AND quarter <= 1 + 1)
OR (year = 2026 - 1 AND quarter > 1 + 1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name

In [8]:
df = pd.read_sql(sql, conlt)
df

Empty DataFrame
Columns: [name, COUNT(*)]
Index: []

### Irregular Quarter Minus 1

In [10]:
file_name   = 'M1-Stocks.csv'
input_file = irreg_path + file_name
# Read with header=0 (default) to use first row as column names
data_ins = pd.read_csv(input_file)
# Now data_ins will have the actual column name (probably 'name' or something else)
data_ins

      name
0   AEONTS
1      BCT
2    BLAND
3      BTS
4   BTSGIF
5      EPG
6   IMPACT
7      KYE
8      LHK
9      LPF
10    MACO
11     PTL
12     SFP
13  STANLY
14    TIF1
15    TLGF
16     TMW
17      TR
18    TSTH
19     VGI

In [11]:
stock_list = data_ins['name'].unique().tolist()
stock_list_str = "','".join(stock_list)
print(stock_list_str)

AEONTS','BCT','BLAND','BTS','BTSGIF','EPG','IMPACT','KYE','LHK','LPF','MACO','PTL','SFP','STANLY','TIF1','TLGF','TMW','TR','TSTH','VGI

In [12]:
sql = f'''
SELECT name, COUNT(*) FROM epss 
WHERE name in ('{stock_list_str}')
AND ((year = {year} AND quarter <= {quarter} - 1)
OR (year = {year} - 1 AND quarter > {quarter} - 1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name'''
print(sql)

SELECT name, COUNT(*) FROM epss
WHERE name in ('AEONTS','BCT','BLAND','BTS','BTSGIF','EPG','IMPACT','KYE','LHK','LPF','MACO','PTL','SFP','STANLY','TIF1','TLGF','TMW','TR','TSTH','VGI')
AND ((year = 2026 AND quarter <= 1 - 1)
OR (year = 2026 - 1 AND quarter > 1 - 1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name

In [13]:
df = pd.read_sql(sql, conlt)
df

      name  COUNT(*)
0      BCT         3
1    BLAND         3
2      BTS         3
3   BTSGIF         3
4      EPG         3
5   IMPACT         3
6      KYE         3
7      LHK         3
8      PTL         3
9   STANLY         3
10     TMW         3
11      TR         3
12    TSTH         3
13     VGI         3

### End of Irregular quarter

### Normal Quarter Stocks

In [16]:
irreg_files = sorted(glob('../data/irreg/*.csv'))
irreg_files

['../data/irreg\\M1-Stocks.csv', '../data/irreg\\P1-Stocks.csv']

In [17]:
col_names = ['name']
df_tmp = pd.concat((pd.read_csv(file) for file in irreg_files), ignore_index=True)
df_tmp

      name
0   AEONTS
1      BCT
2    BLAND
3      BTS
4   BTSGIF
5      EPG
6   IMPACT
7      KYE
8      LHK
9      LPF
10    MACO
11     PTL
12     SFP
13  STANLY
14    TIF1
15    TLGF
16     TMW
17      TR
18    TSTH
19     VGI
20     AOT
21    CITY
22     FPT
23  GVREIT
24     IRC
25    KTIS
26      MC
27   OISHI
28    PICO
29     SSC
30   TFFIF
31      UV

In [18]:
stock_list = df_tmp['name'].unique().tolist()
stock_list_str = "','".join(stock_list)
print(stock_list_str)

AEONTS','BCT','BLAND','BTS','BTSGIF','EPG','IMPACT','KYE','LHK','LPF','MACO','PTL','SFP','STANLY','TIF1','TLGF','TMW','TR','TSTH','VGI','AOT','CITY','FPT','GVREIT','IRC','KTIS','MC','OISHI','PICO','SSC','TFFIF','UV

In [51]:
sql = f"""
SELECT name, COUNT(*) AS quarters 
FROM epss 
WHERE name NOT IN ('{stock_list_str}')
AND ((year = {year} AND quarter <= {quarter}) OR (year = {year}-1 AND quarter >= {quarter}+1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name"""
print(sql)

SELECT name, COUNT(*) AS quarters
FROM epss
WHERE name NOT IN ('AEONTS','BCT','BLAND','BTS','BTSGIF','EPG','IMPACT','KYE','LHK','LPF','MACO','PTL','SFP','STANLY','TIF1','TLGF','TMW','TR','TSTH','VGI','AOT','CITY','FPT','GVREIT','IRC','KTIS','MC','OISHI','PICO','SSC','TFFIF','UV')
AND ((year = 2026 AND quarter <= 1) OR (year = 2026-1 AND quarter >= 1+1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name

In [55]:
df_to_delete = pd.read_sql(sql, conlt)
df_to_delete

     name  quarters
0   FORTH         3
1     KEX         1
2  SPRIME         3
3     SVI         3

In [22]:
sql = 'SELECT * FROM exempts'
df_exempts = pd.read_sql(sql, conlt)
df_exempts

      id    name
0    507      2S
1    508       A
2    509     AAV
3    510     ABM
4    511   ABPIF
..   ...     ...
422  931     SPC
423  932  STANLY
424  933   TIPCO
425  934      TK
426  935     TMW

[427 rows x 2 columns]

In [23]:
df_merge = pd.merge(df, df_exempts, how = 'inner', on = 'name')
df_merge

      name  quarters   id
0       AJ         3  917
1      BAY         3  918
2      BE8         3  912
3      DRT         3  920
4    EASTW         3  913
5      GGC         3  914
6   GRAMMY         3  915
7     INOX         3  921
8     LHFG         3  924
9      LPH         3  926
10     PAP         3  927
11      RS         3  916
12     S11         3  928
13     SKN         3  929
14     SKR         3  930
15     SPC         3  931
16   TIPCO         3  933
17      TK         3  934

### End of Delete EPSs records

In [58]:
# ============================================
# BACKUP AND DELETE OPERATIONS FOR epss TABLE
# ============================================

# Step 1: Create backup of epss table before deletion
print("Creating backup of epss table...")

# Method 1: Create a backup table with timestamp
from datetime import datetime
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
backup_table_name = f"epss_backup_{timestamp}"

# Create backup table with all data from epss
backup_sql = f"""
CREATE TABLE IF NOT EXISTS {backup_table_name} AS
SELECT * FROM epss
"""
conlt.execute(text(backup_sql))
conlt.commit()
print(f"Backup table '{backup_table_name}' created successfully")

# Method 2: Also export to CSV as additional backup (optional)
backup_csv_path = f"../data/epss_backup_{timestamp}.csv"
df_epss_backup = pd.read_sql("SELECT * FROM epss", conlt)
df_epss_backup.to_csv(backup_csv_path, index=False)
print(f"CSV backup saved to: {backup_csv_path}")

Creating backup of epss table...
Backup table 'epss_backup_20260516_145320' created successfully
CSV backup saved to: ../data/epss_backup_20260516_145320.csv

In [60]:
# Step 2: Display count of records to be deleted
if len(df_to_delete) > 0:
    stock_list_to_delete = df_to_delete['name'].tolist()
    stock_list_str_delete = "','".join(stock_list_to_delete)
    
    # Count records to be deleted
    count_sql = f"""
    SELECT COUNT(*) as count_to_delete
    FROM epss
    WHERE name IN ('{stock_list_str_delete}')
    """
    count_to_delete = pd.read_sql(count_sql, conlt).iloc[0]['count_to_delete']
    print(f"\nRecords to be deleted: {count_to_delete}")
    print(f"Stocks to be deleted: {stock_list_to_delete}")

Records to be deleted: 134
Stocks to be deleted: ['FORTH', 'KEX', 'SPRIME', 'SVI']

In [62]:
# ============================================
# BACKUP AND DELETE OPERATIONS FOR epss TABLE
# ============================================

# Step 1: Create backup of epss table before deletion
print("Creating backup of epss table...")

# Method 1: Create a backup table with timestamp
from datetime import datetime
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
backup_table_name = f"epss_backup_{timestamp}"

# Create backup table with all data from epss
backup_sql = f"""
CREATE TABLE IF NOT EXISTS {backup_table_name} AS
SELECT * FROM epss
"""
conlt.execute(text(backup_sql))
conlt.commit()
print(f"Backup table '{backup_table_name}' created successfully")

# Method 2: Also export to CSV as additional backup (optional)
backup_csv_path = f"../data/epss_backup_{timestamp}.csv"
df_epss_backup = pd.read_sql("SELECT * FROM epss", conlt)
df_epss_backup.to_csv(backup_csv_path, index=False)
print(f"CSV backup saved to: {backup_csv_path}")

# Step 2: Display count of records to be deleted
if len(df_to_delete) > 0:
    stock_list_to_delete = df_to_delete['name'].tolist()
    stock_list_str_delete = "','".join(stock_list_to_delete)
    
    # Count records to be deleted
    count_sql = f"""
    SELECT COUNT(*) as count_to_delete
    FROM epss
    WHERE name IN ('{stock_list_str_delete}')
    """
    count_to_delete = pd.read_sql(count_sql, conlt).iloc[0]['count_to_delete']
    print(f"\nRecords to be deleted: {count_to_delete}")
    print(f"Stocks to be deleted: {stock_list_to_delete}")
    
    # Confirm deletion (uncomment if you want interactive confirmation)
    # confirmation = input("Do you want to proceed with deletion? (yes/no): ")
    # if confirmation.lower() != 'yes':
    #     print("Deletion cancelled")
    #     exit()
    
    # Step 3: Perform deletion
    delete_sql = f"""
    DELETE FROM epss
    WHERE name IN ('{stock_list_str_delete}')
    """
    
    try:
        result = conlt.execute(text(delete_sql))
        conlt.commit()
        print(f"\n✓ Successfully deleted {result.rowcount} records from epss table")
    except Exception as e:
        print(f"Error during deletion: {e}")
        conlt.rollback()
else:
    print("No records to delete - df_to_delete is empty")

# Step 4: Verify deletion
print("\n" + "="*50)
print("VERIFICATION AFTER DELETION")
print("="*50)

# Check remaining records
remaining_count = pd.read_sql("SELECT COUNT(*) as remaining FROM epss", conlt)
print(f"Remaining records in epss: {remaining_count.iloc[0]['remaining']}")

# Verify specific stocks were deleted
if len(df_to_delete) > 0:
    sample_stock = df_to_delete['name'].iloc[0]
    check_sql = f"SELECT COUNT(*) as found FROM epss WHERE name = '{sample_stock}'"
    check_result = pd.read_sql(check_sql, conlt)
    if check_result.iloc[0]['found'] == 0:
        print(f"✓ Verification passed: Stock '{sample_stock}' successfully deleted")
    else:
        print(f"✗ Verification failed: Stock '{sample_stock}' still exists")

Creating backup of epss table...
Backup table 'epss_backup_20260516_150055' created successfully
CSV backup saved to: ../data/epss_backup_20260516_150055.csv

Records to be deleted: 134
Stocks to be deleted: ['FORTH', 'KEX', 'SPRIME', 'SVI']

✓ Successfully deleted 134 records from epss table

==================================================
VERIFICATION AFTER DELETION
==================================================
Remaining records in epss: 9563
✓ Verification passed: Stock 'FORTH' successfully deleted

In [ ]:
# ============================================
# RESTORE INSTRUCTIONS AND SCRIPT
# ============================================

print("\n" + "="*50)
print("RESTORE INSTRUCTIONS")
print("="*50)
print(f"""
To restore the epss table from backup, use ONE of the following methods:

METHOD 1 - Restore from backup table:
--------------------------------------------------
Run the following SQL command:

    DROP TABLE IF EXISTS epss;
    CREATE TABLE epss AS SELECT * FROM {backup_table_name};

Or in Python:

    # Drop current epss table
    conlt.execute(text("DROP TABLE IF EXISTS epss"))
    
    # Create epss from backup
    conlt.execute(text(f"CREATE TABLE epss AS SELECT * FROM {backup_table_name}"))
    conlt.commit()
    print("epss table restored successfully")

METHOD 2 - Restore from CSV backup:
--------------------------------------------------
    df_restore = pd.read_csv('{backup_csv_path}')
    df_restore.to_sql('epss', conlt, if_exists='replace', index=False)
    print("epss table restored from CSV")

METHOD 3 - Restore specific deleted records:
--------------------------------------------------
If you only want to restore deleted records (not the entire table):

    # Get deleted records from backup
    restore_sql = f\"\"\"
    INSERT INTO epss
    SELECT * FROM {backup_table_name}
    WHERE name IN ('{stock_list_str_delete}')
    \"\"\"
    conlt.execute(text(restore_sql))
    conlt.commit()
    print(f"Restored records for stocks: {stock_list_to_delete}")

NOTE: The backup table '{backup_table_name}' and CSV file '{backup_csv_path}' 
have been created and will persist. You can delete them manually when no longer needed.
""")

# Optional: Display sample of deleted data (first 5 records)
if len(df_merge) > 0:
    print("\n" + "="*50)
    print("SAMPLE OF DELETED DATA (First 5 records)")
    print("="*50)
    deleted_data_sql = f"""
    SELECT * FROM {backup_table_name}
    WHERE name IN ('{stock_list_str_delete}')
    LIMIT 5
    """
    deleted_sample = pd.read_sql(deleted_data_sql, conlt)
    print(deleted_sample)

print("\n✓ Deletion process completed successfully")

In [ ]:
# ============================================
# RESTORE INSTRUCTIONS AND SCRIPT
# ============================================

print("\n" + "="*50)
print("RESTORE INSTRUCTIONS")
print("="*50)
print(f"""
To restore the epss table from backup, use ONE of the following methods:

METHOD 1 - Restore from backup table:
--------------------------------------------------
Run the following SQL command:

    DROP TABLE IF EXISTS epss;
    CREATE TABLE epss AS SELECT * FROM {backup_table_name};

Or in Python:

    # Drop current epss table
    conlt.execute(text("DROP TABLE IF EXISTS epss"))
    
    # Create epss from backup
    conlt.execute(text(f"CREATE TABLE epss AS SELECT * FROM {backup_table_name}"))
    conlt.commit()
    print("epss table restored successfully")

METHOD 2 - Restore from CSV backup:
--------------------------------------------------
    df_restore = pd.read_csv('{backup_csv_path}')
    df_restore.to_sql('epss', conlt, if_exists='replace', index=False)
    print("epss table restored from CSV")

METHOD 3 - Restore specific deleted records:
--------------------------------------------------
If you only want to restore deleted records (not the entire table):

    # Get deleted records from backup
    restore_sql = f\"\"\"
    INSERT INTO epss
    SELECT * FROM {backup_table_name}
    WHERE name IN ('{stock_list_str_delete}')
    \"\"\"
    conlt.execute(text(restore_sql))
    conlt.commit()
    print(f"Restored records for stocks: {stock_list_to_delete}")

NOTE: The backup table '{backup_table_name}' and CSV file '{backup_csv_path}' 
have been created and will persist. You can delete them manually when no longer needed.
""")

# Optional: Display sample of deleted data (first 5 records)
if len(df_to_delete) > 0:
    print("\n" + "="*50)
    print("SAMPLE OF DELETED DATA (First 5 records)")
    print("="*50)
    deleted_data_sql = f"""
    SELECT * FROM {backup_table_name}
    WHERE name IN ('{stock_list_str_delete}')
    LIMIT 5
    """
    deleted_sample = pd.read_sql(deleted_data_sql, conlt)
    print(deleted_sample)

print("\n✓ Deletion process completed successfully")