In [1]:
import numpy as np
import pandas as pd
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

year = 2026
quarter = 2
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-08-12 11:03:28

### Insert Profits from PortLt to PortMy

In [4]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

lt_profits = pd.read_sql(sql, conlt)
lt_profits

SELECT *
FROM profits
WHERE  year = 2026 AND quarter = 2

,id,name,year,quarter,kind,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,latest_amt_q,...,q_amt_c,y_amt,inc_amt_py,inc_pct_py,q_amt_p,inc_amt_pq,inc_pct_pq,ticker_id,mean_pct,std_pct
0,2899,3BBIF,2026,2,1,8136155,5497047,2639108,48.01,8136155,...,4211921,2907279,1304642,44.875019,-2689000,6900921,256.635218,234,92.155059,110.415809
1,2900,ADVANC,2026,2,1,53532002,37207829,16324173,43.87,53532002,...,13716006,10981885,2734121,24.896646,13495505,220501,1.633885,6,18.945133,19.496680
2,2901,BCP,2026,2,1,21707621,1862603,19845018,1065.45,21707621,...,12239355,-2560098,14799453,578.081503,6143762,6095593,99.215969,52,489.244368,434.994261
3,2902,COM7,2026,2,1,4608974,3466058,1142916,32.97,4608974,...,1303069,1003155,299914,29.897075,1226182,76887,6.270439,114,19.024379,14.386430
4,2903,DOHOME,2026,2,1,754975,674841,80134,11.87,754975,...,305380,157174,148206,94.294222,250732,54648,21.795383,701,38.097401,37.852842
5,2904,GLOBAL,2026,2,1,2579705,2273624,306081,13.46,2579705,...,955484,520401,435083,83.605335,802569,152915,19.053190,193,34.102131,33.135632
6,2905,KKP,2026,2,1,7519473,4540664,2978809,65.60,7519473,...,2122087,1409402,712685,50.566481,1955494,166593,8.519228,255,33.788927,28.727227
7,2906,KTC,2026,2,1,8422876,7494674,928202,12.38,8422876,...,2225308,1894792,330516,17.443392,2171234,54074,2.490473,259,9.098466,7.053529
8,2907,MINT,2026,2,1,9463753,7021008,2442745,34.79,9463753,...,3308002,3085506,222496,7.211005,648780,2659222,409.880391,301,113.572849,198.052954
9,2908,MTC,2026,2,1,7233031,6049148,1183883,19.57,7233031,...,1904948,1647011,257937,15.660915,1823034,81914,4.493279,315,10.856049,7.973154
10,2909,PSL,2026,2,1,1227074,918570,308504,33.59,1227074,...,521494,-43313,564807,1304.012652,108186,413308,382.034644,734,451.229324,588.888450
11,2910,SCGP,2026,2,1,6029794,2874304,3155490,109.78,6029794,...,2303796,1009793,1294003,128.145372,1566168,737628,47.097629,713,78.085750,48.469634
12,2911,SGP,2026,2,1,4565168,808254,3756914,464.82,4565168,...,2591449,-559848,3151297,562.884390,1530428,1061021,69.328384,441,329.978194,224.971076
13,2912,SIS,2026,2,1,1008907,721410,287497,39.85,1008907,...,267554,191114,76440,39.997070,258003,9551,3.701895,449,22.937241,19.699949
14,2913,SYNEX,2026,2,1,835486,663944,171542,25.84,835486,...,222698,190158,32540,17.112086,221377,1321,0.596720,495,11.899701,11.702935
15,2914,TCAP,2026,2,1,8737297,6593539,2143758,32.51,8737297,...,2641274,2067435,573839,27.756084,2123240,518034,24.398278,503,22.923591,11.106052
16,2915,THANI,2026,2,1,1315427,710624,604803,85.11,1315427,...,359525,278679,80846,29.010439,340348,19177,5.634527,522,31.576241,37.290445
17,2916,WHART,2026,2,1,2461472,1923220,538252,27.99,2461472,...,696766,594099,102667,17.281127,674906,21860,3.238970,622,13.215024,11.732340
18,2917,WHAUP,2026,2,1,1485941,872293,613648,70.35,1485941,...,531766,141485,390281,275.846203,303155,228611,75.410599,623,114.306700,109.135552

In [6]:
#still don't know why has to drop id
lt_profits = lt_profits.drop(columns=['id'])
lt_profits.shape

(19, 22)

In [8]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

my_profits = pd.read_sql(sql, conmy)
my_profits

SELECT *
FROM profits
WHERE  year = 2026 AND quarter = 2

Empty DataFrame
Columns: [id, name, year, quarter, kind, latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y, latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q, q_amt_c, y_amt, inc_amt_py, inc_pct_py, q_amt_p, inc_amt_pq, inc_pct_pq, ticker_id, mean_pct, std_pct]
Index: []

[0 rows x 23 columns]

In [10]:
sqlDel = text("DELETE FROM profits WHERE year = :year AND quarter = :quarter")
print(sqlDel)  # Shows the uncompiled SQL with placeholders

# Execute and get the result
result = conmy.execute(sqlDel, {"year": year, "quarter": quarter})
rows_deleted = result.rowcount  # Get the number of rows deleted
#conmy.commit()  # Commit the transaction

print(f"Number of rows deleted: {rows_deleted}")

DELETE FROM profits WHERE year = :year AND quarter = :quarter
Number of rows deleted: 0

In [12]:
sql = """
SELECT * 
FROM profits 
WHERE  id = 210"""
print(sql)

dlt_profits = pd.read_sql(sql, conmy)
dlt_profits

SELECT *
FROM profits
WHERE  id = 210

Empty DataFrame
Columns: [id, name, year, quarter, kind, latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y, latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q, q_amt_c, y_amt, inc_amt_py, inc_pct_py, q_amt_p, inc_amt_pq, inc_pct_pq, ticker_id, mean_pct, std_pct]
Index: []

[0 rows x 23 columns]

In [14]:
sqlDelTmp = text("DELETE FROM profits WHERE id = 210")
print(sqlDelTmp)  # Shows the uncompiled SQL with placeholders

# Execute and get the result
result = conmy.execute(sqlDelTmp)
rows_deleted = result.rowcount  # Get the number of rows deleted
#conmy.commit()  # Commit the transaction

print(f"Number of rows deleted: {rows_deleted}")

DELETE FROM profits WHERE id = 210
Number of rows deleted: 0

In [16]:
conmy.commit()

In [18]:
# Define SQL statement using named placeholders
sqlInsMy = text("""
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)
""")
print(sqlInsMy)

INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)

In [20]:
rcds = lt_profits.values.tolist()
print(f"Number of rows to insert: {len(rcds)}")

Number of rows to insert: 19

In [22]:
# Convert list data to dictionaries for named parameters
columns = [
    "name", "year", "quarter", "kind",
    "latest_amt_y", "previous_amt_y", "inc_amt_y", "inc_pct_y",
    "latest_amt_q", "previous_amt_q", "inc_amt_q", "inc_pct_q",
    "q_amt_c", "y_amt", "inc_amt_py", "inc_pct_py",
    "q_amt_p", "inc_amt_pq", "inc_pct_pq",
    "ticker_id", "mean_pct", "std_pct"
]

records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]
#print(records_dicts)

# Check for empty records before attempting insertion
if not rcds:
    print("No records to insert - skipping database operation")
    # In notebook/script context, just proceed to next cell instead of 'return'
else:    
    try:
        result = conmy.execute(sqlInsMy, records_dicts)  # Bulk insert using named parameters
        rows_insert = result.rowcount
        print(f"{rows_insert} rows inserted successfully!")
    except Exception as e:
        print("Error inserting data:", e)
    finally:
        conmy.commit()

19 rows inserted successfully!

In [24]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

my_profits = pd.read_sql(sql, conmy)
my_profits

SELECT *
FROM profits
WHERE  year = 2026 AND quarter = 2

,id,name,year,quarter,kind,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,latest_amt_q,...,q_amt_c,y_amt,inc_amt_py,inc_pct_py,q_amt_p,inc_amt_pq,inc_pct_pq,ticker_id,mean_pct,std_pct
0,382,3BBIF,2026,2,1,8136155,5497047,2639108,48.01,8136155,...,4211921,2907279,1304642,44.875019,-2689000,6900921,256.635218,234,92.155059,110.415809
1,383,ADVANC,2026,2,1,53532002,37207829,16324173,43.87,53532002,...,13716006,10981885,2734121,24.896646,13495505,220501,1.633885,6,18.945133,19.496680
2,384,BCP,2026,2,1,21707621,1862603,19845018,1065.45,21707621,...,12239355,-2560098,14799453,578.081503,6143762,6095593,99.215969,52,489.244368,434.994261
3,385,COM7,2026,2,1,4608974,3466058,1142916,32.97,4608974,...,1303069,1003155,299914,29.897075,1226182,76887,6.270439,114,19.024379,14.386430
4,386,DOHOME,2026,2,1,754975,674841,80134,11.87,754975,...,305380,157174,148206,94.294222,250732,54648,21.795383,701,38.097401,37.852842
5,387,GLOBAL,2026,2,1,2579705,2273624,306081,13.46,2579705,...,955484,520401,435083,83.605335,802569,152915,19.053190,193,34.102131,33.135632
6,388,KKP,2026,2,1,7519473,4540664,2978809,65.60,7519473,...,2122087,1409402,712685,50.566481,1955494,166593,8.519228,255,33.788927,28.727227
7,389,KTC,2026,2,1,8422876,7494674,928202,12.38,8422876,...,2225308,1894792,330516,17.443392,2171234,54074,2.490473,259,9.098466,7.053529
8,390,MINT,2026,2,1,9463753,7021008,2442745,34.79,9463753,...,3308002,3085506,222496,7.211005,648780,2659222,409.880391,301,113.572849,198.052954
9,391,MTC,2026,2,1,7233031,6049148,1183883,19.57,7233031,...,1904948,1647011,257937,15.660915,1823034,81914,4.493279,315,10.856049,7.973154
10,392,PSL,2026,2,1,1227074,918570,308504,33.59,1227074,...,521494,-43313,564807,1304.012652,108186,413308,382.034644,734,451.229324,588.888450
11,393,SCGP,2026,2,1,6029794,2874304,3155490,109.78,6029794,...,2303796,1009793,1294003,128.145372,1566168,737628,47.097629,713,78.085750,48.469634
12,394,SGP,2026,2,1,4565168,808254,3756914,464.82,4565168,...,2591449,-559848,3151297,562.884390,1530428,1061021,69.328384,441,329.978194,224.971076
13,395,SIS,2026,2,1,1008907,721410,287497,39.85,1008907,...,267554,191114,76440,39.997070,258003,9551,3.701895,449,22.937241,19.699949
14,396,SYNEX,2026,2,1,835486,663944,171542,25.84,835486,...,222698,190158,32540,17.112086,221377,1321,0.596720,495,11.899701,11.702935
15,397,TCAP,2026,2,1,8737297,6593539,2143758,32.51,8737297,...,2641274,2067435,573839,27.756084,2123240,518034,24.398278,503,22.923591,11.106052
16,398,THANI,2026,2,1,1315427,710624,604803,85.11,1315427,...,359525,278679,80846,29.010439,340348,19177,5.634527,522,31.576241,37.290445
17,399,WHART,2026,2,1,2461472,1923220,538252,27.99,2461472,...,696766,594099,102667,17.281127,674906,21860,3.238970,622,13.215024,11.732340
18,400,WHAUP,2026,2,1,1485941,872293,613648,70.35,1485941,...,531766,141485,390281,275.846203,303155,228611,75.410599,623,114.306700,109.135552

In [26]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y:%m:%d %H:%M:%S")
print(formatted_time)

2026:08:12 11:04:48