In [1]:
import numpy as np
import pandas as pd
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

year = 2025
quarter = 3

current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2025-11-30 11:33:41

### Insert Profits from PortLt to PortMy

In [4]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

lt_profits = pd.read_sql(sql, conlt)
lt_profits

SELECT *
FROM profits
WHERE  year = 2025 AND quarter = 3

,id,name,year,quarter,kind,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,latest_amt_q,...,q_amt_c,y_amt,inc_amt_py,inc_pct_py,q_amt_p,inc_amt_pq,inc_pct_pq,ticker_id,mean_pct,std_pct
0,2811,FPT,2025,3,1,1825089,1636546,188543,11.52,1825089,...,644152,330697,313455,94.786164,222210,421942,189.884344,746,79.232627,82.648053
1,2821,CKP,2025,3,1,2491436,1346529,1144907,85.03,2491436,...,1270148,1190919,79229,6.652761,610152,659996,108.169112,107,50.782968,53.758831
2,2822,RCL,2025,3,1,9681980,5280406,4401574,83.36,9681980,...,2300555,4091182,-1790627,-43.767962,2004879,295676,14.747823,396,9.682465,54.622016
3,2823,ACE,2025,3,1,839069,750207,88862,11.84,839069,...,210777,110520,100257,90.713898,148794,61983,41.656922,698,39.445205,36.810072
4,2824,ADVANC,2025,3,1,42863183,32818977,10044206,30.60,42863183,...,12038861,8788129,3250732,36.990035,10981885,1056976,9.624723,6,21.356189,14.609526
5,2825,AMATA,2025,3,1,3130606,2142951,987655,46.09,3130606,...,1138536,765130,373406,48.802949,139867,998669,714.013313,21,205.611565,339.312980
6,2826,BA,2025,3,1,3648593,2910875,737718,25.34,3648593,...,1040922,671223,369699,55.078417,401749,639173,159.097596,45,62.699003,66.809109
7,2827,BGRIM,2025,3,1,1968731,1233128,735603,59.65,1968731,...,520997,162749,358248,220.123012,6846,514151,7510.239556,59,1953.063142,3705.778484
8,2828,BKIH,2025,3,1,3386810,2761710,625100,22.63,3386810,...,1121712,1144725,-23013,-2.010352,955826,165886,17.355251,68,12.703725,10.593870
9,2829,BLA,2025,3,1,7271185,3027476,4243709,140.17,7271185,...,2305941,1497610,808331,53.974733,2128385,177556,8.342288,70,58.201755,57.735084
10,2830,CENTEL,2025,3,1,1685602,1510544,175058,11.59,1685602,...,160361,163096,-2735,-1.676926,110343,50018,45.329563,92,13.770659,21.858720
11,2831,CK,2025,3,1,2712981,1773101,939880,53.01,2712981,...,1738865,1007708,731157,72.556435,862763,876102,101.546079,106,66.000629,27.824706
12,2832,GFPT,2025,3,1,2378968,2001260,377708,18.87,2378968,...,715408,541804,173604,32.041845,642113,73295,11.414658,187,17.549126,10.694248
13,2833,MTC,2025,3,1,6484813,5675828,808985,14.25,6484813,...,1723953,1491064,232889,15.618981,1647011,76942,4.671614,315,9.567649,6.234109
14,2834,OR,2025,3,1,12224912,4843875,7381037,152.38,12224912,...,2614259,-1608745,4223004,262.503007,2231799,382460,17.136848,715,121.197464,110.227850
15,2835,PCSGH,2025,3,1,680862,495395,185467,37.44,680862,...,132602,75631,56971,75.327577,116942,15660,13.391254,346,33.822208,30.347505
16,2836,SSP,2025,3,1,650095,566446,83649,14.77,650095,...,111736,113660,-1924,-1.692768,-13732,125468,913.690650,643,231.616970,454.776878
17,2837,SYNEX,2025,3,1,723427,628765,94662,15.06,723427,...,198138,168908,29230,17.305279,190158,7980,4.196510,495,10.192947,6.976780
18,2838,THANI,2025,3,1,955604,838723,116881,13.94,955604,...,300620,79786,220834,276.782894,278679,21941,7.873216,522,82.161528,130.084611
19,2839,TOA,2025,3,1,2523302,2013648,509654,25.31,2523302,...,687726,187898,499828,266.010282,651794,35932,5.512785,645,80.383267,124.092263
20,2840,TTA,2025,3,1,2303219,462798,1840421,397.67,2303219,...,502910,1088859,-585949,-53.813120,90105,412805,458.137728,579,256.433652,229.458910
21,2841,TTW,2025,3,1,3190977,2857325,333652,11.68,3190977,...,976211,915526,60685,6.628430,796563,179648,22.552893,581,10.700331,8.846219

In [6]:
#still don't know why has to drop id
lt_profits = lt_profits.drop(columns=['id'])
lt_profits.shape

(22, 22)

In [8]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

my_profits = pd.read_sql(sql, conmy)
my_profits

SELECT *
FROM profits
WHERE  year = 2025 AND quarter = 3

,id,name,year,quarter,kind,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,latest_amt_q,...,q_amt_c,y_amt,inc_amt_py,inc_pct_py,q_amt_p,inc_amt_pq,inc_pct_pq,ticker_id,mean_pct,std_pct
0,305,FPT,2025,3,1,1825089,1636546,188543,11.52,1825089,...,644152,330697,313455,94.786164,222210,421942,189.884344,746,79.232627,82.648053
1,306,CKP,2025,3,1,2491436,1346529,1144907,85.03,2491436,...,1270148,1190919,79229,6.652761,610152,659996,108.169112,107,50.782968,53.758831
2,307,RCL,2025,3,1,9681980,5280406,4401574,83.36,9681980,...,2300555,4091182,-1790627,-43.767962,2004879,295676,14.747823,396,9.682465,54.622016

In [10]:
sqlDel = text("DELETE FROM profits WHERE year = :year AND quarter = :quarter")
print(sqlDel)  # Shows the uncompiled SQL with placeholders

# Execute and get the result
result = conmy.execute(sqlDel, {"year": year, "quarter": quarter})
rows_deleted = result.rowcount  # Get the number of rows deleted
#conmy.commit()  # Commit the transaction

print(f"Number of rows deleted: {rows_deleted}")

DELETE FROM profits WHERE year = :year AND quarter = :quarter

OperationalError: (sqlite3.OperationalError) database is locked
[SQL: DELETE FROM profits WHERE year = ? AND quarter = ?]
[parameters: (2025, 3)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
# Define SQL statement using named placeholders
sqlInsMy = text("""
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)
""")
print(sqlInsMy)

In [ ]:
rcds = lt_profits.values.tolist()
print(f"Number of rows to insert: {len(rcds)}")

In [ ]:
# Convert list data to dictionaries for named parameters
columns = [
    "name", "year", "quarter", "kind",
    "latest_amt_y", "previous_amt_y", "inc_amt_y", "inc_pct_y",
    "latest_amt_q", "previous_amt_q", "inc_amt_q", "inc_pct_q",
    "q_amt_c", "y_amt", "inc_amt_py", "inc_pct_py",
    "q_amt_p", "inc_amt_pq", "inc_pct_pq",
    "ticker_id", "mean_pct", "std_pct"
]

records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]
#print(records_dicts)

# Check for empty records before attempting insertion
if not rcds:
    print("No records to insert - skipping database operation")
    # In notebook/script context, just proceed to next cell instead of 'return'
else:    
    try:
        result = conmy.execute(sqlInsMy, records_dicts)  # Bulk insert using named parameters
        rows_insert = result.rowcount
        print(f"{rows_insert} rows inserted successfully!")
    except Exception as e:
        print("Error inserting data:", e)
    finally:
        conmy.commit()

In [ ]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

my_profits = pd.read_sql(sql, conmy)
my_profits

In [16]:
### PortPg Process

In [18]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

pg_profits = pd.read_sql(sql, conpg)
pg_profits

SELECT *
FROM profits
WHERE  year = 2025 AND quarter = 3

,id,name,year,quarter,kind,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,latest_amt_q,...,y_amt,inc_amt_py,inc_pct_py,q_amt_p,inc_amt_pq,inc_pct_pq,mean_pct,std_pct,publish_date,ticker_id
0,67864,FPT,2025,3,1,1825089,1636546,188543,11.52,1825089,...,330697,313455,94.786164,222210,421942,189.884344,79.232627,82.648053,None,722
1,67865,CKP,2025,3,1,2491436,1346529,1144907,85.03,2491436,...,1190919,79229,6.652761,610152,659996,108.169112,50.782968,53.758831,None,110
2,67866,RCL,2025,3,1,9681980,5280406,4401574,83.36,9681980,...,4091182,-1790627,-43.767962,2004879,295676,14.747823,9.682465,54.622016,None,401

In [20]:
sqlDel = text("DELETE FROM profits WHERE year = :year AND quarter = :quarter")
print(sqlDel)  # Shows the uncompiled SQL with placeholders

# Execute and get the result
result = conpg.execute(sqlDel, {"year": year, "quarter": quarter})
rows_deleted = result.rowcount  # Get the number of rows deleted

print(f"Number of rows deleted: {rows_deleted}")

DELETE FROM profits WHERE year = :year AND quarter = :quarter
Number of rows deleted: 3

In [22]:
sql = 'SELECT name, id FROM tickers'
pg_tickers = pd.read_sql(sql, conpg)
pg_tickers.shape

(396, 2)

In [24]:
df_merge = pd.merge(my_profits, pg_tickers, on="name", how="inner")
df_merge

,id_x,name,year,quarter,kind,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,latest_amt_q,...,y_amt,inc_amt_py,inc_pct_py,q_amt_p,inc_amt_pq,inc_pct_pq,ticker_id,mean_pct,std_pct,id_y
0,305,FPT,2025,3,1,1825089,1636546,188543,11.52,1825089,...,330697,313455,94.786164,222210,421942,189.884344,746,79.232627,82.648053,722
1,306,CKP,2025,3,1,2491436,1346529,1144907,85.03,2491436,...,1190919,79229,6.652761,610152,659996,108.169112,107,50.782968,53.758831,110
2,307,RCL,2025,3,1,9681980,5280406,4401574,83.36,9681980,...,4091182,-1790627,-43.767962,2004879,295676,14.747823,396,9.682465,54.622016,401

In [26]:
df_merge = df_merge.drop(columns=['ticker_id']).rename(columns={'id_y': 'ticker_id'})

In [28]:
columns = 'name ticker_id'.split()
df_merge[columns]

  name  ticker_id
0  FPT        722
1  CKP        110
2  RCL        401

In [30]:
colv = 'name year quarter kind latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt \
        inc_amt_py inc_pct_py q_amt_p inc_amt_pq inc_pct_pq \
        ticker_id mean_pct std_pct'.split()
format_dict = {
    'q_amt': '{:,}',
    'y_amt': '{:,}',
    'yoy_gain': '{:,}',
    'q_amt_c': '{:,}',
    'q_amt_p': '{:,}',
    'aq_amt': '{:,}',
    'ay_amt': '{:,}',
    'acc_gain': '{:,}',
    'latest_amt': '{:,}',
    'previous_amt': '{:,}',
    'inc_amt': '{:,}',
    'inc_amt_pq': '{:,}',
    'inc_amt_py': '{:,}',    
    'latest_amt_q': '{:,}',
    'previous_amt_q': '{:,}',
    'inc_amt_q': '{:,}',
    'latest_amt_y': '{:,}',
    'previous_amt_y': '{:,}',
    'inc_amt_y': '{:,}',
    'kind_x': '{:,}',
    'inc_pct': '{:.2f}%',
    'inc_pct_q': '{:.2f}%',
    'inc_pct_y': '{:.2f}%',
    'inc_pct_pq': '{:.2f}%',
    'inc_pct_py': '{:.2f}%',   
    'mean_pct': '{:.2f}%',
    'std_pct': '{:.2f}%',      
}

In [32]:
final = df_merge[colv].copy()
final.sort_values(by=['ticker_id'],ascending=True).style.format(format_dict)

In [34]:
# Define SQL statement using named placeholders
sqlInsPg = text("""
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)
""")

# Convert list data to dictionaries for named parameters
columns = [
    "name", "year", "quarter", "kind",
    "latest_amt_y", "previous_amt_y", "inc_amt_y", "inc_pct_y",
    "latest_amt_q", "previous_amt_q", "inc_amt_q", "inc_pct_q",
    "q_amt_c", "y_amt", "inc_amt_py", "inc_pct_py",
    "q_amt_p", "inc_amt_pq", "inc_pct_pq",
    "ticker_id", "mean_pct", "std_pct"
]
print(sqlInsPg)

INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)

In [36]:
rcds = final.values.tolist()
print(f"Number of rows to insert: {len(rcds)}")

Number of rows to insert: 3

In [38]:
records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]
#print(records_dicts)

# Check for empty records before attempting insertion
if not rcds:
    print("No records to insert - skipping database operation")
    # In notebook/script context, just proceed to next cell instead of 'return'
else:
    try:
        result = conpg.execute(sqlInsPg, records_dicts)  # Bulk insert using named parameters
        rows_insert = result.rowcount
        print(f"{rows_insert} rows inserted successfully!")
    except Exception as e:
        print("Error inserting data:", e)
    finally:
        conpg.commit()

3 rows inserted successfully!

In [40]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

pg_profits = pd.read_sql(sql, conpg)
pg_profits

SELECT *
FROM profits
WHERE  year = 2025 AND quarter = 3

,id,name,year,quarter,kind,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,latest_amt_q,...,y_amt,inc_amt_py,inc_pct_py,q_amt_p,inc_amt_pq,inc_pct_pq,mean_pct,std_pct,publish_date,ticker_id
0,67867,FPT,2025,3,1,1825089,1636546,188543,11.52,1825089,...,330697,313455,94.786164,222210,421942,189.884344,79.232627,82.648053,None,722
1,67868,CKP,2025,3,1,2491436,1346529,1144907,85.03,2491436,...,1190919,79229,6.652761,610152,659996,108.169112,50.782968,53.758831,None,110
2,67869,RCL,2025,3,1,9681980,5280406,4401574,83.36,9681980,...,4091182,-1790627,-43.767962,2004879,295676,14.747823,9.682465,54.622016,None,401

In [42]:
stock_list = pg_profits['name'].unique().tolist()
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

"'FPT', 'CKP', 'RCL'"

In [44]:
sql = f"SELECT name, year, quarter, publish_date FROM epss WHERE year = {year} AND quarter = {quarter} AND name IN ('{stock_list_str}')"
print(sql)
df_epss_profits = pd.read_sql(sql, conlt)
df_epss_profits

  name  year  quarter publish_date
0  CKP  2025        3   2025-11-10
1  FPT  2025        3   2025-08-13
2  RCL  2025        3   2025-11-07

In [46]:
sql = f"""
SELECT name, year, quarter, publish_date 
FROM epss 
WHERE year = {year} AND quarter = {quarter} AND name IN ('{stock_list_str}')"""

df_epss_profits = pd.read_sql(sql, conlt)

if not df_epss_profits.empty:
    update_sql = text("""
        UPDATE profits 
        SET publish_date = :publish_date
        WHERE name = :name AND year = :year AND quarter = :quarter
    """)
    
    # Execute update for each row in df_epss_profits
    for _, row in df_epss_profits.iterrows():
        conpg.execute(update_sql, {
            'publish_date': row['publish_date'],
            'name': row['name'],
            'year': row['year'],
            'quarter': row['quarter']
        })

In [48]:
#After update publish_date from epss to profits
sql = """
SELECT name, year, quarter, publish_date 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

pg_profits = pd.read_sql(sql, conpg)
pg_profits

SELECT name, year, quarter, publish_date
FROM profits
WHERE  year = 2025 AND quarter = 3

  name  year  quarter publish_date
0  CKP  2025        3   2025-11-10
1  FPT  2025        3   2025-08-13
2  RCL  2025        3   2025-11-07