In [3]:
import numpy as np
import pandas as pd
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

year = 2025
quarter = 4
select_date = date.today()
select_date = select_date.strftime("%Y-%m-%d")
print(select_date)

2026-03-12

In [5]:
select_date = date(2026, 1, 1)
select_date = select_date.strftime("%Y-%m-%d")
print(select_date)

2026-01-01

In [7]:
cols = "name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y".split()
colt = "year quarter q_amt y_amt aq_amt ay_amt".split()
colu = 'name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt q_amt_p'.split() 
colv = 'name year quarter kind latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt \
        inc_amt_py inc_pct_py q_amt_p inc_amt_pq inc_pct_pq \
        ticker_id mean_pct std_pct'.split()
colw = 'name year quarter kind_x latest_amt_y_x previous_amt_y_x inc_amt_y_x inc_pct_y_x \
        latest_amt_q_x previous_amt_q_x inc_amt_q_x inc_pct_q_x q_amt_c_x y_amt_x \
        inc_amt_py_x inc_pct_py_x q_amt_p_x inc_amt_pq_x inc_pct_pq_x \
        ticker_id_x mean_pct_x std_pct_x'.split()

format_dict = {
    'q_amt': '{:,}',
    'y_amt': '{:,}',
    'yoy_gain': '{:,}',
    'q_amt_c': '{:,}',
    'q_amt_p': '{:,}',
    'aq_amt': '{:,}',
    'ay_amt': '{:,}',
    'acc_gain': '{:,}',
    'latest_amt': '{:,}',
    'previous_amt': '{:,}',
    'inc_amt': '{:,}',
    'inc_amt_pq': '{:,}',
    'inc_amt_py': '{:,}',    
    'latest_amt_q': '{:,}',
    'previous_amt_q': '{:,}',
    'inc_amt_q': '{:,}',
    'latest_amt_y': '{:,}',
    'previous_amt_y': '{:,}',
    'inc_amt_y': '{:,}',
    'kind_x': '{:,}',
    'inc_pct': '{:.2f}%',
    'inc_pct_q': '{:.2f}%',
    'inc_pct_y': '{:.2f}%',
    'inc_pct_pq': '{:.2f}%',
    'inc_pct_py': '{:.2f}%',   
    'mean_pct': '{:.2f}%',
    'std_pct': '{:.2f}%',      
}

### Process for specified stocks

In [8]:
names = """
IP
""".split()
names

['IP']

In [10]:
stock_list = names
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

"'IP'"

In [12]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = {year} AND quarter = {quarter}
AND name IN ('{stock_list_str}')
"""
print(sql)
epss = pd.read_sql(sql, conlt)
epss.style.format(format_dict)

### End of Process for specified stocks

In [13]:
sql = f"""
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = {year} AND quarter = {quarter}
AND publish_date >= '{select_date}'
"""
print(sql)
epss = pd.read_sql(sql, conlt)
#epss.style.format(format_dict)
epss.shape

SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt
FROM epss
WHERE year = 2025 AND quarter = 4
AND publish_date >= '2026-01-01'

(194, 7)

### End of Normal Process

In [15]:
sql = f"""
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM qt_profits 
WHERE year = {year} AND quarter = 'Q{quarter}'
"""
print(sql)
qt_pf = pd.read_sql(sql, conlt)
qt_pf.shape

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM qt_profits
WHERE year = 2025 AND quarter = 'Q4'

(201, 7)

In [17]:
df_merge = pd.merge(epss, qt_pf, on=["name"], suffixes=(["_e", "_q"]), how="inner")
df_merge.sample(5).style.format(format_dict)

### Delete duplicated year and quarter

In [20]:
columns = ["year_q", "quarter_q"]
epssqt_pf = df_merge.drop(columns, axis=1)
epssqt_pf.sample(5).style.format(format_dict)

In [22]:
sql = f"""
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM yr_profits 
WHERE year = {year} AND quarter = 'Q{quarter}'
"""
print(sql)
yr_pf = pd.read_sql(sql, conlt)
yr_pf.sample(5).style.format(format_dict)

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM yr_profits
WHERE year = 2025 AND quarter = 'Q4'

In [24]:
df_merge2 = pd.merge(
    epssqt_pf, yr_pf, on=["name"], suffixes=(["_q", "_y"]), how="inner"
)
df_merge2.sample(5).style.format(format_dict)

### Delete duplicated year and quarter

In [27]:
columns = ["year_e", "quarter_e"]
profits = df_merge2.drop(columns, axis=1)
profits.sample().style.format(format_dict)

### profits criteria
1. Yearly profit amount > 440 millions
2. Previous yearly gain amount > 400 millions
3. Yearly gain percent >= 10 percent
4. YoY Profit Higher

In [29]:
profits[profits["name"] == "MCS"].style.format(format_dict)

In [31]:
criteria_1 = profits.latest_amt_y > 440_000
profits.loc[criteria_1, cols].sort_values(by=["name"], ascending=True).style.format(format_dict)

In [33]:
criteria_2 = profits.previous_amt_y >= 400_000
profits.loc[criteria_2, cols].sort_values(by=["name"], ascending=True).style.format(format_dict)

In [35]:
criteria_3 = profits.inc_pct_y >= 10.00
profits.loc[criteria_3, cols].style.format(format_dict)

In [37]:
criteria_4 = (profits.q_amt > profits.y_amt)
colt = 'name q_amt y_amt inc_amt_q inc_pct_q'.split()
profits.loc[criteria_4,colt].sort_values(['inc_pct_q'],ascending=[False]).style.format(format_dict)

In [39]:
profits_criteria = criteria_1 & criteria_2 & criteria_3 & criteria_4
#profits_criteria = criteria_1 & criteria_2 
filter = profits.loc[profits_criteria]
filter.sort_values('name').style.format(format_dict)

In [41]:
columns = 'year quarter q_amt y_amt aq_amt ay_amt'.split()
pre_final = filter.drop(columns, axis=1)
pre_final.sort_values(['name'],ascending=[True]).style.format(format_dict)

In [43]:
final = pre_final.loc[:,:]
final.style.format(format_dict)

In [49]:
#final = filter.drop(colt, axis=1)
#final.style.format(format_dict)

In [45]:
final.sort_values(by=["name"], ascending=True).style.format(format_dict)

In [51]:
sql = f"""
SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p 
FROM epss A JOIN epss B ON a.name = B.name 
WHERE (A.year = {year} AND A.quarter = {quarter} 
AND B.year = {year} AND B.quarter = {quarter}-1)"""
print(sql)

SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p
FROM epss A JOIN epss B ON a.name = B.name
WHERE (A.year = 2025 AND A.quarter = 4
AND B.year = 2025 AND B.quarter = 4-1)

In [53]:
epss2 = pd.read_sql(sql, conlt)
epss2.head().style.format(format_dict)

In [55]:
df_merge3 = pd.merge(final, epss2, on=["name"], suffixes=(["_f", "_e"]), how="inner")
df_merge3.style.format(format_dict)

### The fifth criteria, added on 2022q1

In [58]:
mask = (df_merge3.q_amt_c > df_merge3.q_amt_p)
df_merge3 = df_merge3[mask]
df_merge3

,name,latest_amt_q,previous_amt_q,inc_amt_q,inc_pct_q,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,year,quarter,q_amt_c,y_amt,q_amt_p
0,SCGP,4069495,2806314,1263181,45.01,4069495,3699083,370412,10.01,2025,4,1206601,-56580,953229
1,KKP,5912913,5546534,366379,6.61,5912913,4985068,927845,18.61,2025,4,1772010,1451311,1669882
2,3BBIF,10827771,7719299,3108472,40.27,10827771,5279119,5548652,105.11,2025,4,6429421,3961184,183813
3,ADVANC,47885902,42863183,5022719,11.72,47885902,35075357,12810545,36.52,2025,4,14281630,9258911,12038861
4,BCP,2879701,679670,2200031,323.69,2879701,2184088,695613,31.85,2025,4,2216608,16577,1107896
8,DIF,13855643,868268,12987375,1495.78,13855643,656288,13199355,2011.21,2025,4,5589388,-7397987,2769459
9,NER,1884525,1848738,35787,1.94,1884525,1652466,232059,14.04,2025,4,395108,359321,326583
12,MTC,6723275,6484813,238462,3.68,6723275,5867308,855967,14.59,2025,4,1781096,1542634,1723953
13,GULF,101380618,96429425,4951193,5.13,101380618,18170334,83210284,457.95,2025,4,8851992,3900799,7274297
16,SIS,876418,843843,32575,3.86,876418,697604,178814,25.63,2025,4,264524,231949,218826
19,COM7,4063532,3880193,183339,4.72,4063532,3307162,756370,22.87,2025,4,1207698,1029675,872025
20,CENTEL,1992901,1685602,307299,18.23,1992901,1752985,239916,13.69,2025,4,974352,667053,160361
22,CPNREIT,3460976,2333575,1127401,48.31,3460976,1696069,1764907,104.06,2025,4,1484839,357438,250530
24,CPALL,28206100,28129321,76779,0.27,28206100,25345841,2860259,11.28,2025,4,7255879,7179100,6596528
27,WHA,5135026,4936500,198526,4.02,5135026,4359376,775650,17.79,2025,4,1445231,1246705,634251
29,TOA,2917013,2523302,393711,15.60,2917013,1919604,997409,51.96,2025,4,844394,450683,687726
34,THANI,1147837,955604,192233,20.12,1147837,800211,347626,43.44,2025,4,314934,122701,300620
35,VIBHA,1694894,388785,1306109,335.95,1694894,698606,996288,142.61,2025,4,1226409,-79700,226930

In [60]:
final2 = df_merge3[colu].copy()
final2.style.format(format_dict)

### If there is no record in the above statement, no need to further process

In [63]:
def better(vals):
    current, previous = vals
    if current > previous:
        return 1
    else:
        return 0

In [65]:
final2["kind"] = final2[["q_amt_c", "q_amt_p"]].apply(better, axis=1)

In [67]:
final2.kind.value_counts()

kind
1    18
Name: count, dtype: int64

In [69]:
final2["inc_amt_py"] = final2["q_amt_c"] - final2["y_amt"]
final2["inc_pct_py"] = final2["inc_amt_py"] / abs(final2["y_amt"]) * 100

final2["inc_amt_pq"] = final2["q_amt_c"] - final2["q_amt_p"]
final2["inc_pct_pq"] = final2["inc_amt_pq"] / abs(final2["q_amt_p"]) * 100

In [71]:
final2["inc_pct_py"] = final2["inc_pct_py"].replace("inf", np.nan)

In [73]:
final2["mean_pct"] = final2[
    ["inc_pct_y", "inc_pct_q", "inc_pct_py", "inc_pct_pq"]
].mean(axis=1, skipna=True)

In [75]:
final2[["name", "mean_pct"]].sort_values(by=["mean_pct"], ascending=False)

       name     mean_pct
4       BCP  3431.800198
8       DIF   946.091300
2     3BBIF   901.373991
35    VIBHA   639.444154
0      SCGP   578.539458
22  CPNREIT   240.115186
13     GULF   152.924072
20   CENTEL   146.396815
34    THANI    56.247332
29      TOA    44.424832
27      WHA    41.399565
3    ADVANC    30.279204
19     COM7    20.843187
16      SIS    16.104324
1       KKP    13.358269
9       NER    11.730508
12      MTC     9.260689
24    CPALL     5.653726

In [77]:
final2["std_pct"] = final2[["inc_pct_y", "inc_pct_q", "inc_pct_py", "inc_pct_pq"]].std(
    axis=1
)

In [79]:
final2[["name", "std_pct"]].sort_values(by=["std_pct"], ascending=True)

       name      std_pct
24    CPALL     5.788066
12      MTC     6.666059
9       NER     7.956583
1       KKP     8.204486
16      SIS     9.447133
19     COM7    14.002731
3    ADVANC    19.092616
29      TOA    32.657025
27      WHA    57.964872
34    THANI    68.809594
22  CPNREIT   203.926733
13     GULF   210.382557
20   CENTEL   241.226564
35    VIBHA   677.552714
8       DIF   956.234816
0      SCGP  1102.771316
2     3BBIF  1664.505281
4       BCP  6561.042071

In [81]:
sql = "SELECT name, id, market FROM tickers"
tickers = pd.read_sql(sql, conlt)
tickers.head().style.format(format_dict)

In [83]:
df_merge4 = pd.merge(final2, tickers, on="name", how="inner")
df_merge4.rename(columns={"id": "ticker_id"}, inplace=True)

final3 = df_merge4[colv].copy()
final3.style.format(format_dict)

In [87]:
sql = f"""
SELECT *
FROM profits
WHERE year = {year} AND quarter = {quarter}
ORDER BY name"""
print(sql)

SELECT *
FROM profits
WHERE year = 2025 AND quarter = 4
ORDER BY name

In [89]:
profits = pd.read_sql(sql, conlt)
profits.style.format(format_dict)

In [91]:
df_merge = pd.merge(
    final3, profits, on=["name", "year", "quarter"], how="outer", indicator=True
)
df_merge.sample().style.format(format_dict)

In [93]:
final4 = df_merge[df_merge["_merge"] == "left_only"]
final4

,name,year,quarter,kind_x,latest_amt_y_x,previous_amt_y_x,inc_amt_y_x,inc_pct_y_x,latest_amt_q_x,previous_amt_q_x,...,y_amt_y,inc_amt_py_y,inc_pct_py_y,q_amt_p_y,inc_amt_pq_y,inc_pct_pq_y,ticker_id_y,mean_pct_y,std_pct_y,_merge
3,CENTEL,2025,4,1,1992901,1752985,239916,13.69,1992901,1685602,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,COM7,2025,4,1,4063532,3307162,756370,22.87,4063532,3880193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5,CPALL,2025,4,1,28206100,25345841,2860259,11.28,28206100,28129321,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
6,CPNREIT,2025,4,1,3460976,1696069,1764907,104.06,3460976,2333575,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
13,SIS,2025,4,1,876418,697604,178814,25.63,876418,843843,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
14,THANI,2025,4,1,1147837,800211,347626,43.44,1147837,955604,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
15,TOA,2025,4,1,2917013,1919604,997409,51.96,2917013,2523302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
16,VIBHA,2025,4,1,1694894,698606,996288,142.61,1694894,388785,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
17,WHA,2025,4,1,5135026,4359376,775650,17.79,5135026,4936500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [95]:
final5 = final4[colw]
final5.sort_values('name')

,name,year,quarter,kind_x,latest_amt_y_x,previous_amt_y_x,inc_amt_y_x,inc_pct_y_x,latest_amt_q_x,previous_amt_q_x,...,q_amt_c_x,y_amt_x,inc_amt_py_x,inc_pct_py_x,q_amt_p_x,inc_amt_pq_x,inc_pct_pq_x,ticker_id_x,mean_pct_x,std_pct_x
3,CENTEL,2025,4,1,1992901,1752985,239916,13.69,1992901,1685602,...,974352,667053,307299,46.068154,160361,813991,507.599105,92,146.396815,241.226564
4,COM7,2025,4,1,4063532,3307162,756370,22.87,4063532,3880193,...,1207698,1029675,178023,17.289242,872025,335673,38.493506,114,20.843187,14.002731
5,CPALL,2025,4,1,28206100,25345841,2860259,11.28,28206100,28129321,...,7255879,7179100,76779,1.069479,6596528,659351,9.995425,116,5.653726,5.788066
6,CPNREIT,2025,4,1,3460976,1696069,1764907,104.06,3460976,2333575,...,1484839,357438,1127401,315.411624,250530,1234309,492.679120,647,240.115186,203.926733
13,SIS,2025,4,1,876418,697604,178814,25.63,876418,843843,...,264524,231949,32575,14.044036,218826,45698,20.883259,449,16.104324,9.447133
14,THANI,2025,4,1,1147837,800211,347626,43.44,1147837,955604,...,314934,122701,192233,156.667835,300620,14314,4.761493,522,56.247332,68.809594
15,TOA,2025,4,1,2917013,1919604,997409,51.96,2917013,2523302,...,844394,450683,393711,87.358742,687726,156668,22.780584,645,44.424832,32.657025
16,VIBHA,2025,4,1,1694894,698606,996288,142.61,1694894,388785,...,1226409,-79700,1306109,1638.781681,226930,999479,440.434936,610,639.444154,677.552714
17,WHA,2025,4,1,5135026,4359376,775650,17.79,5135026,4936500,...,1445231,1246705,198526,15.924056,634251,810980,127.864205,619,41.399565,57.964872

In [97]:
rcds = final5.values.tolist()
len(rcds)

9

In [101]:
sql = f"""
SELECT *
FROM profits
WHERE year = {year} AND quarter = {quarter}
ORDER BY name"""
print(sql)
profits = pd.read_sql(sql, conlt)
profits.head().style.format(format_dict)

SELECT *
FROM profits
WHERE year = 2025 AND quarter = 4
ORDER BY name

In [103]:
for rcd in rcds:
    print(rcd)

['CENTEL', 2025, 4, 1, 1992901, 1752985, 239916, 13.69, 1992901, 1685602, 307299, 18.23, 974352, 667053, 307299, 46.06815350504383, 160361, 813991, 507.59910452042584, 92, 146.39681450636743, 241.22656396484436]
['COM7', 2025, 4, 1, 4063532, 3307162, 756370, 22.87, 4063532, 3880193, 183339, 4.72, 1207698, 1029675, 178023, 17.28924175103795, 872025, 335673, 38.49350649350649, 114, 20.84318706113611, 14.002731103007644]
['CPALL', 2025, 4, 1, 28206100, 25345841, 2860259, 11.28, 28206100, 28129321, 76779, 0.27, 7255879, 7179100, 76779, 1.069479461213801, 6596528, 659351, 9.995424865929472, 116, 5.653726081785818, 5.7880661749539595]
['CPNREIT', 2025, 4, 1, 3460976, 1696069, 1764907, 104.06, 3460976, 2333575, 1127401, 48.31, 1484839, 357438, 1127401, 315.41162383406356, 250530, 1234309, 492.67912026503814, 647, 240.11518602477543, 203.92673313057207]
['SIS', 2025, 4, 1, 876418, 697604, 178814, 25.63, 876418, 843843, 32575, 3.86, 264524, 231949, 32575, 14.044035542295935, 218826, 45698, 20.88325884492702, 449, 16.104323596805738, 9.447133255737029]
['THANI', 2025, 4, 1, 1147837, 800211, 347626, 43.44, 1147837, 955604, 192233, 20.12, 314934, 122701, 192233, 156.66783481797216, 300620, 14314, 4.761492914643071, 522, 56.24733193315381, 68.80959449314722]
['TOA', 2025, 4, 1, 2917013, 1919604, 997409, 51.96, 2917013, 2523302, 393711, 15.6, 844394, 450683, 393711, 87.35874217576433, 687726, 156668, 22.7805841279812, 645, 44.42483157593639, 32.657024795809946]
['VIBHA', 2025, 4, 1, 1694894, 698606, 996288, 142.61, 1694894, 388785, 1306109, 335.95, 1226409, -79700, 1306109, 1638.7816813048933, 226930, 999479, 440.43493588331205, 610, 639.4441542970513, 677.5527139316283]
['WHA', 2025, 4, 1, 5135026, 4359376, 775650, 17.79, 5135026, 4936500, 198526, 4.02, 1445231, 1246705, 198526, 15.924055811118107, 634251, 810980, 127.86420518059884, 619, 41.39956524792924, 57.96487157198943]

In [105]:
# Define SQL statement using named placeholders
sql = text("""
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)
""")

# Convert list data to dictionaries for named parameters
columns = [
    "name", "year", "quarter", "kind",
    "latest_amt_y", "previous_amt_y", "inc_amt_y", "inc_pct_y",
    "latest_amt_q", "previous_amt_q", "inc_amt_q", "inc_pct_q",
    "q_amt_c", "y_amt", "inc_amt_py", "inc_pct_py",
    "q_amt_p", "inc_amt_pq", "inc_pct_pq",
    "ticker_id", "mean_pct", "std_pct"
]

records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]

In [107]:
try:
    # Execute the SQL statement within the existing transaction
    conlt.execute(sql, records_dicts)  # Bulk insert using named parameters
    print("Data inserted successfully!")
except Exception as e:
    print("Error inserting data:", e)
    conlt.rollback()  # Rollback the transaction in case of error

Data inserted successfully!

In [109]:
sql = f"""
SELECT *
FROM profits
WHERE year = {year} AND quarter = {quarter}
ORDER BY name"""
profits = pd.read_sql(sql, conlt)
profits.head().style.format(format_dict)

### End of Create Data

In [112]:
sql = """
SELECT name, market
FROM tickers"""
tickers = pd.read_sql(sql, conlt)
tickers.shape

(394, 2)

In [114]:
df_merge = pd.merge(final5, tickers, on='name', how='inner')
df_merge[['name','market']].sort_values('name').style.format(format_dict)

### Insert Profits from PortLt to PortMy

In [117]:
stock_list = final5['name'].unique().tolist()
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

CENTEL','COM7','CPALL','CPNREIT','SIS','THANI','TOA','VIBHA','WHA

In [119]:
#quarter = 4
sql = f"""
SELECT * 
FROM profits 
WHERE name IN ('{stock_list_str}') AND year = {year} AND quarter = {quarter}"""
print(sql)

SELECT *
FROM profits
WHERE name IN ('CENTEL','COM7','CPALL','CPNREIT','SIS','THANI','TOA','VIBHA','WHA') AND year = 2025 AND quarter = 4

In [121]:
profits_inp = pd.read_sql(sql, conlt)
profits_inp.style.format(format_dict)

In [123]:
profits_inp.sort_values(by=["kind", "name"], ascending=[True, True]).style.format(format_dict)

In [125]:
rcds = profits_inp.values.tolist()
len(rcds)

9

In [127]:
for rcd in rcds:
    print(rcd)

[2851, 'CENTEL', 2025, 4, 1, 1992901, 1752985, 239916, 13.69, 1992901, 1685602, 307299, 18.23, 974352, 667053, 307299, 46.06815350504383, 160361, 813991, 507.59910452042584, 92, 146.39681450636743, 241.22656396484436]
[2852, 'COM7', 2025, 4, 1, 4063532, 3307162, 756370, 22.87, 4063532, 3880193, 183339, 4.72, 1207698, 1029675, 178023, 17.28924175103795, 872025, 335673, 38.49350649350649, 114, 20.84318706113611, 14.002731103007644]
[2853, 'CPALL', 2025, 4, 1, 28206100, 25345841, 2860259, 11.28, 28206100, 28129321, 76779, 0.27, 7255879, 7179100, 76779, 1.069479461213801, 6596528, 659351, 9.995424865929472, 116, 5.653726081785818, 5.7880661749539595]
[2854, 'CPNREIT', 2025, 4, 1, 3460976, 1696069, 1764907, 104.06, 3460976, 2333575, 1127401, 48.31, 1484839, 357438, 1127401, 315.41162383406356, 250530, 1234309, 492.67912026503814, 647, 240.11518602477543, 203.92673313057207]
[2855, 'SIS', 2025, 4, 1, 876418, 697604, 178814, 25.63, 876418, 843843, 32575, 3.86, 264524, 231949, 32575, 14.044035542295935, 218826, 45698, 20.88325884492702, 449, 16.104323596805738, 9.447133255737029]
[2856, 'THANI', 2025, 4, 1, 1147837, 800211, 347626, 43.44, 1147837, 955604, 192233, 20.12, 314934, 122701, 192233, 156.66783481797216, 300620, 14314, 4.761492914643071, 522, 56.24733193315381, 68.80959449314722]
[2857, 'TOA', 2025, 4, 1, 2917013, 1919604, 997409, 51.96, 2917013, 2523302, 393711, 15.6, 844394, 450683, 393711, 87.35874217576433, 687726, 156668, 22.7805841279812, 645, 44.42483157593639, 32.657024795809946]
[2858, 'VIBHA', 2025, 4, 1, 1694894, 698606, 996288, 142.61, 1694894, 388785, 1306109, 335.95, 1226409, -79700, 1306109, 1638.7816813048933, 226930, 999479, 440.43493588331205, 610, 639.4441542970513, 677.5527139316283]
[2859, 'WHA', 2025, 4, 1, 5135026, 4359376, 775650, 17.79, 5135026, 4936500, 198526, 4.02, 1445231, 1246705, 198526, 15.924055811118107, 634251, 810980, 127.86420518059884, 619, 41.39956524792924, 57.96487157198943]

In [129]:
# Define SQL statement using named placeholders
sql = text("""
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)
""")

# Convert list data to dictionaries for named parameters
columns = [
    "name", "year", "quarter", "kind",
    "latest_amt_y", "previous_amt_y", "inc_amt_y", "inc_pct_y",
    "latest_amt_q", "previous_amt_q", "inc_amt_q", "inc_pct_q",
    "q_amt_c", "y_amt", "inc_amt_py", "inc_pct_py",
    "q_amt_p", "inc_amt_pq", "inc_pct_pq",
    "ticker_id", "mean_pct", "std_pct"
]

records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]

# Insert data using transactions
try:
    with conmy.begin():  # Transaction block
        conmy.execute(sql, records_dicts)  # Bulk insert using named parameters
    print("Data inserted successfully!")
except Exception as e:
    print("Error inserting data:", e)
finally:
    conmy.commit()

Error inserting data: (sqlite3.IntegrityError) UNIQUE constraint failed: profits.name, profits.year, profits.quarter
[SQL:
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (?, ?, ?, ?,
?, ?, ?, ?,
?, ?, ?, ?,
?, ?, ?, ?,
?, ?, ?,
?, ?, ?)
]
[parameters: [(2851, 'CENTEL', 2025, 4, 1, 1992901, 1752985, 239916, 13.69, 1992901, 1685602, 307299, 18.23, 974352, 667053, 307299, 46.06815350504383, 160361, 813991, 507.59910452042584, 92, 146.39681450636743), (2852, 'COM7', 2025, 4, 1, 4063532, 3307162, 756370, 22.87, 4063532, 3880193, 183339, 4.72, 1207698, 1029675, 178023, 17.28924175103795, 872025, 335673, 38.49350649350649, 114, 20.84318706113611), (2853, 'CPALL', 2025, 4, 1, 28206100, 25345841, 2860259, 11.28, 28206100, 28129321, 76779, 0.27, 7255879, 7179100, 76779, 1.069479461213801, 6596528, 659351, 9.995424865929472, 116, 5.653726081785818), (2854, 'CPNREIT', 2025, 4, 1, 3460976, 1696069, 1764907, 104.06, 3460976, 2333575, 1127401, 48.31, 1484839, 357438, 1127401, 315.41162383406356, 250530, 1234309, 492.67912026503814, 647, 240.11518602477543), (2855, 'SIS', 2025, 4, 1, 876418, 697604, 178814, 25.63, 876418, 843843, 32575, 3.86, 264524, 231949, 32575, 14.044035542295935, 218826, 45698, 20.88325884492702, 449, 16.104323596805738), (2856, 'THANI', 2025, 4, 1, 1147837, 800211, 347626, 43.44, 1147837, 955604, 192233, 20.12, 314934, 122701, 192233, 156.66783481797216, 300620, 14314, 4.761492914643071, 522, 56.24733193315381), (2857, 'TOA', 2025, 4, 1, 2917013, 1919604, 997409, 51.96, 2917013, 2523302, 393711, 15.6, 844394, 450683, 393711, 87.35874217576433, 687726, 156668, 22.7805841279812, 645, 44.42483157593639), (2858, 'VIBHA', 2025, 4, 1, 1694894, 698606, 996288, 142.61, 1694894, 388785, 1306109, 335.95, 1226409, -79700, 1306109, 1638.7816813048933, 226930, 999479, 440.43493588331205, 610, 639.4441542970513), (2859, 'WHA', 2025, 4, 1, 5135026, 4359376, 775650, 17.79, 5135026, 4936500, 198526, 4.02, 1445231, 1246705, 198526, 15.924055811118107, 634251, 810980, 127.86420518059884, 619, 41.39956524792924)]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [131]:
sql = """
SELECT name, year, quarter 
FROM profits
ORDER BY name
"""
df_tmp = pd.read_sql(sql, conmy)
df_tmp.set_index("name", inplace=True)
df_tmp.index

Index(['2842', '2843', '2844', '2845', '2846', '2847', '2848', '2849', '2850',
       '2851', '2851', '2852', '2853', '2854', '2855', '2856', '3BBIF',
       'ADVANC', 'BCP', 'DIF', 'FPT', 'GULF', 'KKP', 'MTC', 'NER', 'SCGP'],
      dtype='object', name='name')

### After call 450-Export-to-PortPg

In [134]:
sql = f"""
SELECT * 
FROM profits 
WHERE name IN ('{stock_list_str}') AND year = {year} AND quarter = {quarter}"""
print(sql)

SELECT *
FROM profits
WHERE name IN ('CENTEL','COM7','CPALL','CPNREIT','SIS','THANI','TOA','VIBHA','WHA') AND year = 2025 AND quarter = 4

In [136]:
profits_inp = pd.read_sql(sql, conpg)
profits_inp[['name','ticker_id']].sort_values(by=[ "name"], ascending=[True])

Empty DataFrame
Columns: [name, ticker_id]
Index: []

In [138]:
sql = f"""
SELECT * 
FROM tickers
WHERE name IN ('{stock_list_str}')
ORDER BY name"""
print(sql)

SELECT *
FROM tickers
WHERE name IN ('CENTEL','COM7','CPALL','CPNREIT','SIS','THANI','TOA','VIBHA','WHA')
ORDER BY name

In [140]:
tickers = pd.read_sql(sql, conpg)
tickers[['name','id','market']].sort_values(by=[ "name"], ascending=[True])

      name   id                    market
0   CENTEL   94  SET100 / SETTHSI / SETWB
1     COM7  118  SET100 / SETTHSI / SETWB
2    CPALL  120   SET50 / SETTHSI / SETWB
3  CPNREIT  127                       SET
4      SIS  455                      sSET
5    THANI  528  SET100 / SETHD / SETTHSI
6      TOA  562                   SETTHSI
7    VIBHA  619                     SETWB
8      WHA  628  SET100 / SETHD / SETTHSI

### Additional process to find stocks in SET50 & SET100

In [143]:
stock_list = epss['name'].unique().tolist()
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

SCGP','SCC','MST','KBANK','SCB','KTB','TTB','BBL','KKP','DCC','KCE','MBAX','OR','GGC','PTTGC','PTTEP','3BBIF','ADVANC','BCP','BCPG','SPRC','PLANB','TOP','DRT','SINGER','JMART','JMT','SVI','GPSC','INOX','SMPC','ASK','DELTA','PSL','EGATIF','TTLPF','MINT','LANNA','DIF','STA','PTT','NER','RCL','BLA','AIMIRT','CBG','DOHOME','MAJOR','TMT','WORK','TPIPL','SCCC','TIPCO','LIT','PDG','ASIAN','BEC','TCAP','PREB','ASW','STGT','TASCO','TPIPP','MTC','IRPC','GULF','SUPEREIF','MCS','SYNEX','WHAIR','WHART','THG','SIS','CKP','CPN','CPAXT','PCSGH','SJWD','HMPRO','TKS','QH','COM7','BJC','SPCG','SC','CENTEL','DCON','SPALI','BGRIM','MEGA','TTW','TKN','PTG','CPNREIT','RJH','SGP','BDMS','WHAUP','OSP','TK','BEM','PAP','CPALL','CPF','AWC','AH','BCH','CK','BAM','TTA','RATCH','PRM','M','ILM','BA','ASP','LPN','AP','WICE','BEAUTY','FSMART','EASTW','WHA','BPP','BANPU','VNG','SAPPE','III','SENA','TOA','TVO','ORI','IVL','ACE','AIE','AIT','AJ','AMATA','ANAN','BAY','BE8','BGC','BH','BKIH','CHG','CPNCG','CRC','EA','EGCO','FORTH','GC','GFPT','GLOBAL','GRAMMY','RS','S11','SAT','GUNKUL','HANA','HFT','HTC','ICHI','IMH','IP','KGI','LALIN','LH','LPH','NOBLE','ONEE','POPF','PSH','RBF','ROJNA','SAWAD','SIRI','SKN','SKR','SNC','SPC','SPRIME','SSP','SUPER','TFG','THANI','TIDLOR','TIPH','TQM','TRUE','TSE','TU','TYCN','UTP','VIBHA

In [145]:
sql = f"""
SELECT * 
FROM tickers
WHERE name IN ('{stock_list_str}')
ORDER BY name"""
print(sql)

SELECT *
FROM tickers
WHERE name IN ('SCGP','SCC','MST','KBANK','SCB','KTB','TTB','BBL','KKP','DCC','KCE','MBAX','OR','GGC','PTTGC','PTTEP','3BBIF','ADVANC','BCP','BCPG','SPRC','PLANB','TOP','DRT','SINGER','JMART','JMT','SVI','GPSC','INOX','SMPC','ASK','DELTA','PSL','EGATIF','TTLPF','MINT','LANNA','DIF','STA','PTT','NER','RCL','BLA','AIMIRT','CBG','DOHOME','MAJOR','TMT','WORK','TPIPL','SCCC','TIPCO','LIT','PDG','ASIAN','BEC','TCAP','PREB','ASW','STGT','TASCO','TPIPP','MTC','IRPC','GULF','SUPEREIF','MCS','SYNEX','WHAIR','WHART','THG','SIS','CKP','CPN','CPAXT','PCSGH','SJWD','HMPRO','TKS','QH','COM7','BJC','SPCG','SC','CENTEL','DCON','SPALI','BGRIM','MEGA','TTW','TKN','PTG','CPNREIT','RJH','SGP','BDMS','WHAUP','OSP','TK','BEM','PAP','CPALL','CPF','AWC','AH','BCH','CK','BAM','TTA','RATCH','PRM','M','ILM','BA','ASP','LPN','AP','WICE','BEAUTY','FSMART','EASTW','WHA','BPP','BANPU','VNG','SAPPE','III','SENA','TOA','TVO','ORI','IVL','ACE','AIE','AIT','AJ','AMATA','ANAN','BAY','BE8','BGC','BH','BKIH','CHG','CPNCG','CRC','EA','EGCO','FORTH','GC','GFPT','GLOBAL','GRAMMY','RS','S11','SAT','GUNKUL','HANA','HFT','HTC','ICHI','IMH','IP','KGI','LALIN','LH','LPH','NOBLE','ONEE','POPF','PSH','RBF','ROJNA','SAWAD','SIRI','SKN','SKR','SNC','SPC','SPRIME','SSP','SUPER','TFG','THANI','TIDLOR','TIPH','TQM','TRUE','TSE','TU','TYCN','UTP','VIBHA')
ORDER BY name

In [147]:
df = pd.read_sql(sql, conlt)
df

,id,name,full_name,sector,subsector,market,website,created_at,updated_at
0,234,3BBIF,JASMINE BROADBAND INTERNET INFRASTRUCTURE FUND,Technology,Information & Communication Technology,SET,www.jas-if.com,2017-07-23 06:31:17.769146,2019-03-03 03:43:41.108383
1,698,ACE,ABSOLUTE CLEAN ENERGY PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,SET100,www.ace-energy.co.th,2019-11-19 07:11:16.920183,2021-01-26 15:41:59.109472
2,6,ADVANC,ADVANCED INFO SERVICE PUBLIC COMPANY LIMITED,Technology,Information & Communication Technology,SET50 / SETHD / SETTHSI,investor.ais.co.th,2017-07-23 06:30:43.494530,2021-07-07 03:34:13.518706
3,9,AH,AAPICO HITECH PUBLIC COMPANY LIMITED,Industrials,Automotive,sSET / SETTHSI,www.aapico.com,2017-07-23 06:30:43.935758,2021-07-07 03:34:13.530450
4,720,AIE,AI ENERGY PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,sSET,www.aienergy.co.th,2021-02-21 16:12:17.821078,2022-01-15 03:54:12.607554
...,...,...,...,...,...,...,...,...,...
189,211,WHAIR,HEMARAJ LEASEHOLD REAL ESTATE INVESTMENT TRUST,Property & Construction,Property Fund & REITs,SET,www.hemarajreit.com,2017-07-23 06:31:14.694180,2017-07-23 06:31:14.694180
190,622,WHART,WHA PREMIUM GROWTH FREEHOLD AND LEASEHOLD REAL...,Property & Construction,Property Fund & REITs,SET,www.whareit.com,2017-07-23 06:32:16.019967,2017-07-23 06:32:16.019967
191,623,WHAUP,WHA UTILITIES AND POWER PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,sSET / SETTHSI,www.wha-up.com,2017-07-23 06:32:16.177824,2021-07-07 03:34:14.179836
192,624,WICE,WICE LOGISTICS PUBLIC COMPANY LIMITED,Services,Transportation & Logistics,sSET,www.wice.co.th,2017-07-23 06:32:16.329569,2021-01-26 15:42:00.303670
193,628,WORK,WORKPOINT ENTERTAINMENT PUBLIC COMPANY LIMITED,Services,Media & Publishing,SET,www.workpoint.co.th,2017-07-23 06:32:16.937561,2022-01-15 03:54:13.274614

In [149]:
conlt.commit()
conlt.close()

In [151]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y:%m:%d %H:%M:%S")
print(formatted_time)

2026:03:12 14:18:15