In [1]:
import numpy as np
import pandas as pd
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

year = 2025
quarter = 4
select_date = date.today()
select_date = select_date.strftime("%Y-%m-%d")
print(select_date)

2026-03-02

In [3]:
select_date = date(2026, 2, 24)
select_date = select_date.strftime("%Y-%m-%d")
print(select_date)

2026-02-24

In [5]:
cols = "name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y".split()
colt = "year quarter q_amt y_amt aq_amt ay_amt".split()
colu = 'name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt q_amt_p'.split() 
colv = 'name year quarter kind latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt \
        inc_amt_py inc_pct_py q_amt_p inc_amt_pq inc_pct_pq \
        ticker_id mean_pct std_pct'.split()
colw = 'name year quarter kind_x latest_amt_y_x previous_amt_y_x inc_amt_y_x inc_pct_y_x \
        latest_amt_q_x previous_amt_q_x inc_amt_q_x inc_pct_q_x q_amt_c_x y_amt_x \
        inc_amt_py_x inc_pct_py_x q_amt_p_x inc_amt_pq_x inc_pct_pq_x \
        ticker_id_x mean_pct_x std_pct_x'.split()

format_dict = {
    'q_amt': '{:,}',
    'y_amt': '{:,}',
    'yoy_gain': '{:,}',
    'q_amt_c': '{:,}',
    'q_amt_p': '{:,}',
    'aq_amt': '{:,}',
    'ay_amt': '{:,}',
    'acc_gain': '{:,}',
    'latest_amt': '{:,}',
    'previous_amt': '{:,}',
    'inc_amt': '{:,}',
    'inc_amt_pq': '{:,}',
    'inc_amt_py': '{:,}',    
    'latest_amt_q': '{:,}',
    'previous_amt_q': '{:,}',
    'inc_amt_q': '{:,}',
    'latest_amt_y': '{:,}',
    'previous_amt_y': '{:,}',
    'inc_amt_y': '{:,}',
    'kind_x': '{:,}',
    'inc_pct': '{:.2f}%',
    'inc_pct_q': '{:.2f}%',
    'inc_pct_y': '{:.2f}%',
    'inc_pct_pq': '{:.2f}%',
    'inc_pct_py': '{:.2f}%',   
    'mean_pct': '{:.2f}%',
    'std_pct': '{:.2f}%',      
}

### Process for specified stocks

In [8]:
names = """
IP
""".split()
names

['IP']

In [10]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'IP'"

In [12]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = %s AND quarter = %s
AND name IN (%s)
"""
sql = sql % (year, quarter, in_p)
epss = pd.read_sql(sql, conlt)
epss.style.format(format_dict)

### End of Process for specified stocks

In [15]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = %s AND quarter = %s
AND publish_date >= '%s'
"""
sql = sql % (year, quarter, select_date)
print(sql)
epss = pd.read_sql(sql, conlt)
#epss.style.format(format_dict)
epss.shape

SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt
FROM epss
WHERE year = 2025 AND quarter = 4
AND publish_date >= '2026-02-24'

(57, 7)

### End of Normal Process

In [18]:
sql = """
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM qt_profits 
WHERE year = %s AND quarter = 'Q%s'
"""
sql = sql % (year, quarter)
print(sql)
qt_pf = pd.read_sql(sql, conlt)
qt_pf.shape

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM qt_profits
WHERE year = 2025 AND quarter = 'Q4'

(141, 7)

In [20]:
df_merge = pd.merge(epss, qt_pf, on=["name"], suffixes=(["_e", "_q"]), how="inner")
df_merge.sample(5).style.format(format_dict)

### Delete duplicated year and quarter

In [23]:
columns = ["year_q", "quarter_q"]
epssqt_pf = df_merge.drop(columns, axis=1)
epssqt_pf.sample(5).style.format(format_dict)

In [25]:
sql = """
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM yr_profits 
WHERE year = %s AND quarter = 'Q%s'
"""
sql = sql % (year, quarter)
print(sql)
yr_pf = pd.read_sql(sql, conlt)
yr_pf.sample(5).style.format(format_dict)

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM yr_profits
WHERE year = 2025 AND quarter = 'Q4'

In [27]:
df_merge2 = pd.merge(
    epssqt_pf, yr_pf, on=["name"], suffixes=(["_q", "_y"]), how="inner"
)
df_merge2.sample(5).style.format(format_dict)

### Delete duplicated year and quarter

In [30]:
columns = ["year_e", "quarter_e"]
profits = df_merge2.drop(columns, axis=1)
profits.sample().style.format(format_dict)

### profits criteria
1. Yearly profit amount > 440 millions
2. Previous yearly gain amount > 400 millions
3. Yearly gain percent >= 10 percent
4. YoY Profit Higher

In [33]:
profits[profits["name"] == "MCS"].style.format(format_dict)

In [35]:
criteria_1 = profits.latest_amt_y > 440_000
profits.loc[criteria_1, cols].sort_values(by=["name"], ascending=True).style.format(format_dict)

In [37]:
criteria_2 = profits.previous_amt_y >= 400_000
profits.loc[criteria_2, cols].sort_values(by=["name"], ascending=True).style.format(format_dict)

In [39]:
criteria_3 = profits.inc_pct_y >= 10.00
profits.loc[criteria_3, cols].style.format(format_dict)

In [41]:
criteria_4 = (profits.q_amt > profits.y_amt)
colt = 'name q_amt y_amt inc_amt_q inc_pct_q'.split()
profits.loc[criteria_4,colt].sort_values(['inc_pct_q'],ascending=[False]).style.format(format_dict)

In [43]:
profits_criteria = criteria_1 & criteria_2 & criteria_3 & criteria_4
#profits_criteria = criteria_1 & criteria_2 
filter = profits.loc[profits_criteria]
filter.sort_values('name').style.format(format_dict)

In [45]:
columns = 'year quarter q_amt y_amt aq_amt ay_amt'.split()
pre_final = filter.drop(columns, axis=1)
pre_final.sort_values(['name'],ascending=[True]).style.format(format_dict)

In [47]:
final = pre_final.loc[:,:]
final.style.format(format_dict)

In [49]:
#final = filter.drop(colt, axis=1)
#final.style.format(format_dict)

In [51]:
final.sort_values(by=["name"], ascending=True).style.format(format_dict)

In [53]:
sql = """
SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p 
FROM epss A JOIN epss B ON a.name = B.name 
WHERE A.year = %s AND A.quarter = %s 
AND B.year = %s AND B.quarter = (%s-1)"""
sql = sql % (year, quarter, year, quarter)
print(sql)

SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p
FROM epss A JOIN epss B ON a.name = B.name
WHERE A.year = 2025 AND A.quarter = 4
AND B.year = 2025 AND B.quarter = (4-1)

In [55]:
epss2 = pd.read_sql(sql, conlt)
epss2.head().style.format(format_dict)

In [57]:
df_merge3 = pd.merge(final, epss2, on=["name"], suffixes=(["_f", "_e"]), how="inner")
df_merge3.style.format(format_dict)

### The fifth criteria, added on 2022q1

In [60]:
mask = (df_merge3.q_amt_c > df_merge3.q_amt_p)
df_merge3 = df_merge3[mask]
df_merge3

,name,latest_amt_q,previous_amt_q,inc_amt_q,inc_pct_q,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,year,quarter,q_amt_c,y_amt,q_amt_p
1,COM7,4063532,3880193,183339,4.72,4063532,3307162,756370,22.87,2025,4,1207698,1029675,872025
2,CENTEL,1992901,1685602,307299,18.23,1992901,1752985,239916,13.69,2025,4,974352,667053,160361
4,CPNREIT,3460976,2333575,1127401,48.31,3460976,1696069,1764907,104.06,2025,4,1484839,357438,250530
6,CPALL,28206100,28129321,76779,0.27,28206100,25345841,2860259,11.28,2025,4,7255879,7179100,6596528
9,WHA,5135026,4936500,198526,4.02,5135026,4359376,775650,17.79,2025,4,1445231,1246705,634251
11,TOA,2917013,2523302,393711,15.60,2917013,1919604,997409,51.96,2025,4,844394,450683,687726

In [62]:
final2 = df_merge3[colu].copy()
final2.style.format(format_dict)

### If there is no record in the above statement, no need to further process

In [65]:
def better(vals):
    current, previous = vals
    if current > previous:
        return 1
    else:
        return 0

In [67]:
final2["kind"] = final2[["q_amt_c", "q_amt_p"]].apply(better, axis=1)

In [69]:
final2.kind.value_counts()

kind
1    6
Name: count, dtype: int64

In [71]:
final2["inc_amt_py"] = final2["q_amt_c"] - final2["y_amt"]
final2["inc_pct_py"] = final2["inc_amt_py"] / abs(final2["y_amt"]) * 100

final2["inc_amt_pq"] = final2["q_amt_c"] - final2["q_amt_p"]
final2["inc_pct_pq"] = final2["inc_amt_pq"] / abs(final2["q_amt_p"]) * 100

In [73]:
final2["inc_pct_py"] = final2["inc_pct_py"].replace("inf", np.nan)

In [75]:
final2["mean_pct"] = final2[
    ["inc_pct_y", "inc_pct_q", "inc_pct_py", "inc_pct_pq"]
].mean(axis=1, skipna=True)

In [77]:
final2[["name", "mean_pct"]].sort_values(by=["mean_pct"], ascending=False)

       name    mean_pct
4   CPNREIT  240.115186
2    CENTEL  146.396815
11      TOA   44.424832
9       WHA   41.399565
1      COM7   20.843187
6     CPALL    5.653726

In [79]:
final2["std_pct"] = final2[["inc_pct_y", "inc_pct_q", "inc_pct_py", "inc_pct_pq"]].std(
    axis=1
)

In [81]:
final2[["name", "std_pct"]].sort_values(by=["std_pct"], ascending=True)

       name     std_pct
6     CPALL    5.788066
1      COM7   14.002731
11      TOA   32.657025
9       WHA   57.964872
4   CPNREIT  203.926733
2    CENTEL  241.226564

In [83]:
sql = "SELECT name, id, market FROM tickers"
tickers = pd.read_sql(sql, conlt)
tickers.head().style.format(format_dict)

In [85]:
df_merge4 = pd.merge(final2, tickers, on="name", how="inner")
df_merge4.rename(columns={"id": "ticker_id"}, inplace=True)

final3 = df_merge4[colv].copy()
final3.style.format(format_dict)

In [87]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
print(sql)

SELECT *
FROM profits
WHERE year = 2025 AND quarter = 4
ORDER BY name

In [89]:
profits = pd.read_sql(sql, conlt)
profits.style.format(format_dict)

In [91]:
df_merge = pd.merge(
    final3, profits, on=["name", "year", "quarter"], how="outer", indicator=True
)
df_merge.sample().style.format(format_dict)

In [93]:
final4 = df_merge[df_merge["_merge"] == "left_only"]
final4

,name,year,quarter,kind_x,latest_amt_y_x,previous_amt_y_x,inc_amt_y_x,inc_pct_y_x,latest_amt_q_x,previous_amt_q_x,...,y_amt_y,inc_amt_py_y,inc_pct_py_y,q_amt_p_y,inc_amt_pq_y,inc_pct_pq_y,ticker_id_y,mean_pct_y,std_pct_y,_merge
3,CENTEL,2025,4,1.0,1992901.0,1752985.0,239916.0,13.69,1992901.0,1685602.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,COM7,2025,4,1.0,4063532.0,3307162.0,756370.0,22.87,4063532.0,3880193.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5,CPALL,2025,4,1.0,28206100.0,25345841.0,2860259.0,11.28,28206100.0,28129321.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
6,CPNREIT,2025,4,1.0,3460976.0,1696069.0,1764907.0,104.06,3460976.0,2333575.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
13,TOA,2025,4,1.0,2917013.0,1919604.0,997409.0,51.96,2917013.0,2523302.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
14,WHA,2025,4,1.0,5135026.0,4359376.0,775650.0,17.79,5135026.0,4936500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [95]:
final5 = final4[colw]
final5.sort_values('name')

,name,year,quarter,kind_x,latest_amt_y_x,previous_amt_y_x,inc_amt_y_x,inc_pct_y_x,latest_amt_q_x,previous_amt_q_x,...,q_amt_c_x,y_amt_x,inc_amt_py_x,inc_pct_py_x,q_amt_p_x,inc_amt_pq_x,inc_pct_pq_x,ticker_id_x,mean_pct_x,std_pct_x
3,CENTEL,2025,4,1.0,1992901.0,1752985.0,239916.0,13.69,1992901.0,1685602.0,...,974352.0,667053.0,307299.0,46.068154,160361.0,813991.0,507.599105,92.0,146.396815,241.226564
4,COM7,2025,4,1.0,4063532.0,3307162.0,756370.0,22.87,4063532.0,3880193.0,...,1207698.0,1029675.0,178023.0,17.289242,872025.0,335673.0,38.493506,114.0,20.843187,14.002731
5,CPALL,2025,4,1.0,28206100.0,25345841.0,2860259.0,11.28,28206100.0,28129321.0,...,7255879.0,7179100.0,76779.0,1.069479,6596528.0,659351.0,9.995425,116.0,5.653726,5.788066
6,CPNREIT,2025,4,1.0,3460976.0,1696069.0,1764907.0,104.06,3460976.0,2333575.0,...,1484839.0,357438.0,1127401.0,315.411624,250530.0,1234309.0,492.679120,647.0,240.115186,203.926733
13,TOA,2025,4,1.0,2917013.0,1919604.0,997409.0,51.96,2917013.0,2523302.0,...,844394.0,450683.0,393711.0,87.358742,687726.0,156668.0,22.780584,645.0,44.424832,32.657025
14,WHA,2025,4,1.0,5135026.0,4359376.0,775650.0,17.79,5135026.0,4936500.0,...,1445231.0,1246705.0,198526.0,15.924056,634251.0,810980.0,127.864205,619.0,41.399565,57.964872

In [97]:
rcds = final5.values.tolist()
len(rcds)

6

In [99]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
print(sql)
profits = pd.read_sql(sql, conlt)
profits.head().style.format(format_dict)

SELECT *
FROM profits
WHERE year = 2025 AND quarter = 4
ORDER BY name

In [101]:
for rcd in rcds:
    print(rcd)

['CENTEL', 2025, 4, 1.0, 1992901.0, 1752985.0, 239916.0, 13.69, 1992901.0, 1685602.0, 307299.0, 18.23, 974352.0, 667053.0, 307299.0, 46.06815350504383, 160361.0, 813991.0, 507.59910452042584, 92.0, 146.39681450636743, 241.22656396484436]
['COM7', 2025, 4, 1.0, 4063532.0, 3307162.0, 756370.0, 22.87, 4063532.0, 3880193.0, 183339.0, 4.72, 1207698.0, 1029675.0, 178023.0, 17.28924175103795, 872025.0, 335673.0, 38.49350649350649, 114.0, 20.84318706113611, 14.002731103007644]
['CPALL', 2025, 4, 1.0, 28206100.0, 25345841.0, 2860259.0, 11.28, 28206100.0, 28129321.0, 76779.0, 0.27, 7255879.0, 7179100.0, 76779.0, 1.069479461213801, 6596528.0, 659351.0, 9.995424865929472, 116.0, 5.653726081785818, 5.7880661749539595]
['CPNREIT', 2025, 4, 1.0, 3460976.0, 1696069.0, 1764907.0, 104.06, 3460976.0, 2333575.0, 1127401.0, 48.31, 1484839.0, 357438.0, 1127401.0, 315.41162383406356, 250530.0, 1234309.0, 492.67912026503814, 647.0, 240.11518602477543, 203.92673313057207]
['TOA', 2025, 4, 1.0, 2917013.0, 1919604.0, 997409.0, 51.96, 2917013.0, 2523302.0, 393711.0, 15.6, 844394.0, 450683.0, 393711.0, 87.35874217576433, 687726.0, 156668.0, 22.7805841279812, 645.0, 44.42483157593639, 32.657024795809946]
['WHA', 2025, 4, 1.0, 5135026.0, 4359376.0, 775650.0, 17.79, 5135026.0, 4936500.0, 198526.0, 4.02, 1445231.0, 1246705.0, 198526.0, 15.924055811118107, 634251.0, 810980.0, 127.86420518059884, 619.0, 41.39956524792924, 57.96487157198943]

In [103]:
# Define SQL statement using named placeholders
sql = text("""
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)
""")

# Convert list data to dictionaries for named parameters
columns = [
    "name", "year", "quarter", "kind",
    "latest_amt_y", "previous_amt_y", "inc_amt_y", "inc_pct_y",
    "latest_amt_q", "previous_amt_q", "inc_amt_q", "inc_pct_q",
    "q_amt_c", "y_amt", "inc_amt_py", "inc_pct_py",
    "q_amt_p", "inc_amt_pq", "inc_pct_pq",
    "ticker_id", "mean_pct", "std_pct"
]

records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]

In [105]:
try:
    # Execute the SQL statement within the existing transaction
    conlt.execute(sql, records_dicts)  # Bulk insert using named parameters
    print("Data inserted successfully!")
except Exception as e:
    print("Error inserting data:", e)
    conlt.rollback()  # Rollback the transaction in case of error

Data inserted successfully!

In [107]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
profits = pd.read_sql(sql, conlt)
profits.head().style.format(format_dict)

### End of Create Data

In [110]:
sql = """
SELECT name, market
FROM tickers"""
tickers = pd.read_sql(sql, conlt)
tickers.shape

(394, 2)

In [112]:
df_merge = pd.merge(final5, tickers, on='name', how='inner')
df_merge[['name','market']].sort_values('name').style.format(format_dict)

### Insert Profits from PortLt to PortMy

In [115]:
names = final5.name
names

3      CENTEL
4        COM7
5       CPALL
6     CPNREIT
13        TOA
14        WHA
Name: name, dtype: object

In [117]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'CENTEL', 'COM7', 'CPALL', 'CPNREIT', 'TOA', 'WHA'"

In [119]:
#quarter = 4
sql = """
SELECT * 
FROM profits 
WHERE name IN (%s) AND year = %s AND quarter = %s"""
sql = sql % (in_p, year, quarter)
print(sql)

SELECT *
FROM profits
WHERE name IN ('CENTEL', 'COM7', 'CPALL', 'CPNREIT', 'TOA', 'WHA') AND year = 2025 AND quarter = 4

In [121]:
profits_inp = pd.read_sql(sql, conlt)
profits_inp.style.format(format_dict)

In [123]:
profits_inp.sort_values(by=["kind", "name"], ascending=[True, True]).style.format(format_dict)

In [125]:
rcds = profits_inp.values.tolist()
len(rcds)

6

In [127]:
for rcd in rcds:
    print(rcd)

[2851, 'CENTEL', 2025, 4, 1, 1992901, 1752985, 239916, 13.69, 1992901, 1685602, 307299, 18.23, 974352, 667053, 307299, 46.06815350504383, 160361, 813991, 507.59910452042584, 92, 146.39681450636743, 241.22656396484436]
[2852, 'COM7', 2025, 4, 1, 4063532, 3307162, 756370, 22.87, 4063532, 3880193, 183339, 4.72, 1207698, 1029675, 178023, 17.28924175103795, 872025, 335673, 38.49350649350649, 114, 20.84318706113611, 14.002731103007644]
[2853, 'CPALL', 2025, 4, 1, 28206100, 25345841, 2860259, 11.28, 28206100, 28129321, 76779, 0.27, 7255879, 7179100, 76779, 1.069479461213801, 6596528, 659351, 9.995424865929472, 116, 5.653726081785818, 5.7880661749539595]
[2854, 'CPNREIT', 2025, 4, 1, 3460976, 1696069, 1764907, 104.06, 3460976, 2333575, 1127401, 48.31, 1484839, 357438, 1127401, 315.41162383406356, 250530, 1234309, 492.67912026503814, 647, 240.11518602477543, 203.92673313057207]
[2855, 'TOA', 2025, 4, 1, 2917013, 1919604, 997409, 51.96, 2917013, 2523302, 393711, 15.6, 844394, 450683, 393711, 87.35874217576433, 687726, 156668, 22.7805841279812, 645, 44.42483157593639, 32.657024795809946]
[2856, 'WHA', 2025, 4, 1, 5135026, 4359376, 775650, 17.79, 5135026, 4936500, 198526, 4.02, 1445231, 1246705, 198526, 15.924055811118107, 634251, 810980, 127.86420518059884, 619, 41.39956524792924, 57.96487157198943]

In [129]:
# Define SQL statement using named placeholders
sql = text("""
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)
""")

# Convert list data to dictionaries for named parameters
columns = [
    "name", "year", "quarter", "kind",
    "latest_amt_y", "previous_amt_y", "inc_amt_y", "inc_pct_y",
    "latest_amt_q", "previous_amt_q", "inc_amt_q", "inc_pct_q",
    "q_amt_c", "y_amt", "inc_amt_py", "inc_pct_py",
    "q_amt_p", "inc_amt_pq", "inc_pct_pq",
    "ticker_id", "mean_pct", "std_pct"
]

records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]

# Insert data using transactions
try:
    with conmy.begin():  # Transaction block
        conmy.execute(sql, records_dicts)  # Bulk insert using named parameters
    print("Data inserted successfully!")
except Exception as e:
    print("Error inserting data:", e)
finally:
    conmy.commit()

Error inserting data: (sqlite3.IntegrityError) UNIQUE constraint failed: profits.name, profits.year, profits.quarter
[SQL:
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (?, ?, ?, ?,
?, ?, ?, ?,
?, ?, ?, ?,
?, ?, ?, ?,
?, ?, ?,
?, ?, ?)
]
[parameters: [(2851, 'CENTEL', 2025, 4, 1, 1992901, 1752985, 239916, 13.69, 1992901, 1685602, 307299, 18.23, 974352, 667053, 307299, 46.06815350504383, 160361, 813991, 507.59910452042584, 92, 146.39681450636743), (2852, 'COM7', 2025, 4, 1, 4063532, 3307162, 756370, 22.87, 4063532, 3880193, 183339, 4.72, 1207698, 1029675, 178023, 17.28924175103795, 872025, 335673, 38.49350649350649, 114, 20.84318706113611), (2853, 'CPALL', 2025, 4, 1, 28206100, 25345841, 2860259, 11.28, 28206100, 28129321, 76779, 0.27, 7255879, 7179100, 76779, 1.069479461213801, 6596528, 659351, 9.995424865929472, 116, 5.653726081785818), (2854, 'CPNREIT', 2025, 4, 1, 3460976, 1696069, 1764907, 104.06, 3460976, 2333575, 1127401, 48.31, 1484839, 357438, 1127401, 315.41162383406356, 250530, 1234309, 492.67912026503814, 647, 240.11518602477543), (2855, 'TOA', 2025, 4, 1, 2917013, 1919604, 997409, 51.96, 2917013, 2523302, 393711, 15.6, 844394, 450683, 393711, 87.35874217576433, 687726, 156668, 22.7805841279812, 645, 44.42483157593639), (2856, 'WHA', 2025, 4, 1, 5135026, 4359376, 775650, 17.79, 5135026, 4936500, 198526, 4.02, 1445231, 1246705, 198526, 15.924055811118107, 634251, 810980, 127.86420518059884, 619, 41.39956524792924)]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [131]:
sql = """
SELECT name, year, quarter 
FROM profits
ORDER BY name
"""
df_tmp = pd.read_sql(sql, conmy)
df_tmp.set_index("name", inplace=True)
df_tmp.index

Index(['2842', '2843', '2844', '2845', '2846', '2847', '2848', '2849', '2850',
       '2851', '2851', '2852', '2853', '2854', '2855', '2856', '3BBIF',
       'ADVANC', 'BCP', 'DIF', 'FPT', 'GFPT', 'GULF', 'GUNKUL', 'KKP', 'MTC',
       'NER', 'SCGP'],
      dtype='object', name='name')

### After call 450-Export-to-PortPg

In [128]:
sql = """
SELECT * 
FROM profits 
WHERE name IN (%s) AND year = %s AND quarter = %s"""
sql = sql % (in_p, year, quarter)
print(sql)

SELECT *
FROM profits
WHERE name IN ('DIF', 'GULF', 'MTC', 'NER') AND year = 2025 AND quarter = 4

In [130]:
profits_inp = pd.read_sql(sql, conpg)
profits_inp[['name','ticker_id']].sort_values(by=[ "name"], ascending=[True])

Empty DataFrame
Columns: [name, ticker_id]
Index: []

In [132]:
sql = """
SELECT * 
FROM tickers
WHERE name IN (%s)
ORDER BY name"""
sql = sql % in_p
print(sql)

SELECT *
FROM tickers
WHERE name IN ('DIF', 'GULF', 'MTC', 'NER')
ORDER BY name

In [134]:
tickers = pd.read_sql(sql, conpg)
tickers[['name','id','market']].sort_values(by=[ "name"], ascending=[True])

   name   id                     market
0   DIF  146                        SET
1  GULF  207  SET50 / SETCLMV / SETTHSI
2   MTC  323            SET50 / SETTHSI
3   NER  649                       sSET

### Additional process to find stocks in SET50 & SET100

In [137]:
names = epss['name']
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'LANNA', 'DIF', 'STA', 'PTT', 'NER', 'RCL', 'BLA', 'AIMIRT', 'CBG', 'DOHOME', 'MAJOR', 'TMT', 'WORK', 'TPIPL', 'SCCC', 'TIPCO', 'LIT', 'PDG', 'ASIAN', 'BEC', 'TCAP', 'PREB', 'ASW', 'STGT', 'TASCO', 'TPIPP', 'MTC', 'IRPC', 'GULF', 'SUPEREIF'"

In [139]:
sql = """
SELECT * 
FROM tickers
WHERE name IN (%s)
ORDER BY name"""
sql = sql % in_p
print(sql)

SELECT *
FROM tickers
WHERE name IN ('LANNA', 'DIF', 'STA', 'PTT', 'NER', 'RCL', 'BLA', 'AIMIRT', 'CBG', 'DOHOME', 'MAJOR', 'TMT', 'WORK', 'TPIPL', 'SCCC', 'TIPCO', 'LIT', 'PDG', 'ASIAN', 'BEC', 'TCAP', 'PREB', 'ASW', 'STGT', 'TASCO', 'TPIPP', 'MTC', 'IRPC', 'GULF', 'SUPEREIF')
ORDER BY name

In [141]:
df = pd.read_sql(sql, conlt)
df

,id,name,full_name,sector,subsector,market,website,created_at,updated_at
0,669,AIMIRT,AIM INDUSTRIAL GROWTH FREEHOLD AND LEASEHOLD R...,Property & Construction,Property Fund & REITs,SET,www.aimreit.com,2018-06-21 02:39:56.326926,2018-06-21 02:39:56.326926
1,36,ASIAN,ASIAN SEA CORPORATION PUBLIC COMPANY LIMITED,Agro & Food Industry,Food & Beverage,sSET / SETTHSI,www.asianseafoods.co.th,2017-07-23 06:30:46.928337,2022-01-15 03:54:12.629742
2,728,ASW,ASSETWISE PUBLIC COMPANY LIMITED,Property & Construction,Property Development,sSET,www.assetwise.co.th,2021-08-22 15:11:51.493365,2022-01-15 03:54:12.640882
3,56,BEC,BEC WORLD PUBLIC COMPANY LIMITED,Services,Media & Publishing,SET100,www.becworld.com,2017-07-23 06:30:49.218292,2021-07-07 03:34:13.608165
4,70,BLA,BANGKOK LIFE ASSURANCE PUBLIC COMPANY LIMITED,Financials,Insurance,SET50 / SETTHSI,www.bangkoklife.com,2017-07-23 06:30:51.035886,2022-01-15 03:54:12.701165
5,87,CBG,CARABAO GROUP PUBLIC COMPANY LIMITED,Agro & Food Industry,Food & Beverage,SET50 / SETCLMV / SETWB,www.carabaogroup.com,2017-07-23 06:30:54.027998,2019-11-19 07:11:19.512684
6,140,DIF,DIGITAL TELECOMMUNICATIONS INFRASTRUCTURE FUND,Technology,Information & Communication Technology,SET,www.digital-tif.com,2017-07-23 06:31:01.454911,2017-07-23 06:31:01.454911
7,701,DOHOME,DOHOME PUBLIC COMPANY LIMITED,Services,Commerce,SET100 / SETWB,https://www.dohome.co.th/,2019-11-19 07:11:20.688406,2021-01-26 15:41:59.414935
8,653,GULF,GULF ENERGY DEVELOPMENT PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,SET50 / SETCLMV / SETTHSI,www.gulf.co.th,2017-12-21 13:43:30.426842,2021-01-26 15:41:59.507480
9,227,IRPC,IRPC PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,SET50 / SETCLMV / SETTHSI,https://www.irpc.co.th,2017-07-23 06:31:16.891853,2021-07-07 03:34:13.770280
10,264,LANNA,THE LANNA RESOURCES PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,sSET,www.lannar.com,2017-07-23 06:31:21.518187,2021-01-26 15:41:59.658586
11,273,LIT,LEASE IT PUBLIC COMPANY LIMITED,Financials,Financials,mai,www.leaseit.co.th,2017-07-23 06:31:22.751914,2022-01-15 03:54:12.908594
12,282,MAJOR,MAJOR CINEPLEX GROUP PUBLIC COMPANY LIMITED,Services,Media & Publishing,SET100 / SETCLMV / SETTHSI,www.majorcineplex.com,2017-07-23 06:31:23.860123,2021-07-07 03:34:13.827819
13,315,MTC,MUANGTHAI CAPITAL PUBLIC COMPANY LIMITED,Financials,Finance & Securities,SET50 / SETTHSI,www.muangthaicap.com,2017-07-23 06:31:27.734879,2021-01-26 15:41:59.736895
14,680,NER,NORTH EAST RUBBER PUBLIC COMPANY LIMITED,Agro & Food Industry,Agribusiness,sSET,www.nerubber.com,2019-03-03 03:43:42.465733,2019-11-19 07:11:24.050281
15,347,PDG,PRODIGY PUBLIC COMPANY LIMITED,Industrial,Industrial,mai,www.prodigy.co.th,2017-07-23 06:31:32.209499,2022-01-15 03:54:12.985822
16,372,PREB,PRE-BUILT PUBLIC COMPANY LIMITED,Property & Construction,Construction Services,SET,www.prebuilt.co.th,2017-07-23 06:31:35.566133,2021-01-26 15:41:59.818302
17,383,PTT,PTT PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,SET50 / SETCLMV / SETHD / SETTHSI,www.pttplc.com,2017-07-23 06:31:37.233572,2019-11-19 07:11:25.130404
18,396,RCL,REGIONAL CONTAINER LINES PUBLIC COMPANY LIMITED,Services,Transportation & Logistics,SET100 / SETCLMV,www.rclgroup.com,2017-07-23 06:31:39.448926,2022-01-15 03:54:13.035036
19,428,SCCC,SIAM CITY CEMENT PUBLIC COMPANY LIMITED,Property & Construction,Construction Materials,SETCLMV / SETTHSI,www.siamcitycement.com,2017-07-23 06:31:44.357168,2021-01-26 15:41:59.928836
20,481,STA,SRI TRANG AGRO-INDUSTRY PUBLIC COMPANY LIMITED,Agro & Food Industry,Agribusiness,SET100 / SETTHSI / SETWB,www.sritranggroup.com,2017-07-23 06:31:51.957277,2022-01-15 03:54:13.122661
21,714,STGT,SRI TRANG GLOVES (THAILAND) PUBLIC COMPANY LIM...,Consumer Products,Personal Products & Pharmaceuticals,SET100 / SETTHSI,www.sritranggloves.com,2021-01-26 15:42:00.052117,2022-01-15 03:54:13.136033
22,706,SUPEREIF,SUPER ENERGY POWER PLANT INFRASTRUCTURE FUND,Resources,Energy & Utilities,SET,www.supereif.com,2019-11-19 07:11:27.915718,2022-01-15 03:54:13.142504
23,502,TASCO,TIPCO ASPHALT PUBLIC COMPANY LIMITED,Property & Construction,Construction Materials,SET100 / SETCLMV / SETHD / SETTHSI,www.tipcoasphalt.com,2017-07-23 06:31:54.989965,2021-01-26 15:42:00.086060
24,503,TCAP,THANACHART CAPITAL PUBLIC COMPANY LIMITED,Financials,Banking,SET100 / SETHD,www.thanachart.co.th,2017-07-23 06:31:55.147304,2021-01-26 15:42:00.090886
25,530,TIPCO,TIPCO FOODS PUBLIC COMPANY LIMITED,Agro & Food Industry,Food & Beverage,sSET,www.tipco.net,2017-07-23 06:31:59.622355,2017-12-27 02:26:23.098918
26,545,TMT,TMT STEEL PUBLIC COMPANY LIMITED,Industrials,Steel and Metal Products,sSET / SETTHSI,www.tmtsteel.co.th,2017-07-23 06:32:02.297024,2022-01-15 03:54:13.186946
27,559,TPIPL,TPI POLENE PUBLIC COMPANY LIMITED,Property & Construction,Construction Materials,SET,www.tpipolene.co.th,2017-07-23 06:32:05.279713,2019-03-03 03:43:45.671381
28,560,TPIPP,TPI POLENE POWER PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,SET,www.tpipolenepower.co.th,2017-07-23 06:32:05.530911,2021-07-07 03:34:14.114254
29,628,WORK,WORKPOINT ENTERTAINMENT PUBLIC COMPANY LIMITED,Services,Media & Publishing,SET,www.workpoint.co.th,2017-07-23 06:32:16.937561,2022-01-15 03:54:13.274614

In [143]:
conlt.commit()
conlt.close()

In [145]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y:%m:%d %H:%M:%S")
print(formatted_time)

2026:02:21 16:08:28