In [1]:
import pandas as pd
import os
from sqlalchemy import create_engine, text
from glob import glob

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()

engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

data_path = "../data/"
csv_path = os.path.join(os.path.expanduser("~"), "iCloudDrive")
one_path = os.path.join(os.path.expanduser("~"), "OneDrive","Documents","Data")
osd_path = os.path.join(os.path.expanduser("~"),"OneDrive","Documents","obsidian-git-sync","Data")
dts_path = os.path.join(os.path.expanduser("~"),"Downloads","Datasets")

data_path = "../data/"
irreg_path = "../data/irreg/"

year = 2025
quarter = 4
year, quarter

(2025, 4)

### Begin of Irregular quarter

### Irregular Quarter Plus 1

In [5]:
file_name = 'P1-Stocks.csv'
input_file = irreg_path + file_name
# Read with header=0 (default) to use first row as column names
data_ins = pd.read_csv(input_file)
# Now data_ins will have the actual column name (probably 'name' or something else)
data_ins

      name
0      AOT
1     CITY
2      FPT
3   GVREIT
4      IRC
5     KTIS
6       MC
7    OISHI
8     PICO
9      SSC
10   TFFIF
11      UV

In [7]:
stock_list = data_ins['name'].unique().tolist()
stock_list_str = "','".join(stock_list)
print(stock_list_str)

AOT','CITY','FPT','GVREIT','IRC','KTIS','MC','OISHI','PICO','SSC','TFFIF','UV

In [9]:
sql = f'''
SELECT name, COUNT(*) FROM epss 
WHERE name in ('{stock_list_str}')
AND ((year = {year} AND quarter <= {quarter} + 1)
OR (year = {year} - 1 AND quarter > {quarter} + 1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name'''
print(sql)

SELECT name, COUNT(*) FROM epss
WHERE name in ('AOT','CITY','FPT','GVREIT','IRC','KTIS','MC','OISHI','PICO','SSC','TFFIF','UV')
AND ((year = 2025 AND quarter <= 4 + 1)
OR (year = 2025 - 1 AND quarter > 4 + 1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name

In [11]:
df = pd.read_sql(sql, conlt)
df

Empty DataFrame
Columns: [name, COUNT(*)]
Index: []

In [13]:
file_name = 'incomplete-eps.csv'
csv_file = csv_path + '/' + file_name
df.to_csv(csv_file, index=False)

### Irregular Quarter Minus 1

In [16]:
file_name   = 'M1-Stocks.csv'
input_file = irreg_path + file_name
# Read with header=0 (default) to use first row as column names
data_ins = pd.read_csv(input_file)
# Now data_ins will have the actual column name (probably 'name' or something else)
data_ins

      name
0   AEONTS
1      BCT
2    BLAND
3      BTS
4   BTSGIF
5      EPG
6   IMPACT
7      KYE
8      LHK
9      LPF
10    MACO
11     PTL
12     SFP
13  STANLY
14    TIF1
15    TLGF
16     TMW
17      TR
18    TSTH
19     VGI

In [18]:
stock_list = data_ins['name'].unique().tolist()
stock_list_str = "','".join(stock_list)
print(stock_list_str)

AEONTS','BCT','BLAND','BTS','BTSGIF','EPG','IMPACT','KYE','LHK','LPF','MACO','PTL','SFP','STANLY','TIF1','TLGF','TMW','TR','TSTH','VGI

In [20]:
sql = f'''
SELECT name, COUNT(*) FROM epss 
WHERE name in ('{stock_list_str}')
AND ((year = {year} AND quarter <= {quarter} - 1)
OR (year = {year} - 1 AND quarter > {quarter} - 1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name'''
print(sql)

SELECT name, COUNT(*) FROM epss
WHERE name in ('AEONTS','BCT','BLAND','BTS','BTSGIF','EPG','IMPACT','KYE','LHK','LPF','MACO','PTL','SFP','STANLY','TIF1','TLGF','TMW','TR','TSTH','VGI')
AND ((year = 2025 AND quarter <= 4 - 1)
OR (year = 2025 - 1 AND quarter > 4 - 1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name

In [22]:
df = pd.read_sql(sql, conlt)
df

Empty DataFrame
Columns: [name, COUNT(*)]
Index: []

In [24]:
file_name = 'incomplete-eps.csv'
csv_file = csv_path + '/' + file_name
df.to_csv(csv_file, index=False)

### End of Irregular quarter

### Normal Quarter Stocks

In [28]:
irreg_files = sorted(glob('../data/irreg/*.csv'))
irreg_files

['../data/irreg\\M1-Stocks.csv', '../data/irreg\\P1-Stocks.csv']

In [30]:
col_names = ['name']
df_tmp = pd.concat((pd.read_csv(file) for file in irreg_files), ignore_index=True)
df_tmp.shape

(32, 1)

In [32]:
stock_list = df_tmp['name'].unique().tolist()
stock_list_str = "','".join(stock_list)
print(stock_list_str)

AEONTS','BCT','BLAND','BTS','BTSGIF','EPG','IMPACT','KYE','LHK','LPF','MACO','PTL','SFP','STANLY','TIF1','TLGF','TMW','TR','TSTH','VGI','AOT','CITY','FPT','GVREIT','IRC','KTIS','MC','OISHI','PICO','SSC','TFFIF','UV

In [38]:
sql = f"""
SELECT name, COUNT(*) AS quarters 
FROM epss 
WHERE name NOT IN ('{stock_list_str}')
AND ((year = {year} AND quarter <= {quarter}) OR (year = {year}-1 AND quarter >= {quarter}+1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name"""
print(sql)

SELECT name, COUNT(*) AS quarters
FROM epss
WHERE name NOT IN ('AEONTS','BCT','BLAND','BTS','BTSGIF','EPG','IMPACT','KYE','LHK','LPF','MACO','PTL','SFP','STANLY','TIF1','TLGF','TMW','TR','TSTH','VGI','AOT','CITY','FPT','GVREIT','IRC','KTIS','MC','OISHI','PICO','SSC','TFFIF','UV')
AND ((year = 2025 AND quarter <= 4) OR (year = 2025-1 AND quarter >= 4+1))
GROUP BY name
HAVING COUNT(*) < 4
ORDER BY name

In [40]:
df = pd.read_sql(sql, conlt)
df

    name  quarters
0    KEX         2
1  SABUY         1

In [42]:
file_name = 'incomplete-eps.csv'
csv_file = csv_path + '/' + file_name
df.to_csv(csv_file, index=False)

### End of Normal Quarter stocks

### New stocks with less than 4 quarters EPS

In [44]:
sql = f'''
SELECT name, COUNT(*) FROM epss 
WHERE (year = {year} AND quarter <= {quarter}) 
OR (year = {year}-1 AND quarter > {quarter})
GROUP BY name 
HAVING MAX(quarter) < 4 
ORDER BY name'''
print(sql)

SELECT name, COUNT(*) FROM epss
WHERE (year = 2025 AND quarter <= 4)
OR (year = 2025-1 AND quarter > 4)
GROUP BY name
HAVING MAX(quarter) < 4
ORDER BY name

In [46]:
df_tmp = pd.read_sql(sql, conlt)
df_tmp

      name  COUNT(*)
0   AEONTS         3
1      BCT         3
2    BLAND         3
3      BTS         3
4   BTSGIF         3
5      EPG         3
6   IMPACT         3
7      KEX         2
8      KYE         3
9      LHK         3
10     PTL         3
11   SABUY         1
12  STANLY         3
13     TMW         3
14      TR         3
15    TSTH         3
16     VGI         3

### Delete EPSS record that unmatch with Tickers in PortPg

In [48]:
sql = f"SELECT * FROM epss E WHERE E.ticker_id NOT IN (SELECT id FROM tickers)"
df = pd.read_sql(sql, conpg)
df.shape

(0, 14)

In [50]:
sql = '''
SELECT *
FROM epss
'''
epss = pd.read_sql(sql, conlt)
epss.shape

(10332, 14)

In [52]:
sql = '''
SELECT *
FROM tickers
'''
tickers = pd.read_sql(sql, conpg)
tickers.shape

(396, 9)

In [54]:
df_merge = pd.merge(epss, tickers, on='name', how='outer', indicator = True)
df_merge.shape

(10502, 23)

In [56]:
df_left = df_merge[df_merge['_merge'] == 'left_only']
df_left

Empty DataFrame
Columns: [id_x, name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, q_eps, y_eps, aq_eps, ay_eps, ticker_id, publish_date, id_y, full_name, sector, subsector, market, website, created_at, updated_at, _merge]
Index: []

[0 rows x 23 columns]

In [58]:
stock_list = df_left['name'].unique().tolist()
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

In [60]:
sql = f'''
SELECT *
FROM epss
WHERE name IN ('{stock_list_str}')
'''
print(sql)
errors = pd.read_sql(sql, conlt)
errors

SELECT *
FROM epss
WHERE name IN ('')

Empty DataFrame
Columns: [id, name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, q_eps, y_eps, aq_eps, ay_eps, ticker_id, publish_date]
Index: []

### Delete YR_PROFITS record that unmatch with Tickers in PortPg

In [63]:
sql = """
SELECT name, sector, subsector 
FROM tickers
"""
tickers = pd.read_sql(sql, conpg)
tickers.shape

(396, 3)

In [65]:
sql = '''
SELECT *
FROM yr_profits
'''
yr_profits = pd.read_sql(sql, conlt)
yr_profits.shape

(7788, 9)

In [67]:
df_merge = pd.merge(yr_profits, tickers, on="name", how="outer", indicator=True)
df_merge.shape

(7958, 12)

In [69]:
df_left = df_merge[df_merge["_merge"] == "left_only"]
df_left.shape

(0, 12)

In [73]:
stock_list = df_left['name'].unique().tolist()
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

In [75]:
sql = f'''
SELECT *
FROM yr_profits
WHERE name IN ('{stock_list_str}')
'''
print(sql)

SELECT *
FROM yr_profits
WHERE name IN ('')

In [77]:
errors = pd.read_sql(sql, conlt)
errors

Empty DataFrame
Columns: [id, name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct, ticker_id]
Index: []

In [79]:
sqlDel = f'''
DELETE
FROM yr_profits
WHERE name IN ('{stock_list_str}')
'''
print(sqlDel)

DELETE
FROM yr_profits
WHERE name IN ('')

In [83]:
rp = conlt.execute(text(sqlDel))
rp.rowcount

0

In [85]:
name_ary = df_left["name"].unique()

# Check if name_ary is empty/null
if len(name_ary) == 0:
    print("No names to delete - name_ary is empty")
else:
    # SQLAlchemy uses parameterized queries differently
    placeholders = ', '.join([':' + str(i) for i in range(len(name_ary))])
    query = f"DELETE FROM yr_profits WHERE name IN ({placeholders})"

    # Create parameters dictionary
    params = {str(i): name for i, name in enumerate(name_ary)}

    # Execute using connection directly
    result = conlt.execute(query, params)
    conlt.commit()

    print(f"Query executed: {query}")
    print(f"Number of rows deleted: {result.rowcount}")

No names to delete - name_ary is empty

### Profits table

In [88]:
pd.set_option('display.max_rows',None)
sql = '''
SELECT * 
FROM profits
ORDER BY name, year, quarter
'''
profits = pd.read_sql(sql, conmy)
profits.shape

(35, 23)

### End of Delete Profits records

In [91]:
sql = """
SELECT * 
FROM tickers
LIMIT 1"""
tickers = pd.read_sql(sql, conlt)
tickers.dtypes

id             int64
name          object
full_name     object
sector        object
subsector     object
market        object
website       object
created_at    object
updated_at    object
dtype: object

In [93]:
sql = """
SELECT DISTINCT T.sector, T.subsector
FROM profits P
JOIN tickers T ON P.ticker_id = T.id
ORDER BY T.sector, T.subsector
"""
pwc = pd.read_sql(sql, conlt)
pwc

                     sector                               subsector
0      Agro & Food Industry                            Agribusiness
1                Financials                                 Banking
2                Financials                    Finance & Securities
3               Industrials                               Packaging
4   Property & Construction                  Construction Materials
5   Property & Construction                    Property Development
6   Property & Construction                   Property Fund & REITs
7                 Resources                      Energy & Utilities
8                  Services                                Commerce
9                  Services                    Health Care Services
10                 Services                       Tourism & Leisure
11               Technology  Information & Communication Technology

In [95]:
sql = """
SELECT * 
FROM consensus
LIMIT 1"""
consensus = pd.read_sql(sql, conlt)
consensus

,id,name,price,buy,hold,sell,eps_a,eps_b,pe,pbv,yield,target_price,status,ticker_id,created_at,updated_at
0,2,ADVANC,197.5,12,0,0,9.28,9.58,21.3,6.6,3.9,238,X,6,2017-07-23 09:50:15.621932,2023-01-31 03:07:34.659210

In [97]:
sql = """
SELECT P.name, year, quarter, C.buy, C.hold, C.sell
FROM profits P
JOIN tickers T ON P.ticker_id = T.id
JOIN consensus C ON C.ticker_id = T.id
ORDER BY C.buy DESC
"""
pwc = pd.read_sql(sql, conlt)
pwc

       name  year  quarter  buy  hold  sell
0    ADVANC  2025        4   12     0     0
1       KKP  2025        4   10     3     0
2       BCP  2025        4    8     2     0
3    CENTEL  2025        4    8     2     0
4      SCGP  2025        4    5     8     1
5     CPALL  2025        4    4     0     0
6       NER  2025        4    3     0     0
7      COM7  2025        4    3     0     0
8     THANI  2025        4    3     1     0
9       TOA  2025        4    3     0     0
10      WHA  2025        4    3     1     0
11      FPT  2025        3    1     0     0
12    3BBIF  2025        4    1     1     0
13      DIF  2025        4    1     2     0
14     GULF  2025        4    1     2     0
15      MTC  2025        4    1     1     2
16    VIBHA  2025        4    1     1     0
17  CPNREIT  2025        4    0     2     0
18      SIS  2025        4    0     0     0

### Delete Profits records by Name

In [100]:
sql = '''
SELECT * 
FROM profits
ORDER BY name, year, quarter'''
profits = pd.read_sql(sql, conlt)
profits.shape

(19, 23)

In [102]:
stock_list = names
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

NameError: name 'names' is not defined

In [41]:
sqlDel = f'''
DELETE FROM profits
WHERE name IN ('{stock_list_str}')'''
print(sqlDel)

DELETE FROM profits
WHERE name IN ('')

In [43]:
rp = conlt.execute(text(sqlDel))
rp.rowcount

OperationalError: (sqlite3.OperationalError) database is locked
[SQL:
DELETE FROM profits
WHERE name IN ('')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

### Delete profits by year

In [44]:
sql = '''
DELETE FROM profits
WHERE year = 2020'''
print(sql)

DELETE FROM profits
WHERE year = 2020

In [45]:
#rp = conlt.execute(sql)
rp.rowcount

0

### End of Delete profits by year