In [63]:
import numpy as np
import os
import pandas as pd
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text
from glob import glob

# Database connections
engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()

In [65]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dts_path = os.path.join(user_path, "OneDrive", "Downloads", "Datasets")
print(f"Datasets path: {dts_path}")
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

Datasets path: C:\Users\PC1\OneDrive\Downloads\Datasets

In [67]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Datasets path : {dts_path}") 
print(f"Data path : {dat_path}") 
print(f"Google Drive path : {god_path}")
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Data Cleansing
Base path: C:\Users\PC1\OneDrive\A4
Datasets path : C:\Users\PC1\OneDrive\Downloads\Datasets
Data path : C:\Users\PC1\OneDrive\A4\Data
Google Drive path : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path : C:\Users\PC1\iCloudDrive\Data
Obsidian path : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [69]:
sql = f"""
SELECT *
FROM tickers
"""
df_tickers_lt = pd.read_sql(sql, conlt)
df_tickers_lt.shape

(390, 9)

In [71]:
df_tickers_lt.dtypes

id             int64
name          object
full_name     object
sector        object
subsector     object
market        object
website       object
created_at    object
updated_at    object
dtype: object

In [73]:
sql = f"""
SELECT *
FROM stocks
"""
df_stocks_lt = pd.read_sql(sql, conlt)
df_stocks_lt.shape

(229, 15)

In [75]:
df_stocks_lt.dtypes

id                int64
name             object
market           object
price           float64
max_price       float64
min_price       float64
pe              float64
pbv             float64
paid_up         float64
market_cap      float64
daily_volume    float64
beta            float64
ticker_id         int64
created_at       object
updated_at       object
dtype: object

In [77]:
sql = f"""
SELECT *
FROM tickers 
"""
df_tickers_my = pd.read_sql(sql, conmy)
df_tickers_my.shape

(401, 9)

In [117]:
sql = f"""
SELECT *
FROM stocks
"""
df_stocks_my = pd.read_sql(sql, conmy)
df_stocks_my.shape

(229, 15)

In [119]:
tickers_lt_set = set(df_tickers_lt['name'].to_list())
tickers_my_set = set(df_tickers_my['name'].to_list())
lt_my_dif_set = tickers_lt_set - tickers_my_set
lt_my_dif_set

set()

In [121]:
tickers_lt_set = set(df_tickers_lt['name'].to_list())
tickers_my_set = set(df_tickers_my['name'].to_list())
my_lt_dif_set = tickers_my_set - tickers_lt_set 
my_lt_dif_set

{'ALLY,ALLY LEASEHOLD REAL ESTATE INVESTMENT TRUST,Property & Construction,Property Fund & REITs,SET,www.allyreit.com',
 'BE8,BERYL 8 PLUS PUBLIC COMPANY LIMITED,Technology,Technology,mai,www.beryl8.com',
 'CPTGF',
 'ECL',
 'ESSO',
 'INTUCH',
 'KEX',
 'LPF',
 'SABUY',
 'STEC',
 'TR'}

In [123]:
stocks_lt_set = set(df_stocks_lt['name'].to_list())
stocks_my_set = set(df_stocks_my['name'].to_list())
lt_my_dif_set = stocks_lt_set - stocks_my_set
lt_my_dif_set

set()

In [125]:
stocks_lt_set = set(df_stocks_lt['name'].to_list())
stocks_my_set = set(df_stocks_my['name'].to_list())
my_lt_dif_set = stocks_my_set - stocks_lt_set 
my_lt_dif_set

set()

In [89]:
sql = f"""
SELECT *
FROM tickers 
WHERE name = '3BBIF'
"""
df_tmp = pd.read_sql(sql, conlt)
df_tmp

,id,name,full_name,sector,subsector,market,website,created_at,updated_at
0,234,3BBIF,JASMINE BROADBAND INTERNET INFRASTRUCTURE FUND,Technology,Information & Communication Technology,SET,www.jas-if.com,2017-07-23 06:31:17.769146,2019-03-03 03:43:41.108383

In [91]:
sql = f"""
SELECT *
FROM tickers 
WHERE name = '3BBIF'
"""
df_tmp = pd.read_sql(sql, conmy)
df_tmp

,id,name,full_name,sector,subsector,market,website,created_at,updated_at
0,234,3BBIF,JASMINE BROADBAND INTERNET INFRASTRUCTURE FUND,Technology,Information & Communication Technology,SET,www.jas-if.com,2017-07-23 06:31:17.769146,2019-03-03 03:44:27.745228

In [99]:
sql = f"""
SELECT *
FROM stocks 
WHERE name = 'WG'
"""
df_tmp = pd.read_sql(sql, conmy)
df_tmp

,id,name,market,price,max_price,min_price,pe,pbv,paid_up,market_cap,daily_volume,beta,ticker_id,created_at,updated_at
0,618,WG,SET,185,185.5,116,19.46,1.65,178.5,3302.25,0.17,-0.07,618,2017-07-23 07:25:51.813637,2020-09-06 09:40:26.411806

In [95]:
sql = f"""
SELECT *
FROM consensus 
WHERE name = '3BBIF'
"""
df_tmp = pd.read_sql(sql, conmy)
df_tmp

,id,name,price,buy,hold,sell,eps_a,eps_b,pe,pbv,yield,target_price,status,ticker_id
0,208,3BBIF,8.15,1,1,0,0.94,0,8.7,0.7,11.4,8.8,X,234

In [97]:
sql = f"""
SELECT *
FROM profits 
WHERE name = '3BBIF'
"""
df_tmp = pd.read_sql(sql, conmy)
df_tmp

,id,name,year,quarter,kind,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,latest_amt_q,...,q_amt_c,y_amt,inc_amt_py,inc_pct_py,q_amt_p,inc_amt_pq,inc_pct_pq,ticker_id,mean_pct,std_pct
0,351,3BBIF,2025,4,1,10827771,5279119,5548652,105.11,10827771,...,6429421,3961184,2468237,62.310587,183813,6245608,3397.805378,234,901.373991,1664.505281

In [59]:
# --- COPY MISSING TICKERS AND STOCKS FROM portlt TO portmy ---
# This cell adds tickers and stocks that exist in portlt but not in portmy,
# maintaining the foreign key relationship (stocks.ticker_id -> tickers.id).

print("\n" + "="*80)
print("COPY MISSING DATA FROM portlt → portmy")
print("="*80)

# 1. Identify missing tickers in portmy
tickers_lt_set = set(df_tickers_lt['name'])
tickers_my_set = set(df_tickers_my['name'])
missing_tickers = tickers_lt_set - tickers_my_set

# 2. Identify missing stocks in portmy
stocks_lt_set = set(df_stocks_lt['name'])
stocks_my_set = set(df_stocks_my['name'])
missing_stocks = stocks_lt_set - stocks_my_set

print(f"📌 Missing tickers in portmy: {len(missing_tickers)} → {sorted(missing_tickers)}")
print(f"📌 Missing stocks in portmy: {len(missing_stocks)} → {sorted(missing_stocks)}")

# -------------------------------------------------------------------
# STEP 1: Insert missing tickers (without 'id' column, let SQLite auto-increment)
# -------------------------------------------------------------------
if missing_tickers:
    # Fetch full ticker records from portlt (exclude id)
    placeholders = ','.join(['?'] * len(missing_tickers))
    sql_tickers = f"""
        SELECT name, full_name, sector, subsector, market, website, created_at, updated_at
        FROM tickers
        WHERE name IN ({placeholders})
    """
    df_tickers_to_add = pd.read_sql(sql_tickers, conlt, params=tuple(missing_tickers))
    print(f"📥 Retrieved {len(df_tickers_to_add)} ticker records from portlt.")
    
    # Close existing connection to release any lock, then create a new engine with timeout
    conmy.close()
    engine_my_new = create_engine(
        "sqlite:///c:\\\\ruby\\\\portmy\\\\db\\\\development.sqlite3",
        connect_args={'timeout': 30}
    )
    
    try:
        with engine_my_new.connect() as conn:
            df_tickers_to_add.to_sql('tickers', conn, if_exists='append', index=False)
        print(f"✅ Added {len(df_tickers_to_add)} tickers to portmy.")
    except Exception as e:
        print(f"❌ Error adding tickers: {e}")
        raise
    finally:
        engine_my_new.dispose()
    
    # Refresh tickers DataFrame for portmy to get new IDs
    engine_my_new = create_engine("sqlite:///c:\\\\ruby\\\\portmy\\\\db\\\\development.sqlite3")
    df_tickers_my = pd.read_sql("SELECT id, name FROM tickers", engine_my_new)
    engine_my_new.dispose()
else:
    print("✅ No missing tickers to add.")

# -------------------------------------------------------------------
# STEP 2: Insert missing stocks (map ticker_id from portlt to portmy)
# -------------------------------------------------------------------
if missing_stocks:
    # Fetch missing stock records from portlt (include ticker_id)
    placeholders = ','.join(['?'] * len(missing_stocks))
    sql_stocks = f"""
        SELECT name, market, price, max_price, min_price, pe, pbv,
               paid_up, market_cap, daily_volume, beta, ticker_id,
               created_at, updated_at
        FROM stocks
        WHERE name IN ({placeholders})
    """
    df_stocks_to_add = pd.read_sql(sql_stocks, conlt, params=tuple(missing_stocks))
    print(f"📥 Retrieved {len(df_stocks_to_add)} stock records from portlt.")
    
    # Build mapping from ticker name → new ticker id in portmy
    ticker_name_to_id_my = dict(zip(df_tickers_my['name'], df_tickers_my['id']))
    
    # Get ticker names for each stock's original ticker_id (from portlt)
    ticker_id_to_name_lt = dict(zip(df_tickers_lt['id'], df_tickers_lt['name']))
    df_stocks_to_add['ticker_name'] = df_stocks_to_add['ticker_id'].map(ticker_id_to_name_lt)
    
    # Map to new ticker_id in portmy
    df_stocks_to_add['new_ticker_id'] = df_stocks_to_add['ticker_name'].map(ticker_name_to_id_my)
    
    # Drop any rows where the ticker name is not found in portmy (should not happen)
    before = len(df_stocks_to_add)
    df_stocks_to_add = df_stocks_to_add.dropna(subset=['new_ticker_id'])
    if len(df_stocks_to_add) < before:
        print(f"⚠️  Skipped {before - len(df_stocks_to_add)} stocks because their ticker is missing in portmy.")
    
    # Prepare insertion DataFrame (drop original ticker_id and helper columns)
    df_insert = df_stocks_to_add.drop(columns=['ticker_id', 'ticker_name'], errors='ignore')
    df_insert.rename(columns={'new_ticker_id': 'ticker_id'}, inplace=True)
    
    # Ensure column order matches target table
    column_order = ['name', 'market', 'price', 'max_price', 'min_price', 'pe', 'pbv',
                    'paid_up', 'market_cap', 'daily_volume', 'beta', 'ticker_id',
                    'created_at', 'updated_at']
    df_insert = df_insert[column_order]
    
    # Insert using a fresh connection with timeout
    engine_my_new = create_engine(
        "sqlite:///c:\\\\ruby\\\\portmy\\\\db\\\\development.sqlite3",
        connect_args={'timeout': 30}
    )
    try:
        with engine_my_new.connect() as conn:
            df_insert.to_sql('stocks', conn, if_exists='append', index=False)
        print(f"✅ Added {len(df_insert)} stocks to portmy.")
    except Exception as e:
        if "UNIQUE constraint failed" in str(e):
            print("⚠️  Some stocks already exist – using INSERT OR IGNORE row by row.")
            with engine_my_new.connect() as conn:
                for _, row in df_insert.iterrows():
                    conn.execute(
                        text("""
                            INSERT OR IGNORE INTO stocks 
                            (name, market, price, max_price, min_price, pe, pbv,
                             paid_up, market_cap, daily_volume, beta, ticker_id,
                             created_at, updated_at)
                            VALUES (:name, :market, :price, :max_price, :min_price, :pe, :pbv,
                                    :paid_up, :market_cap, :daily_volume, :beta, :ticker_id,
                                    :created_at, :updated_at)
                        """),
                        row.to_dict()
                    )
                conn.commit()
            print(f"✅ Inserted/ignored {len(df_insert)} records.")
        else:
            print(f"❌ Error adding stocks: {e}")
            raise
    finally:
        engine_my_new.dispose()
else:
    print("✅ No missing stocks to add.")

# -------------------------------------------------------------------
# STEP 3: Verification (re‑query both tables in portmy)
# -------------------------------------------------------------------
print("\n" + "-"*60)
print("VERIFICATION")
print("-"*60)

# Use a fresh connection to verify
engine_my_verify = create_engine("sqlite:///c:\\\\ruby\\\\portmy\\\\db\\\\development.sqlite3")
df_tickers_my_final = pd.read_sql("SELECT name FROM tickers", engine_my_verify)
df_stocks_my_final = pd.read_sql("SELECT name FROM stocks", engine_my_verify)
engine_my_verify.dispose()

tickers_my_final_set = set(df_tickers_my_final['name'])
stocks_my_final_set = set(df_stocks_my_final['name'])

still_missing_tickers = tickers_lt_set - tickers_my_final_set
still_missing_stocks = stocks_lt_set - stocks_my_final_set

print(f"Tickers in portlt: {len(tickers_lt_set)}")
print(f"Tickers in portmy after copy: {len(tickers_my_final_set)}")
if not still_missing_tickers:
    print("✅ All tickers from portlt are now present in portmy.")
else:
    print(f"⚠️  Still missing {len(still_missing_tickers)} tickers: {sorted(still_missing_tickers)}")

print(f"\nStocks in portlt: {len(stocks_lt_set)}")
print(f"Stocks in portmy after copy: {len(stocks_my_final_set)}")
if not still_missing_stocks:
    print("✅ All stocks from portlt are now present in portmy.")
else:
    print(f"⚠️  Still missing {len(still_missing_stocks)} stocks: {sorted(still_missing_stocks)}")

print("\n" + "="*80)
print("COPY OPERATION COMPLETED")
print("="*80)

# Optional: reassign conmy for later cells (if needed)
# engine = create_engine("sqlite:///c:\\\\ruby\\\\portmy\\\\db\\\\development.sqlite3")
# conmy = engine.connect()

================================================================================
COPY MISSING DATA FROM portlt → portmy
================================================================================
📌 Missing tickers in portmy: 5 → ['AURA', 'BTG', 'MOSHI', 'STECON', 'TLI']
📌 Missing stocks in portmy: 5 → ['AURA', 'BTG', 'MOSHI', 'STECON', 'TLI']
📥 Retrieved 5 ticker records from portlt.
✅ Added 5 tickers to portmy.
📥 Retrieved 5 stock records from portlt.
✅ Added 5 stocks to portmy.

------------------------------------------------------------
VERIFICATION
------------------------------------------------------------
Tickers in portlt: 390
Tickers in portmy after copy: 401
✅ All tickers from portlt are now present in portmy.

Stocks in portlt: 229
Stocks in portmy after copy: 258
✅ All stocks from portlt are now present in portmy.

================================================================================
COPY OPERATION COMPLETED
================================================================================

In [115]:
# --- DELETE EXTRA TICKERS AND STOCKS FROM portmy (not in portlt) ---
# Uses raw DBAPI cursor with manual connection management.

print("\n" + "="*80)
print("DELETE EXTRA DATA FROM portmy (records not in portlt)")
print("="*80)

# 1. Identify extra tickers in portmy (present in my, missing in lt)
tickers_lt_set = set(df_tickers_lt['name'])
tickers_my_set = set(df_tickers_my['name'])
extra_tickers = tickers_my_set - tickers_lt_set

# 2. Identify extra stocks in portmy
stocks_lt_set = set(df_stocks_lt['name'])
stocks_my_set = set(df_stocks_my['name'])
extra_stocks = stocks_my_set - stocks_lt_set

print(f"📌 Extra tickers in portmy (to delete): {len(extra_tickers)} → {sorted(extra_tickers)}")
print(f"📌 Extra stocks in portmy (to delete): {len(extra_stocks)} → {sorted(extra_stocks)}")

if not extra_tickers and not extra_stocks:
    print("✅ No extra data to delete – portmy is already a subset of portlt.")
else:
    # Use a fresh engine with timeout
    engine_my_del = create_engine(
        "sqlite:///c:\\\\ruby\\\\portmy\\\\db\\\\development.sqlite3",
        connect_args={'timeout': 30}
    )
    
    # First, delete extra stocks (they reference tickers)
    if extra_stocks:
        stock_names = list(extra_stocks)
        placeholders = ','.join(['?'] * len(stock_names))
        delete_stocks_sql = f"DELETE FROM stocks WHERE name IN ({placeholders})"
        
        # Manually handle raw connection (no context manager)
        raw_conn = engine_my_del.raw_connection()
        try:
            cursor = raw_conn.cursor()
            cursor.execute(delete_stocks_sql, stock_names)
            raw_conn.commit()
            deleted_count = cursor.rowcount
        finally:
            raw_conn.close()
        print(f"✅ Deleted {deleted_count} extra stock records from portmy.")
    
    # Second, delete extra tickers (after stocks are gone)
    if extra_tickers:
        ticker_names = list(extra_tickers)
        placeholders = ','.join(['?'] * len(ticker_names))
        delete_tickers_sql = f"DELETE FROM tickers WHERE name IN ({placeholders})"
        
        raw_conn = engine_my_del.raw_connection()
        try:
            cursor = raw_conn.cursor()
            cursor.execute(delete_tickers_sql, ticker_names)
            raw_conn.commit()
            deleted_count = cursor.rowcount
        finally:
            raw_conn.close()
        print(f"✅ Deleted {deleted_count} extra ticker records from portmy.")
    
    engine_my_del.dispose()

# -------------------------------------------------------------------
# FINAL VERIFICATION – both tables should now be identical
# -------------------------------------------------------------------
print("\n" + "-"*60)
print("FINAL VERIFICATION (portmy vs portlt)")
print("-"*60)

# Refresh DataFrames using fresh connections
engine_lt_verify = create_engine("sqlite:///c:\\\\ruby\\\\portlt\\\\db\\\\development.sqlite3")
df_tickers_lt_final = pd.read_sql("SELECT name FROM tickers", engine_lt_verify)
df_stocks_lt_final = pd.read_sql("SELECT name FROM stocks", engine_lt_verify)
engine_lt_verify.dispose()

engine_my_verify = create_engine("sqlite:///c:\\\\ruby\\\\portmy\\\\db\\\\development.sqlite3")
df_tickers_my_final = pd.read_sql("SELECT name FROM tickers", engine_my_verify)
df_stocks_my_final = pd.read_sql("SELECT name FROM stocks", engine_my_verify)
engine_my_verify.dispose()

tickers_lt_final_set = set(df_tickers_lt_final['name'])
tickers_my_final_set = set(df_tickers_my_final['name'])
stocks_lt_final_set = set(df_stocks_lt_final['name'])
stocks_my_final_set = set(df_stocks_my_final['name'])

tickers_diff = tickers_lt_final_set.symmetric_difference(tickers_my_final_set)
stocks_diff = stocks_lt_final_set.symmetric_difference(stocks_my_final_set)

print(f"Tickers in portlt: {len(tickers_lt_final_set)}")
print(f"Tickers in portmy: {len(tickers_my_final_set)}")
if not tickers_diff:
    print("✅ Tickers tables are identical.")
else:
    print(f"⚠️  Tickers differ: {tickers_diff}")

print(f"\nStocks in portlt: {len(stocks_lt_final_set)}")
print(f"Stocks in portmy: {len(stocks_my_final_set)}")
if not stocks_diff:
    print("✅ Stocks tables are identical.")
else:
    print(f"⚠️  Stocks differ: {stocks_diff}")

print("\n" + "="*80)
print("SYNC OPERATION (copy + delete) COMPLETED")
print("="*80)

================================================================================
DELETE EXTRA DATA FROM portmy (records not in portlt)
================================================================================
📌 Extra tickers in portmy (to delete): 11 → ['ALLY,ALLY LEASEHOLD REAL ESTATE INVESTMENT TRUST,Property & Construction,Property Fund & REITs,SET,www.allyreit.com', 'BE8,BERYL 8 PLUS PUBLIC COMPANY LIMITED,Technology,Technology,mai,www.beryl8.com', 'CPTGF', 'ECL', 'ESSO', 'INTUCH', 'KEX', 'LPF', 'SABUY', 'STEC', 'TR']
📌 Extra stocks in portmy (to delete): 29 → ['BAT-3K', 'BTC', 'CNS', 'CPNRF', 'CPTGF', 'EARTH', 'ECL', 'EPCO', 'ESSO', 'FOCUS', 'GL', 'GOLDPF', 'INTUCH', 'KEX', 'LPF', 'NPPG', 'PRANDA', 'SABUY', 'SMM', 'SPPT', 'SSTSS', 'STEC', 'TFUND', 'TGROWTH', 'TIC', 'TLOGIS', 'TR', 'UNIPF', 'WG']
✅ Deleted 29 extra stock records from portmy.
✅ Deleted 11 extra ticker records from portmy.

------------------------------------------------------------
FINAL VERIFICATION (portmy vs portlt)
------------------------------------------------------------
Tickers in portlt: 390
Tickers in portmy: 390
✅ Tickers tables are identical.

Stocks in portlt: 229
Stocks in portmy: 229
✅ Stocks tables are identical.

================================================================================
SYNC OPERATION (copy + delete) COMPLETED
================================================================================