### Restart and Run All
#### Input file: C:\Users\PC1\OneDrive\A5\Data\price-hilo.csv
#### Update file: C:\Ruby\PortPg\db

In [2]:
import os
import pandas as pd
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-05-22 19:53:26

In [3]:
sql = '''
SELECT *
FROM stocks ORDER BY name
'''
stocks = pd.read_sql(sql, conpg)
stocks.head(5)

,id,name,market,price,max_price,min_price,pe,pbv,paid_up,market_cap,daily_volume,beta,ticker_id,created_at,updated_at
0,814,3BBIF,SET,6.45,6.95,5.65,999.99,0.74,78812.80,65200.00,40.31,0.59,241,2022-05-17 18:59:06.534682,2026-05-20
1,718,ACE,SET100 / SETTHSI,1.30,1.34,1.25,17.72,1.82,5088.00,26050.56,54.63,0.92,667,2022-05-17 18:59:06.146232,2026-05-20
2,719,ADVANC,SET50 / SETHD / SETTHSI,368.00,410.00,267.00,23.03,7.52,2974.21,587406.42,954.23,0.79,8,2022-05-17 18:59:06.164482,2026-05-20
3,720,AEONTS,SET,92.25,122.50,86.50,12.18,2.26,250.00,49125.00,100.95,1.15,9,2022-05-17 18:59:06.169113,2026-05-20
4,721,AH,sSET / SETTHSI,13.90,15.80,11.70,7.48,1.21,354.84,11532.37,70.31,1.51,11,2022-05-17 18:59:06.173369,2026-05-20

In [4]:
# Get the current working directory
current_path = os.getcwd()
#print(f"Current path: {current_path}") 
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#print(f"Base path (base_path): {base_path}") 
dat_path = os.path.join(base_path, "Data")
#print(f"Data path (dat_path): {dat_path}") 

file_name = 'price-hilo.csv'
input_file = os.path.join(dat_path, file_name )
print(f"Input file : {input_file}")

Input file : C:\Users\PC1\OneDrive\A4\Data\price-hilo.csv

In [5]:
in_df = pd.read_csv(input_file)
in_df.shape

(185, 8)

In [6]:
# Logic to update year_low and year_high based on conditions
in_df.loc[in_df['today_low'] < in_df['year_low'], 'year_low'] = in_df['today_low']
in_df.loc[in_df['today_high'] > in_df['year_high'], 'year_high'] = in_df['today_high']

In [7]:
in_df.sample(5)

,name,price,today_low,today_high,year_low,year_high,percent,updated_at
171,TTLPF,9.9,9.85,9.90,8.80,12.10,-0.50,2026-05-21
161,TOA,12.5,12.00,12.50,9.35,16.40,5.04,2026-05-21
116,PTTEP,150.5,150.00,153.00,97.25,164.00,-1.63,2026-05-21
124,SAPPE,29.5,29.25,29.75,27.50,41.75,0.85,2026-05-21
32,BLA,22.1,22.10,22.50,14.00,24.00,-1.78,2026-05-21

### Update table Stocks in PortPG Database, columns max_price & min_price with 
### year_high & year_low from price-hilo.csv

In [9]:
for index, row in in_df.iterrows():
    sql = text('''
        UPDATE stocks
        SET price = :price, max_price = :max_price, min_price = :min_price, updated_at = :updated_at 
        WHERE name = :name
    ''')
    
    params = {
        'price': float(row['price']),
        'max_price': float(row['year_high']),
        'min_price': float(row['year_low']),
        'updated_at': row['updated_at'],
        'name': str(row['name'])
    }
    
    conpg.execute(sql, params)

In [10]:
stocks.head(5)

,id,name,market,price,max_price,min_price,pe,pbv,paid_up,market_cap,daily_volume,beta,ticker_id,created_at,updated_at
0,814,3BBIF,SET,6.45,6.95,5.65,999.99,0.74,78812.80,65200.00,40.31,0.59,241,2022-05-17 18:59:06.534682,2026-05-20
1,718,ACE,SET100 / SETTHSI,1.30,1.34,1.25,17.72,1.82,5088.00,26050.56,54.63,0.92,667,2022-05-17 18:59:06.146232,2026-05-20
2,719,ADVANC,SET50 / SETHD / SETTHSI,368.00,410.00,267.00,23.03,7.52,2974.21,587406.42,954.23,0.79,8,2022-05-17 18:59:06.164482,2026-05-20
3,720,AEONTS,SET,92.25,122.50,86.50,12.18,2.26,250.00,49125.00,100.95,1.15,9,2022-05-17 18:59:06.169113,2026-05-20
4,721,AH,sSET / SETTHSI,13.90,15.80,11.70,7.48,1.21,354.84,11532.37,70.31,1.51,11,2022-05-17 18:59:06.173369,2026-05-20

In [11]:
# Commit the changes
conpg.commit()
conpg.close()

In [12]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-05-22 19:53:27