### Must check that there are data for all sector

### Input file: name-ttl.csv
### Output files: Price.csv, Price-Today.csv

In [3]:
import glob
import os
import pandas as pd
from datetime import date, timedelta, datetime
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

##pd.reset_option('display.max_rows')
pd.options.display.float_format = '{:.2f}'.format
pd.options.display.max_rows = 120

today = date.today()
today = today - timedelta(days=1)
yesterday = today - timedelta(days=1)
print(today, yesterday)

2026-03-13 2026-03-12

In [4]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-03-14 21:46:19

### Restart & Run All Cells

In [6]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dts_path = os.path.join(user_path, "OneDrive", "Downloads", "Datasets")
print(f"Datasets path: {dts_path}")
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

Datasets path: C:\Users\User\OneDrive\Downloads\Datasets

In [7]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Datasets path : {dts_path}") 
print(f"Data path : {dat_path}") 
print(f"Google Drive path : {god_path}")
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\User
Current path: C:\Users\User\OneDrive\A4\Daily
Base path: C:\Users\User\OneDrive\A4
Datasets path : C:\Users\User\OneDrive\Downloads\Datasets
Data path : C:\Users\User\OneDrive\A4\Data
Google Drive path : C:\Users\User\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path : C:\Users\User\iCloudDrive\Data
Obsidian path : C:\Users\User\OneDrive\Documents\obsidian-git-sync\Data

In [8]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [9]:
format_dict = {'Bid Size':'{:,}','Offer Size':'{:,}',
              'Last':'{:,.2f}','Open':'{:,.2f}','High':'{:,.2f}','Low':'{:,.2f}','Bid':'{:,.2f}','Offer':'{:,.2f}',
              'Total Volume':'{:,}','Total-Volume':'{:,}','Total Value (k)':'{:,.3f}','Total-Value-(k)':'{:,.3f}',
              'TR Volume':'{:,}','TR Value (k)':'{:,.3f}',               
              'Change':'{:,.2f}','%Change':'{:.2f}%'}

### If use style.format(format_dict), number of maximum rows will be ineffective

In [11]:
### SET100 b
file_name = "StockQuotation.xlsx"
input_file = os.path.join(dts_path, file_name)
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['Total Volume'] != '-']
df_S100[colu].shape

(100, 9)

In [12]:
df_S100.query('Symbol == ("ADVANC","BCH","IVL","JMT","PTTGC","RCL","STA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,ADVANC,-,363.00,-5,-1.36,366.00,367.00,360.00,-,0.00,6528781,2367269.60,40100,362.00,363.00,31800
12,BCH,-,10.10,0.20,2.02,9.90,10.10,9.85,-,0.00,13018395,130586.69,147700,10.10,10.20,919400
47,IVL,-,19.70,-0.60,-2.96,20.10,20.20,19.60,-,0.00,25638802,508821.53,367600,19.70,19.80,40500
50,JMT,-,8.75,-0.35,-3.85,9.00,9.05,8.75,10000,87.50,13936359,123147.91,428900,8.75,8.80,135200
71,PTTGC,-,28.25,-,-,28.25,28.50,27.75,-,0.00,25376372,715115.03,2067500,28.25,28.50,911600
74,RCL,-,29.50,-0.25,-0.84,29.75,29.75,29.25,-,0.00,2872004,84659.57,265800,29.25,29.50,59000
84,STA,-,15.50,-0.20,-1.27,15.80,16.00,15.40,-,0.00,12283755,192276.33,224600,15.50,15.60,255800

In [13]:
### sSET 1
file_name = "StockQuotation (1).xlsx"
input_file = os.path.join(dts_path, file_name)
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['Total Volume'] != '-']
df_sSET[colu].shape

(100, 9)

In [14]:
df_sSET.query('Symbol == ("AH","MCS","ORI","SINGER","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
2,AH,XD,13.30,-,-,13.30,13.30,13.10,-,0,101245,1331.74,8400,13.20,13.30,23800
39,MCS,-,9.55,0.05,0.53,9.50,9.60,9.45,-,0,523103,4972.67,18900,9.55,9.60,113600
50,ORI,-,1.90,-0.03,-1.55,1.93,1.93,1.86,-,0,1484054,2794.68,119200,1.87,1.90,6600
73,SINGER,-,5.50,-0.05,-0.90,5.55,5.70,5.35,-,0,1753880,9639.93,18400,5.50,5.55,101400
83,SYNEX,-,9.50,-0.10,-1.04,9.60,9.60,9.45,-,0,398225,3788.26,36700,9.45,9.50,1100

In [15]:
### SETCLMV 2
file_name = "StockQuotation (2).xlsx"
input_file = os.path.join(dts_path, file_name)
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['Total Volume'] != '-']
df_CLMV[colu].shape

(57, 9)

In [16]:
df_CLMV.query('Symbol == ("BCH","IVL","PTTGC","RCL","TOA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
5,BCH,-,10.10,0.20,2.02,9.90,10.10,9.85,-,0.00,13018395,130586.69,147700,10.10,10.20,919400
24,IVL,-,19.70,-0.60,-2.96,20.10,20.20,19.60,-,0.00,25638802,508821.53,367600,19.70,19.80,40500
38,PTTGC,-,28.25,-,-,28.25,28.50,27.75,-,0.00,25376372,715115.03,2067500,28.25,28.50,911600
41,RCL,-,29.50,-0.25,-0.84,29.75,29.75,29.25,-,0.00,2872004,84659.57,265800,29.25,29.50,59000
53,TOA,-,12.70,-0.60,-4.51,13.20,13.20,12.50,-,0.00,6733751,85826.99,124300,12.70,12.80,58800

In [17]:
### SETHD 3
file_name = "StockQuotation (3).xlsx"
input_file = os.path.join(dts_path, file_name)
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['Total Volume'] != '-']
df_HD[colu].shape

(30, 9)

In [18]:
df_HD.query('Symbol == ("JMT","RCL")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
6,JMT,-,8.75,-0.35,-3.85,9.00,9.05,8.75,10000,87.50,13936359,123147.91,428900,8.75,8.80,135200
19,RCL,-,29.50,-0.25,-0.84,29.75,29.75,29.25,-,0.00,2872004,84659.57,265800,29.25,29.50,59000

In [19]:
### SETESG 4
file_name = "StockQuotation (4).xlsx"
input_file = os.path.join(dts_path, file_name)
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['Total Volume'] != '-']
df_THSI[colu].shape

(122, 9)

In [20]:
df_THSI.query('Symbol == ("AWC","BCH","IVL","JMT","NER","ORI","PTTGC","STA","SYNEX","TOA","TVO","VIBHA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2.04,-0.04,-1.92,2.04,2.08,2.02,-,0.00,55009176,112160.31,2705800,2.04,2.06,714100
13,BCH,-,10.10,0.20,2.02,9.90,10.10,9.85,-,0.00,13018395,130586.69,147700,10.10,10.20,919400
48,IVL,-,19.70,-0.60,-2.96,20.10,20.20,19.60,-,0.00,25638802,508821.53,367600,19.70,19.80,40500
50,JMT,-,8.75,-0.35,-3.85,9.00,9.05,8.75,10000,87.50,13936359,123147.91,428900,8.75,8.80,135200
66,NER,-,4.70,-0.04,-0.84,4.74,4.74,4.64,-,0.00,12066853,56559.45,170800,4.68,4.70,445500
68,ORI,-,1.90,-0.03,-1.55,1.93,1.93,1.86,-,0.00,1484054,2794.68,119200,1.87,1.90,6600
80,PTTGC,-,28.25,-,-,28.25,28.50,27.75,-,0.00,25376372,715115.03,2067500,28.25,28.50,911600
101,STA,-,15.50,-0.20,-1.27,15.80,16.00,15.40,-,0.00,12283755,192276.33,224600,15.50,15.60,255800
104,SYNEX,-,9.50,-0.10,-1.04,9.60,9.60,9.45,-,0.00,398225,3788.26,36700,9.45,9.50,1100
112,TOA,-,12.70,-0.60,-4.51,13.20,13.20,12.50,-,0.00,6733751,85826.99,124300,12.70,12.80,58800
119,TVO,XD,24.20,-1.30,-5.10,24.30,24.30,24.00,-,0.00,2486970,59932.28,114800,24.20,24.30,89200

In [21]:
### SETWB 5
file_name = "StockQuotation (5).xlsx"
input_file = os.path.join(dts_path, file_name)
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['Total Volume'] != '-']
df_WB[colu].shape

(30, 9)

In [22]:
df_WB.query('Symbol == ("BCH","CPF","STA","TVO","VIBHA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
3,BCH,-,10.10,0.20,2.02,9.90,10.10,9.85,-,0.00,13018395,130586.69,147700,10.10,10.20,919400
15,CPF,-,18.90,-0.20,-1.05,18.90,19.10,18.60,-,0.00,28028366,527480.21,2846000,18.80,18.90,844600
26,STA,-,15.50,-0.20,-1.27,15.80,16.00,15.40,-,0.00,12283755,192276.33,224600,15.50,15.60,255800
29,TVO,XD,24.20,-1.30,-5.10,24.30,24.30,24.00,-,0.00,2486970,59932.28,114800,24.20,24.30,89200

In [23]:
### PROP 6
file_name = "StockQuotation (6).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PROP = pd.read_excel(input_file, header=9)
df_PROP = df_PROP[df_PROP['Total Volume'] != '-']
df_PROP[colu].shape

(55, 9)

In [24]:
df_PROP.query('Symbol == ("AWC","ORI","SENA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2.04,-0.04,-1.92,2.04,2.08,2.02,-,0,55009176,112160.31,2705800,2.04,2.06,714100
34,ORI,-,1.90,-0.03,-1.55,1.93,1.93,1.86,-,0,1484054,2794.68,119200,1.87,1.90,6600
53,SENA,-,1.87,-,-,1.86,1.87,1.85,-,0,102765,191.00,133400,1.85,1.87,147000

In [25]:
### PFREIT 7
file_name = "StockQuotation (7).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['Total Volume'] != '-']
df_PFREIT[colu].shape

(53, 9)

In [26]:
df_PFREIT.query('Symbol == ("CPNREIT","GVREIT","WHAIR","WHART")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
9,CPNREIT,-,11.60,-,-,11.70,11.70,11.50,-,0,986998,11420.57,1369800,11.50,11.60,940000
17,GVREIT,-,6.40,-0.05,-0.78,6.45,6.45,6.35,-,0,317701,2029.91,231700,6.35,6.40,175900
54,WHAIR,-,6.65,-0.10,-1.48,6.70,6.75,6.65,-,0,773729,5184.74,1025300,6.65,6.70,130400
55,WHART,-,10.30,-0.10,-0.96,10.30,10.30,10.20,-,0,455700,4693.14,863900,10.20,10.30,143100

In [27]:
### TRANS 8
file_name = "StockQuotation (8).xlsx"
input_file = os.path.join(dts_path, file_name)
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['Total Volume'] != '-']
df_TRANS[colu].shape

(27, 9)

In [28]:
df_TRANS.query('Symbol == ("RCL","TFFIF")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
19,RCL,-,29.50,-0.25,-0.84,29.75,29.75,29.25,-,0,2872004,84659.57,265800,29.25,29.50,59000
23,TFFIF,-,6.50,-0.05,-0.76,6.55,6.60,6.50,-,0,1558699,10181.42,786200,6.50,6.55,3200

In [29]:
### ICT 9
file_name = "StockQuotation (9).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['Total Volume'] != '-']
df_ICT[colu].shape

(38, 9)

In [30]:
df_ICT.query('Symbol == ("3BBIF","DIF","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
0,3BBIF,-,6.60,-0.05,-0.75,6.60,6.65,6.55,-,0,4490689,29643.58,3462000,6.55,6.60,712300
7,DIF,-,9.40,-0.05,-0.53,9.45,9.50,9.40,-,0,13837385,130420.48,2626100,9.40,9.45,2422100
33,SYNEX,-,9.50,-0.10,-1.04,9.60,9.60,9.45,-,0,398225,3788.26,36700,9.45,9.50,1100

## Add section ENERG for PTG

In [32]:
### ENERG 10
file_name = "StockQuotation (10).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ENG = pd.read_excel(input_file, header=9)
df_ENG = df_ENG[df_ENG['Total Volume'] != '-']
df_ENG[colu].shape

(59, 9)

In [33]:
df_ENG.query('Symbol == ("PTG","PTT")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
35,PTG,-,8,-0.15,-1.84,8.05,8.10,7.90,-,0,9126046,72951.52,516200,7.95,8,187900
36,PTT,-,34.25,-0.75,-2.14,34.50,35,34,-,0,121092039,4166814.80,19608700,34,34.25,5758800

### ------------ End of Individual Category

In [35]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_PROP, df_PFREIT, df_TRANS, df_ICT, df_ENG])
df.shape

(671, 16)

In [36]:
df.query('Symbol == "RCL"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
74,RCL,-,29.50,-0.25,-0.84,29.75,29.75,29.25,-,0.00,2872004,84659.57,265800,29.25,29.50,59000
41,RCL,-,29.50,-0.25,-0.84,29.75,29.75,29.25,-,0.00,2872004,84659.57,265800,29.25,29.50,59000
19,RCL,-,29.50,-0.25,-0.84,29.75,29.75,29.25,-,0.00,2872004,84659.57,265800,29.25,29.50,59000
25,RCL,-,29.50,-0.25,-0.84,29.75,29.75,29.25,-,0.00,2872004,84659.57,265800,29.25,29.50,59000
19,RCL,-,29.50,-0.25,-0.84,29.75,29.75,29.25,-,0,2872004,84659.57,265800,29.25,29.50,59000

In [37]:
df.Symbol.nunique()

363

In [38]:
stock_list = df['Symbol'].unique().tolist()
stock_list_str = "','".join(stock_list)
len(stock_list)

363

In [39]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(363, 16)

In [40]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [41]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
#df[cols].sort_values('Symbol',ascending=True)
df[cols].shape

(363, 9)

In [42]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file: {input_file}")

Input file: C:\Users\User\OneDrive\A4\Data\name-ttl.csv

In [43]:
df_ttl = pd.read_csv(input_file, header=None, names=['Symbol'])
df_ttl.shape

(215, 1)

In [44]:
colt = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()

In [45]:
df_out = df[colt]
df_out.shape

(363, 9)

In [46]:
df_merge = pd.merge(df_ttl, df_out, on = 'Symbol', how='inner')
df_merge.shape

(165, 9)

In [47]:
# Select rows in df_ttl where Symbol is NOT in df
df_only_in_ttl = df_ttl[~df_ttl['Symbol'].isin(df['Symbol'])]
print(df_only_in_ttl.shape)

(50, 1)

In [48]:
print(df_only_in_ttl)

     Symbol
7        AJ
14      ASP
20      BAY
25      BCT
27      BE8
28   BEAUTY
31      BGC
35     BKIH
53      DCC
54     DCON
58      DRT
66   FSMART
68       GC
70      GGC
73   GRAMMY
83      IMH
85     INOX
86       IP
96      KSL
99      KYE
103    LHFG
104     LHK
105     LIT
106     LPH
110    MBAX
115     MST
123     PAP
124   PCSGH
125     PDG
128    PREB
143      RS
144     S11
151    SCCC
159     SKN
160     SKR
161    SMPC
162     SNC
164     SPC
170  STANLY
183   TIPCO
185      TK
188     TMT
189     TMW
192   TPIPL
197    TSTH
204    TYCN
205     UTP
207   VIBHA
208     VNG
214    WORK

In [102]:
file_name = '254-candidates.csv'
data_file = os.path.join(dat_path, file_name)
df_only_in_ttl.to_csv(data_file, index=False, header=True)

### End of daily process to export Price to MySql Stock database

In [51]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-03-14 21:46:20

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes