In [1]:
import os
import pandas as pd
from urllib import request
from bs4 import BeautifulSoup
# from datetime import date, timedelta
from datetime import datetime
from time import sleep, strftime

# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-07-20 21:00:37

In [2]:
url = "https://www.set.or.th/en/market/product/stock/quote/"
percent_span = ''

In [3]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

In [4]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path : {dat_path}") 
print(f"Google Drive path : {god_path}")
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Daily
Base path: C:\Users\PC1\OneDrive\A4
Data path : C:\Users\PC1\OneDrive\A4\Data
Google Drive path : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path : C:\Users\PC1\iCloudDrive\Data
Obsidian path : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [5]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file : {input_file}")

Input file : C:\Users\PC1\OneDrive\A4\Data\name-ttl.csv

In [6]:
file_name = "price-hilo.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [7]:
print(f"Output file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

Output file : C:\Users\PC1\OneDrive\A4\Data\price-hilo.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\price-hilo.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\price-hilo.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\price-hilo.csv

In [8]:
def cvt_str_to_flt(input_str):
    # Check for the special pattern and return 0
    if input_str == '(-)':
        return 0
    
    # Remove parentheses and percent sign
    cleaned_str = input_str.replace('(', '').replace(')', '').replace('%', '')

    # Convert to float
    try:
        return float(cleaned_str)
    except ValueError:
        # Handle the case where the conversion fails
        return None

In [9]:
def get_stock_data(in_df):

    in_df.columns = ['name']
    
    output_columns = ['name', 'price', 'today_low', 'today_high', 'year_low', 'year_high', 'percent', 'updated_at']
    # Initialize an empty DataFrame with specified columns
    out_df = pd.DataFrame(columns=output_columns)
    
    for index, row in in_df.iterrows():
        name = str(row['name']).upper()
        response = request.urlopen(url + name + '/price')
        html_page = BeautifulSoup(response, 'html.parser')
        
  #      price = html_page.find('div', class_='value text-white mb-0 me-2 lh-1 stock-info').text.strip()        
  #      if (price == '-'):
  #          price = '0.00'        

        price_div = html_page.find('div', class_='value text-white mb-0 me-2 lh-1 stock-info')
        if price_div:
            price = price_div.text.strip()
        else:
            print(f"Price div not found for {name}")
            price = '0.00'     
            
        # Try to find the <h3> tag with the class 'theme-success'
        h3_tag = html_page.find('h3', class_='theme-success')
        if h3_tag:
        # Find all <span> tags within the found <h3> tag
            span_tags = h3_tag.find_all('span')
    
            if len(span_tags) > 1:
                # Extract the text from the second <span> tag
                percent_span = span_tags[1].text
                # print(percent_span)
                
        # Try to find the <h3> tag with the class 'theme-danger'
        h3_tag = html_page.find('h3', class_='theme-danger')
        if h3_tag:
        # Find all <span> tags within the found <h3> tag
            span_tags = h3_tag.find_all('span')
    
            if len(span_tags) > 1:
                # Extract the text from the second <span> tag
                percent_span = span_tags[1].text
                # print(percent_span)    
                
        # Try to find the <h3> tag with the class 'theme-danger'
        h3_tag = html_page.find('h3', class_='theme-normal')
        if h3_tag:
        # Find all <span> tags within the found <h3> tag
            span_tags = h3_tag.find_all('span')
    
            if len(span_tags) > 1:
                # Extract the text from the second <span> tag
                percent_span = span_tags[1].text
                # print(percent_span)   
                
        percent = cvt_str_to_flt(percent_span)
                
        values_low = html_page.find_all('span', class_='title-font-family fs-16px fw-bolder me-auto lh-1')
        today_low = values_low[0].text
        if (today_low == '-'):
            today_low = '0.00'
        
        values_high = html_page.find_all('span', class_='title-font-family fs-16px fw-bolder lh-1')
        today_high = values_high[0].text
        if (today_high == '-'):
            today_high = '0.00'         
        
        year_low = values_low[1].text        
        year_high = values_high[1].text     
        
        # Find the div with the specific class, then find the span within it
        div = html_page.find('div', class_='price-detail-date d-flex align-items-center text-nowrap fs-12px')
        if div:
            span = div.find('span')
            if span:
                text = span.get_text()
#                 print(text)
            else:
                print("Span not found")
        else:
            print("Div not found")
            
        # Extract the date part from the string
        # Assuming the date is always in the format 'dd Mon yyyy'
        date_str = ' '.join(text.split()[2:5])

        # Parse the date string into a datetime object
        date_obj = datetime.strptime(date_str, '%d %b %Y')

        # Format the datetime object to 'yyyy-mm-dd'
        updated_at = date_obj.strftime('%Y-%m-%d')

#         print(updated_at)
        
        # Append row to the DataFrame and print the row
        out_df.loc[len(out_df)] = [name, price, today_low, today_high, year_low, year_high, percent, updated_at]
#       print(out_df.iloc[-1].to_string(header=False, index=False)) 
        print(','.join(map(str, out_df.iloc[-1])))
        sleep(4)
        
    return out_df  # return the final dataframe with all values populated

In [10]:
start_time = strftime("%I:%M %p")
print('Start at: ', start_time)

Start at:  09:00 PM

In [11]:
df = pd.read_csv(input_file, header=None)
out_df = get_stock_data(df)

ACE,1.44,1.36,1.52,1.26,1.36,6.67,2026-07-20
ADVANC,383.00,377.00,383.00,285.00,410.00,1.06,2026-07-20
AEONTS,109.00,107.50,109.00,86.50,122.50,0.93,2026-07-20
AH,15.20,15.10,15.50,11.70,15.80,-1.3,2026-07-20
AIE,1.20,1.19,1.23,0.90,1.37,0.84,2026-07-20
AIMIRT,12.20,12.20,12.30,9.45,12.50,-0.81,2026-07-20
AIT,4.92,4.88,4.92,4.64,5.30,0.0,2026-07-20
AMATA,28.25,27.75,28.50,14.00,28.75,2.73,2026-07-20
ANAN,0.37,0.36,0.37,0.31,0.60,0.0,2026-07-20
AOT,64.00,63.25,64.00,35.00,65.00,0.0,2026-07-20
AP,8.05,8.05,8.15,6.85,9.70,-0.62,2026-07-20
ASIAN,7.30,7.25,7.35,6.75,8.25,0.0,2026-07-20
ASK,12.20,12.10,12.40,7.00,12.60,-0.81,2026-07-20
ASP,2.34,2.30,2.36,1.97,2.80,0.86,2026-07-20
ASW,7.55,7.45,7.60,4.90,8.20,0.0,2026-07-20
AWC,2.82,2.74,2.82,1.90,2.84,1.44,2026-07-20
BA,18.60,18.10,18.60,12.00,19.10,1.09,2026-07-20
BAM,7.00,6.80,7.00,6.20,8.60,2.19,2026-07-20
BBL,203.00,198.50,204.00,141.50,204.00,0.5,2026-07-20
BCH,10.80,10.50,10.80,9.10,14.70,0.0,2026-07-20
BCP,43.50,42.50,44.00,24.20,42.75,2.35,2026-07-20
BCPG,7.55,7.45,7.55,5.30,9.60,0.67,2026-07-20
BDMS,19.60,19.30,19.80,17.40,22.90,-0.51,2026-07-20
BEAUTY,0.37,0.36,0.38,0.27,0.68,-2.63,2026-07-20
BEC,2.12,2.12,2.14,1.72,2.72,0.0,2026-07-20
BEM,6.80,6.55,6.95,4.84,6.65,2.26,2026-07-20
BGC,6.85,6.85,6.90,3.30,7.15,0.0,2026-07-20
BGRIM,19.70,19.60,20.20,10.30,20.30,-2.48,2026-07-20
BH,183.50,182.00,187.00,136.00,214.00,-1.61,2026-07-20
BJC,15.00,14.70,15.10,12.80,21.10,1.35,2026-07-20
BKIH,373.00,372.00,373.00,285.00,378.00,0.0,2026-07-20
BLA,27.00,26.75,27.50,16.50,27.50,-0.92,2026-07-20
BLAND,0.70,0.70,0.78,0.40,0.76,-1.41,2026-07-20
BTS,2.14,2.14,2.16,1.98,3.74,-0.93,2026-07-20
BTSGIF,2.44,2.42,2.44,2.40,2.72,0.0,2026-07-20
CBG,51.50,50.75,52.00,32.75,62.00,0.0,2026-07-20
CENTEL,38.00,37.25,38.25,25.50,40.50,-0.65,2026-07-20
CHG,1.60,1.58,1.62,1.33,1.87,-1.84,2026-07-20
CK,18.90,18.30,19.00,11.10,20.70,2.16,2026-07-20
CKP,2.68,2.64,2.70,2.12,3.00,0.0,2026-07-20
COM7,30.25,29.50,30.50,18.20,30.25,0.83,2026-07-20
CPALL,47.50,46.75,47.75,40.50,54.50,1.06,2026-07-20
CPAXT,15.00,14.80,15.00,13.90,23.40,0.67,2026-07-20
CPF,22.40,21.90,22.40,18.10,24.70,1.82,2026-07-20
CPN,68.75,68.00,68.75,49.00,70.50,0.0,2026-07-20
CPNCG,5.55,5.45,5.55,4.90,6.50,0.91,2026-07-20
CPNREIT,13.50,13.20,13.50,10.60,13.50,1.5,2026-07-20
CRC,23.90,23.00,23.90,16.50,25.25,3.02,2026-07-20
DCC,1.47,1.46,1.48,1.13,1.54,-0.68,2026-07-20
DCON,0.19,0.18,0.19,0.17,0.30,5.56,2026-07-20
DELTA,295.00,292.00,298.00,130.50,372.00,-1.67,2026-07-20
DIF,10.30,10.20,10.30,8.05,10.40,0.98,2026-07-20
DOHOME,3.92,3.82,3.94,3.02,4.35,1.55,2026-07-20
EA,3.10,3.08,3.14,2.40,3.88,-0.64,2026-07-20
EGATIF,6.20,6.15,6.20,5.75,6.40,0.81,2026-07-20
EGCO,132.00,131.00,134.00,106.00,143.00,0.38,2026-07-20
EPG,6.65,6.40,6.65,2.76,6.65,2.31,2026-07-20
FORTH,15.30,14.80,15.80,5.45,18.90,1.32,2026-07-20
FSMART,7.85,7.80,8.10,5.50,9.85,0.0,2026-07-20
GC,5.05,4.98,5.30,3.54,5.10,1.41,2026-07-20
GFPT,9.85,9.70,9.85,8.50,11.00,2.6,2026-07-20
GLOBAL,7.35,7.30,7.55,5.25,8.44,-1.34,2026-07-20
GPSC,54.50,54.25,55.75,30.00,55.00,0.0,2026-07-20
GULF,67.25,66.50,68.00,39.75,68.50,-0.37,2026-07-20
GUNKUL,5.30,5.25,5.45,1.57,5.35,0.0,2026-07-20
GVREIT,8.50,8.35,8.50,6.15,8.40,1.19,2026-07-20
HANA,37.50,36.25,38.00,15.10,42.00,2.04,2026-07-20
HFT,3.98,3.98,4.00,3.48,4.60,-0.5,2026-07-20
HMPRO,6.65,6.60,6.75,5.75,8.00,0.0,2026-07-20
HTC,16.10,15.90,16.20,14.60,16.40,0.63,2026-07-20
ICHI,14.90,14.60,14.90,10.30,15.20,0.68,2026-07-20
III,4.48,4.42,4.52,3.72,5.25,0.9,2026-07-20
ILM,13.30,13.10,13.30,12.10,16.20,0.76,2026-07-20
IMH,3.04,2.98,3.04,2.70,4.48,1.33,2026-07-20
IMPACT,12.50,12.30,12.60,9.55,12.50,0.81,2026-07-20
IP,5.00,4.98,5.10,3.14,5.05,-0.99,2026-07-20
IRPC,2.16,2.12,2.28,0.86,2.34,0.93,2026-07-20
IVL,24.60,24.60,25.25,14.60,26.25,0.41,2026-07-20
3BBIF,6.60,6.55,6.60,6.00,6.95,0.76,2026-07-20
JMART,11.50,11.30,11.70,5.80,12.80,-0.86,2026-07-20
JMT,12.10,12.00,12.30,7.65,13.50,-0.82,2026-07-20
KBANK,238.00,232.00,238.00,157.00,237.00,1.71,2026-07-20
KCE,41.25,39.50,41.75,16.00,46.00,0.0,2026-07-20
KGI,4.78,4.74,4.80,3.74,4.84,0.0,2026-07-20
KKP,109.50,104.00,109.50,48.00,107.50,3.3,2026-07-20
KTB,42.25,41.25,42.25,21.10,42.00,1.81,2026-07-20
KTC,40.50,39.75,41.25,24.40,39.25,3.85,2026-07-20
LALIN,4.44,4.38,4.44,4.26,5.15,0.45,2026-07-20
LANNA,14.80,14.80,14.90,14.00,16.90,0.0,2026-07-20
LH,3.80,3.76,3.80,3.40,4.50,0.0,2026-07-20
LIT,0.87,0.87,0.89,0.58,1.01,-1.14,2026-07-20
LPN,1.61,1.60,1.62,1.46,1.83,-0.62,2026-07-20
M,21.70,21.40,22.40,17.00,35.25,0.46,2026-07-20
MAJOR,6.95,6.80,6.95,6.25,9.45,0.72,2026-07-20
MBAX,2.02,1.99,2.04,1.31,2.60,0.0,2026-07-20
MC,11.70,11.60,11.70,9.90,12.50,0.0,2026-07-20
MCS,8.00,8.00,8.05,7.20,9.75,-0.62,2026-07-20
MEGA,37.75,37.25,38.00,27.75,40.00,0.0,2026-07-20
MINT,24.10,23.60,24.10,19.60,27.00,2.12,2026-07-20
MST,8.15,8.10,8.20,6.50,8.35,0.0,2026-07-20
MTC,34.75,33.00,34.75,26.75,44.00,4.51,2026-07-20
NER,4.54,4.52,4.56,4.08,5.40,0.0,2026-07-20
NOBLE,1.89,1.88,1.92,1.68,2.72,-1.56,2026-07-20
ONEE,3.26,3.26,3.32,1.94,3.40,0.0,2026-07-20
OR,13.10,12.90,13.20,10.40,15.60,0.77,2026-07-20
ORI,2.02,1.98,2.04,1.63,3.12,3.06,2026-07-20
OSP,17.90,17.30,18.00,13.70,19.50,2.87,2026-07-20
PCSGH,3.04,3.00,3.04,2.88,3.32,1.33,2026-07-20
PDG,3.16,3.10,3.18,2.68,3.22,-1.86,2026-07-20
PLANB,5.45,5.45,5.65,3.00,5.85,-2.68,2026-07-20
POPF,8.35,8.30,8.35,5.70,8.50,-0.6,2026-07-20
PREB,3.50,3.46,3.50,3.30,4.10,0.57,2026-07-20
PRM,9.45,9.30,9.45,5.95,9.45,1.61,2026-07-20
PROSPECT,10.50,10.40,10.60,6.60,10.80,-0.94,2026-07-20
PSH,3.98,3.94,3.98,3.30,4.66,0.51,2026-07-20
PSL,8.10,8.00,8.35,5.70,8.45,5.19,2026-07-20
PTG,7.85,7.75,7.85,6.30,10.20,0.0,2026-07-20
PTL,14.40,14.40,14.50,7.50,14.90,-0.69,2026-07-20
PTT,39.25,38.50,39.25,30.00,39.00,1.29,2026-07-20
PTTEP,146.50,146.00,148.50,104.00,164.00,0.69,2026-07-20
PTTGC,37.00,37.00,38.00,19.00,41.25,0.0,2026-07-20
QH,1.41,1.40,1.42,1.21,1.53,0.0,2026-07-20
RATCH,38.00,37.50,38.00,25.00,38.25,0.0,2026-07-20
RBF,4.94,4.94,5.00,2.90,5.25,-1.2,2026-07-20
RCL,33.25,32.50,34.00,24.70,34.50,3.1,2026-07-20
RJH,15.10,14.80,15.10,11.10,15.20,0.0,2026-07-20
ROJNA,6.25,6.15,6.30,4.26,6.20,1.63,2026-07-20
SAPPE,33.75,32.25,34.00,28.50,41.75,3.85,2026-07-20
SAT,16.20,16.10,16.20,12.30,16.70,0.0,2026-07-20
SAWAD,26.25,25.50,26.25,18.00,32.00,3.96,2026-07-20
SC,1.99,1.98,2.00,1.54,2.16,0.51,2026-07-20
SCB,158.50,155.00,159.00,118.00,160.00,0.96,2026-07-20
SCC,257.00,252.00,258.00,163.00,256.00,1.18,2026-07-20
SCCC,149.00,148.00,149.50,138.00,157.00,0.34,2026-07-20
SCGP,30.25,29.00,30.75,14.90,30.00,4.31,2026-07-20
SENA,1.81,1.80,1.83,1.63,2.10,0.0,2026-07-20
SGP,7.95,7.95,8.10,5.00,9.30,-0.63,2026-07-20
SINGER,12.60,12.50,13.20,4.10,13.40,-3.82,2026-07-20
SIRI,1.50,1.50,1.52,1.29,1.60,0.0,2026-07-20
SIS,26.00,25.50,26.25,18.30,26.50,0.97,2026-07-20
SJWD,9.10,8.85,9.10,6.40,10.80,2.82,2026-07-20
SMPC,9.45,9.40,9.50,8.35,9.45,0.53,2026-07-20
SNC,8.20,8.05,8.25,5.50,8.35,1.23,2026-07-20
SPALI,16.00,15.80,16.10,14.80,19.00,0.0,2026-07-20
SPCG,9.35,9.30,9.40,7.95,10.30,0.0,2026-07-20
SPRC,9.25,9.20,9.40,4.28,9.25,1.65,2026-07-20
SSP,4.36,4.12,4.38,3.00,4.34,7.39,2026-07-20
STA,18.70,18.60,19.10,11.20,20.50,0.0,2026-07-20
STGT,10.70,10.60,10.70,6.05,12.20,0.0,2026-07-20
SUPER,0.13,0.12,0.14,0.09,0.16,0.0,2026-07-20
SUPEREIF,6.30,6.25,6.30,5.00,6.35,0.0,2026-07-20
SYNEX,9.75,9.65,9.85,8.55,12.80,1.04,2026-07-20
TASCO,14.20,13.90,14.30,12.40,15.70,-0.7,2026-07-20
TCAP,74.50,71.25,74.50,47.00,73.00,4.2,2026-07-20
TFFIF,6.85,6.75,6.90,5.75,6.95,1.48,2026-07-20
TFG,10.40,10.30,10.50,4.24,11.60,0.97,2026-07-20
THANI,2.22,2.16,2.26,1.52,2.24,1.83,2026-07-20
THG,7.45,7.40,7.55,6.15,9.90,-0.67,2026-07-20
TIPH,23.70,23.50,23.70,18.10,23.90,0.42,2026-07-20
TISCO,133.00,129.00,133.00,97.50,130.00,3.5,2026-07-20
TKN,4.14,4.10,4.16,3.66,6.45,0.49,2026-07-20
TKS,7.35,7.35,7.45,5.20,7.50,-1.34,2026-07-20
TMT,3.38,3.32,3.38,2.68,4.18,1.81,2026-07-20
TOA,15.60,15.40,15.70,11.50,16.40,-0.64,2026-07-20
TOP,62.75,62.50,64.50,29.75,62.25,1.21,2026-07-20
TPIPL,0.87,0.86,0.90,0.65,0.97,-3.33,2026-07-20
TPIPP,1.83,1.82,1.84,1.66,2.44,0.55,2026-07-20
TQM,17.00,16.00,17.20,10.60,16.50,4.94,2026-07-20
TRUE,13.90,13.90,14.10,10.10,15.00,-0.71,2026-07-20
TSE,0.82,0.81,0.86,0.34,1.08,1.23,2026-07-20
TSTH,0.98,0.97,1.03,0.62,1.05,2.08,2026-07-20
TTA,5.15,5.10,5.25,3.94,5.55,1.98,2026-07-20
TTB,2.96,2.70,3.00,1.80,2.74,8.82,2026-07-20
TTLPF,9.45,9.40,9.45,8.80,11.20,0.0,2026-07-20
TTW,10.30,10.20,10.40,8.85,10.30,0.98,2026-07-20
TU,11.90,11.80,12.00,10.20,14.10,0.0,2026-07-20
TVO,27.00,27.00,27.25,21.00,27.25,0.0,2026-07-20
TYCN,1.67,1.65,1.70,1.54,1.86,0.0,2026-07-20
UTP,8.35,8.25,8.35,7.10,8.60,1.21,2026-07-20
VGI,1.02,1.01,1.03,0.77,2.28,-0.97,2026-07-20
VIBHA,1.34,1.34,1.35,1.32,1.66,-0.74,2026-07-20
VNG,2.12,1.99,2.20,1.64,2.28,6.0,2026-07-20
WHA,5.45,5.35,5.55,3.08,5.55,0.0,2026-07-20
WHAIR,8.10,8.05,8.15,5.05,8.15,0.0,2026-07-20
WHART,11.10,10.90,11.20,8.85,11.20,0.91,2026-07-20
WHAUP,7.95,7.80,8.00,3.24,8.50,0.0,2026-07-20
WICE,3.60,3.28,3.60,2.20,3.80,10.43,2026-07-20
WORK,3.50,3.44,3.50,3.34,4.60,-0.57,2026-07-20

In [12]:
end_time = strftime("%I:%M %p")
print('End at: ', end_time)

End at:  09:14 PM

In [13]:
out_df.query('price == "-"')

Empty DataFrame
Columns: [name, price, today_low, today_high, year_low, year_high, percent, updated_at]
Index: []

In [14]:
out_df.shape

(188, 8)

In [15]:
out_df = out_df[out_df['name'] != 'TYCN']

In [16]:
out_df = out_df[out_df['name'] != 'MST']

In [17]:
out_df = out_df[out_df['name'] != 'PDG']

In [18]:
out_df = out_df[out_df['name'] != 'PREB']

In [19]:
out_df = out_df[out_df['name'] != 'MBAX']

In [20]:
out_df.shape

(183, 8)

In [21]:
out_df['price'] = out_df['price'].astype('float')
out_df['today_low'] = out_df['today_low'].astype('float')
out_df['today_high'] = out_df['today_high'].astype('float')
out_df['year_low'] = out_df['year_low'].astype('float')
out_df['year_high'] = out_df['year_high'].astype('float')
out_df['percent'] = out_df['percent'].astype('float')

In [22]:
sorted_out_df = out_df.sort_values('percent')

In [23]:
sorted_out_df.query('today_low < year_low')

Empty DataFrame
Columns: [name, price, today_low, today_high, year_low, year_high, percent, updated_at]
Index: []

In [24]:
sorted_out_df.query('today_high > year_high')

,name,price,today_low,today_high,year_low,year_high,percent,updated_at
32,BLAND,0.70,0.70,0.78,0.40,0.76,-1.41,2026-07-20
75,IP,5.00,4.98,5.10,3.14,5.05,-0.99,2026-07-20
62,GPSC,54.50,54.25,55.75,30.00,55.00,0.00,2026-07-20
64,GUNKUL,5.30,5.25,5.45,1.57,5.35,0.00,2026-07-20
141,SMPC,9.45,9.40,9.50,8.35,9.45,0.53,2026-07-20
74,IMPACT,12.50,12.30,12.60,9.55,12.50,0.81,2026-07-20
40,COM7,30.25,29.50,30.50,18.20,30.25,0.83,2026-07-20
174,TTW,10.30,10.20,10.40,8.85,10.30,0.98,2026-07-20
132,SCC,257.00,252.00,258.00,163.00,256.00,1.18,2026-07-20
65,GVREIT,8.50,8.35,8.50,6.15,8.40,1.19,2026-07-20
164,TOP,62.75,62.50,64.50,29.75,62.25,1.21,2026-07-20
118,PTT,39.25,38.50,39.25,30.00,39.00,1.29,2026-07-20
59,GC,5.05,4.98,5.30,3.54,5.10,1.41,2026-07-20
126,ROJNA,6.25,6.15,6.30,4.26,6.20,1.63,2026-07-20
145,SPRC,9.25,9.20,9.40,4.28,9.25,1.65,2026-07-20
81,KBANK,238.00,232.00,238.00,157.00,237.00,1.71,2026-07-20
85,KTB,42.25,41.25,42.25,21.10,42.00,1.81,2026-07-20
156,THANI,2.22,2.16,2.26,1.52,2.24,1.83,2026-07-20
25,BEM,6.80,6.55,6.95,4.84,6.65,2.26,2026-07-20
20,BCP,43.50,42.50,44.00,24.20,42.75,2.35,2026-07-20
84,KKP,109.50,104.00,109.50,48.00,107.50,3.30,2026-07-20
159,TISCO,133.00,129.00,133.00,97.50,130.00,3.50,2026-07-20
86,KTC,40.50,39.75,41.25,24.40,39.25,3.85,2026-07-20
153,TCAP,74.50,71.25,74.50,47.00,73.00,4.20,2026-07-20
134,SCGP,30.25,29.00,30.75,14.90,30.00,4.31,2026-07-20
167,TQM,17.00,16.00,17.20,10.60,16.50,4.94,2026-07-20
0,ACE,1.44,1.36,1.52,1.26,1.36,6.67,2026-07-20
146,SSP,4.36,4.12,4.38,3.00,4.34,7.39,2026-07-20
172,TTB,2.96,2.70,3.00,1.80,2.74,8.82,2026-07-20

In [25]:
out_df.query('today_high > year_high')

,name,price,today_low,today_high,year_low,year_high,percent,updated_at
0,ACE,1.44,1.36,1.52,1.26,1.36,6.67,2026-07-20
20,BCP,43.50,42.50,44.00,24.20,42.75,2.35,2026-07-20
25,BEM,6.80,6.55,6.95,4.84,6.65,2.26,2026-07-20
32,BLAND,0.70,0.70,0.78,0.40,0.76,-1.41,2026-07-20
40,COM7,30.25,29.50,30.50,18.20,30.25,0.83,2026-07-20
59,GC,5.05,4.98,5.30,3.54,5.10,1.41,2026-07-20
62,GPSC,54.50,54.25,55.75,30.00,55.00,0.00,2026-07-20
64,GUNKUL,5.30,5.25,5.45,1.57,5.35,0.00,2026-07-20
65,GVREIT,8.50,8.35,8.50,6.15,8.40,1.19,2026-07-20
74,IMPACT,12.50,12.30,12.60,9.55,12.50,0.81,2026-07-20
75,IP,5.00,4.98,5.10,3.14,5.05,-0.99,2026-07-20
81,KBANK,238.00,232.00,238.00,157.00,237.00,1.71,2026-07-20
84,KKP,109.50,104.00,109.50,48.00,107.50,3.30,2026-07-20
85,KTB,42.25,41.25,42.25,21.10,42.00,1.81,2026-07-20
86,KTC,40.50,39.75,41.25,24.40,39.25,3.85,2026-07-20
118,PTT,39.25,38.50,39.25,30.00,39.00,1.29,2026-07-20
126,ROJNA,6.25,6.15,6.30,4.26,6.20,1.63,2026-07-20
132,SCC,257.00,252.00,258.00,163.00,256.00,1.18,2026-07-20
134,SCGP,30.25,29.00,30.75,14.90,30.00,4.31,2026-07-20
141,SMPC,9.45,9.40,9.50,8.35,9.45,0.53,2026-07-20
145,SPRC,9.25,9.20,9.40,4.28,9.25,1.65,2026-07-20
146,SSP,4.36,4.12,4.38,3.00,4.34,7.39,2026-07-20
153,TCAP,74.50,71.25,74.50,47.00,73.00,4.20,2026-07-20
156,THANI,2.22,2.16,2.26,1.52,2.24,1.83,2026-07-20
159,TISCO,133.00,129.00,133.00,97.50,130.00,3.50,2026-07-20
164,TOP,62.75,62.50,64.50,29.75,62.25,1.21,2026-07-20
167,TQM,17.00,16.00,17.20,10.60,16.50,4.94,2026-07-20
172,TTB,2.96,2.70,3.00,1.80,2.74,8.82,2026-07-20
174,TTW,10.30,10.20,10.40,8.85,10.30,0.98,2026-07-20

In [26]:
file_name = "Price-Hilo.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [27]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price-Hilo.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price-Hilo.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price-Hilo.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price-Hilo.csv

In [28]:
out_df.to_csv(output_file, index=False)  
out_df.to_csv(god_file, index=False) 
out_df.to_csv(icd_file, index=False)  
out_df.to_csv(osd_file, index=False)

In [29]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-07-20 21:14:39